# Generated by Django 6.0.6 on 2026-08-05 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_alter_reportrun_report_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportrun',
            name='report_type',
            field=models.CharField(choices=[('employee_register', 'Employee Leave Register'), ('monthly_attendance', 'Monthly Attendance Report'), ('leave_utilization', 'Leave Utilization Report'), ('compliance', 'Compliance Report'), ('audit_trail', 'Audit Trail Report'), ('attendance_vs_leave', 'Attendance vs Leave'), ('attendance_vs_wfh', 'Attendance vs WFH'), ('overtime_summary', 'Overtime Summary'), ('late_arrival_summary', 'Late Arrival Summary'), ('shift_utilization', 'Shift Utilization'), ('department_attendance', 'Department Attendance'), ('comp_off_report', 'Comp Off Summary'), ('monthly_workforce_summary', 'Monthly Workforce Summary'), ('executive_summary', 'Executive Summary'), ('department_analytics', 'Department Analytics'), ('attendance_analytics', 'Attendance Analytics'), ('overtime_analytics', 'Overtime Analytics'), ('workforce_analytics', 'Workforce Analytics')], max_length=40),
        ),
        migrations.AlterField(
            model_name='scheduledreport',
            name='report_type',
            field=models.CharField(choices=[('employee_register', 'Employee Leave Register'), ('monthly_attendance', 'Monthly Attendance Report'), ('leave_utilization', 'Leave Utilization Report'), ('compliance', 'Compliance Report'), ('audit_trail', 'Audit Trail Report'), ('attendance_vs_leave', 'Attendance vs Leave'), ('attendance_vs_wfh', 'Attendance vs WFH'), ('overtime_summary', 'Overtime Summary'), ('late_arrival_summary', 'Late Arrival Summary'), ('shift_utilization', 'Shift Utilization'), ('department_attendance', 'Department Attendance'), ('comp_off_report', 'Comp Off Summary'), ('monthly_workforce_summary', 'Monthly Workforce Summary'), ('executive_summary', 'Executive Summary'), ('department_analytics', 'Department Analytics'), ('attendance_analytics', 'Attendance Analytics'), ('overtime_analytics', 'Overtime Analytics'), ('workforce_analytics', 'Workforce Analytics')], max_length=40),
        ),
    ]
