# Generated by Django 5.2.16 on 2026-10-04 12:33

import reports.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_add_department_ownership_report_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportrun',
            name='file',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to=reports.models.report_upload_path),
        ),
    ]
