# Generated by Django 5.2.16 on 2026-07-14 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_notificationlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='category',
            field=models.CharField(choices=[('MEMO_ASSIGNED_TO_REVIEW', 'Memo assigned to review'), ('MEMO_APPROVED', 'Memo approved'), ('MEMO_REJECTED', 'Memo rejected'), ('MEMO_RETURNED', 'Memo returned'), ('LEAVE_SUBMITTED', 'Leave submitted'), ('LEAVE_APPROVED', 'Leave approved'), ('LEAVE_REJECTED', 'Leave rejected'), ('LEAVE_BALANCE_LOW', 'Leave balance low'), ('POLICY_UPDATED', 'Policy updated'), ('SYSTEM_ANNOUNCEMENT', 'System announcement'), ('WEEKLY_DIGEST', 'Weekly digest'), ('INVENTORY_TAKEOUT_REQUESTED', 'Inventory take-out requested'), ('INVENTORY_TAKEOUT_APPROVED', 'Inventory take-out approved'), ('INVENTORY_TAKEOUT_REJECTED', 'Inventory take-out rejected')], db_index=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='notificationpreference',
            name='category',
            field=models.CharField(choices=[('MEMO_ASSIGNED_TO_REVIEW', 'Memo assigned to review'), ('MEMO_APPROVED', 'Memo approved'), ('MEMO_REJECTED', 'Memo rejected'), ('MEMO_RETURNED', 'Memo returned'), ('LEAVE_SUBMITTED', 'Leave submitted'), ('LEAVE_APPROVED', 'Leave approved'), ('LEAVE_REJECTED', 'Leave rejected'), ('LEAVE_BALANCE_LOW', 'Leave balance low'), ('POLICY_UPDATED', 'Policy updated'), ('SYSTEM_ANNOUNCEMENT', 'System announcement'), ('WEEKLY_DIGEST', 'Weekly digest'), ('INVENTORY_TAKEOUT_REQUESTED', 'Inventory take-out requested'), ('INVENTORY_TAKEOUT_APPROVED', 'Inventory take-out approved'), ('INVENTORY_TAKEOUT_REJECTED', 'Inventory take-out rejected')], max_length=40),
        ),
    ]
