# Generated by Django 5.2.16 on 2026-08-04 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_alter_notification_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='category',
            field=models.CharField(choices=[('MEMO_ASSIGNED_TO_REVIEW', 'Memo assigned to review'), ('MEMO_APPROVED', 'Memo approved'), ('MEMO_REJECTED', 'Memo rejected'), ('MEMO_RETURNED', 'Memo returned'), ('LEAVE_SUBMITTED', 'Leave submitted'), ('LEAVE_APPROVED', 'Leave approved'), ('LEAVE_REJECTED', 'Leave rejected'), ('LEAVE_BALANCE_LOW', 'Leave balance low'), ('POLICY_UPDATED', 'Policy updated'), ('SYSTEM_ANNOUNCEMENT', 'System announcement'), ('WEEKLY_DIGEST', 'Weekly digest'), ('INVENTORY_TAKEOUT_REQUESTED', 'Inventory take-out requested'), ('INVENTORY_TAKEOUT_APPROVED', 'Inventory take-out approved'), ('INVENTORY_TAKEOUT_REJECTED', 'Inventory take-out rejected'), ('ATTENDANCE_CORRECTION_SUBMITTED', 'Attendance correction submitted'), ('ATTENDANCE_CORRECTION_MANAGER_APPROVED', 'Attendance correction approved by department head'), ('ATTENDANCE_CORRECTION_APPROVED', 'Attendance correction applied'), ('ATTENDANCE_CORRECTION_REJECTED', 'Attendance correction rejected'), ('WFH_SUBMITTED', 'Work-from-home requested'), ('WFH_APPROVED', 'Work-from-home approved'), ('WFH_REJECTED', 'Work-from-home rejected'), ('COMP_OFF_CONFIRMED', 'Compensatory day confirmed')], db_index=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='notificationpreference',
            name='category',
            field=models.CharField(choices=[('MEMO_ASSIGNED_TO_REVIEW', 'Memo assigned to review'), ('MEMO_APPROVED', 'Memo approved'), ('MEMO_REJECTED', 'Memo rejected'), ('MEMO_RETURNED', 'Memo returned'), ('LEAVE_SUBMITTED', 'Leave submitted'), ('LEAVE_APPROVED', 'Leave approved'), ('LEAVE_REJECTED', 'Leave rejected'), ('LEAVE_BALANCE_LOW', 'Leave balance low'), ('POLICY_UPDATED', 'Policy updated'), ('SYSTEM_ANNOUNCEMENT', 'System announcement'), ('WEEKLY_DIGEST', 'Weekly digest'), ('INVENTORY_TAKEOUT_REQUESTED', 'Inventory take-out requested'), ('INVENTORY_TAKEOUT_APPROVED', 'Inventory take-out approved'), ('INVENTORY_TAKEOUT_REJECTED', 'Inventory take-out rejected'), ('ATTENDANCE_CORRECTION_SUBMITTED', 'Attendance correction submitted'), ('ATTENDANCE_CORRECTION_MANAGER_APPROVED', 'Attendance correction approved by department head'), ('ATTENDANCE_CORRECTION_APPROVED', 'Attendance correction applied'), ('ATTENDANCE_CORRECTION_REJECTED', 'Attendance correction rejected'), ('WFH_SUBMITTED', 'Work-from-home requested'), ('WFH_APPROVED', 'Work-from-home approved'), ('WFH_REJECTED', 'Work-from-home rejected'), ('COMP_OFF_CONFIRMED', 'Compensatory day confirmed')], max_length=40),
        ),
    ]
