# Generated by Django 5.2.16 on 2026-09-03 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0014_appraisal_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationlog',
            name='reference',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
    ]
