#!/usr/bin/env bash
#
# Run the whole OMS locally: database, backend, biometric collector, frontend.
#
#   ./run-local.sh              # start everything, Ctrl-C stops it all
#   ./run-local.sh --no-sync    # everything except the biometric collector
#   ./run-local.sh --check      # verify the setup and exit, starting nothing
#
# WHAT THIS RUNS AGAINST
# ----------------------
# SQLite at backend/db.sqlite3, which is where this machine's biometric history
# already lives (11k+ punches imported from the terminal, and the derived
# attendance built from them). The repo's .env points at PostgreSQL because that
# is the production and all-in-Docker layout; pointing a local run there instead
# would come up against an empty database and look like the history had been
# lost. Nothing here writes to .env — the two configurations coexist.
#
# The backend runs on the HOST rather than in Docker so the collector can open a
# TCP session to the terminal on the LAN directly, with no bridge network in the
# path.
set -euo pipefail

REPO="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ENV_FILE="$REPO/.env.local"
# 8000 is taken on this machine by an unrelated project; the frontend proxy and
# the browser both follow whatever is set here, so one value moves the backend.
BACKEND_PORT="${BACKEND_PORT:-8001}"
FRONTEND_PORT="${FRONTEND_PORT:-5173}"
REDIS_PORT="${REDIS_PORT:-6380}"
SYNC_INTERVAL="${SYNC_INTERVAL:-60}"
DEVICE_LABEL="${DEVICE_LABEL:-main-gate}"
DEVICE_TIMEOUT="${DEVICE_TIMEOUT:-90}"

WITH_SYNC=1
CHECK_ONLY=0
for arg in "$@"; do
  case "$arg" in
    --no-sync) WITH_SYNC=0 ;;
    --check)   CHECK_ONLY=1 ;;
    -h|--help) sed -n '2,20p' "$0"; exit 0 ;;
    *) echo "unknown option: $arg" >&2; exit 2 ;;
  esac
done

say()  { printf '\033[1;36m==>\033[0m %s\n' "$*"; }
warn() { printf '\033[1;33m !\033[0m %s\n' "$*"; }
die()  { printf '\033[1;31mERROR\033[0m %s\n' "$*" >&2; exit 1; }

# --- 1. local environment file ---------------------------------------------
# Generated rather than committed: .env.* is gitignored, and the secret key
# should be this machine's own.
if [[ ! -f "$ENV_FILE" ]]; then
  say "creating $ENV_FILE"
  cat > "$ENV_FILE" <<EOF
# Local development. Generated by run-local.sh — safe to edit.
# NOT used by docker-compose (that reads .env); this file is for host runs.

DJANGO_SECRET_KEY=$(python3 -c 'import secrets; print(secrets.token_urlsafe(50))')
DJANGO_DEBUG=True
DJANGO_ALLOWED_HOSTS=localhost,127.0.0.1

# The database holding this machine's imported biometric history.
DATABASE_ENGINE=sqlite3

# Channel layer + cache. Carries live punch events from the collector process
# to the browser's WebSocket; see docker-compose.local.yml.
REDIS_URL=redis://127.0.0.1:$REDIS_PORT/0

EMAIL_BACKEND=django.core.mail.backends.console.EmailBackend

# Biometric terminal. The address and timezone live on the BiometricDevice row,
# not here — these are only the connection tuning knobs.
BIOMETRIC_DEVICE_COMM_KEY=0
BIOMETRIC_DEVICE_TIMEOUT=$DEVICE_TIMEOUT
EOF
fi

set -a; source "$ENV_FILE"; set +a

# --- 2. prerequisites -------------------------------------------------------
VENV="$REPO/backend/.venv"
[[ -x "$VENV/bin/python" ]] || die "no virtualenv at $VENV — see docs/LOCAL_RUNBOOK.md §3"
PY="$VENV/bin/python"
[[ -d "$REPO/frontend/node_modules" ]] || die "frontend deps missing — run: cd frontend && npm install"

# Node >= 20.19 (package.json engines). The default node on this machine is
# 20.12, which does not merely warn — Vite's bundler calls util.styleText with
# an argument form 20.12 rejects, so `npm run dev` dies on an ERR_INVALID_ARG_VALUE
# stack trace that says nothing about versions. Prefer a new enough nvm install
# rather than making the operator remember to `nvm use` first.
node_ok() { [[ "$(printf '%s\n20.19.0\n' "$1" | sort -V | head -1)" == "20.19.0" ]]; }
NODE_BIN=""
if command -v node >/dev/null 2>&1 && node_ok "$(node -v | tr -d v)"; then
  NODE_BIN="$(dirname "$(command -v node)")"
else
  for candidate in $(ls -1 "$HOME/.nvm/versions/node" 2>/dev/null | sort -Vr); do
    if node_ok "${candidate#v}"; then
      NODE_BIN="$HOME/.nvm/versions/node/$candidate/bin"
      say "using Node $candidate (default is $(node -v 2>/dev/null || echo none), below the 20.19 minimum)"
      break
    fi
  done
  [[ -n "$NODE_BIN" ]] || die "Node >= 20.19 required (found $(node -v 2>/dev/null || echo none)). Install with: nvm install 22"
fi
export PATH="$NODE_BIN:$PATH"

# The connection is opened in a subshell so its descriptor is closed with it —
# no fd juggling in the caller, which is where an unopened-descriptor close
# could otherwise flip a busy port into a free-looking one.
port_busy() { (exec 3<>"/dev/tcp/127.0.0.1/$1") >/dev/null 2>&1; }

# --- 3. Redis ---------------------------------------------------------------
# Optional by design: without it the app still runs, the live feed just arrives
# on the browser's poll instead of instantly. That is a degraded mode worth
# having, not a reason to refuse to start.
if port_busy "$REDIS_PORT"; then
  say "Redis already up on $REDIS_PORT"
elif command -v docker >/dev/null 2>&1; then
  say "starting Redis on $REDIS_PORT"
  docker compose -f "$REPO/docker-compose.yml" -f "$REPO/docker-compose.local.yml" \
    up -d redis >/dev/null 2>&1 || warn "could not start Redis via docker compose"
  for _ in $(seq 1 20); do port_busy "$REDIS_PORT" && break; sleep 0.5; done
fi
if ! port_busy "$REDIS_PORT"; then
  warn "Redis unavailable — falling back to the in-process channel layer."
  warn "The dashboard will update on its 20s poll rather than instantly."
  unset REDIS_URL
fi

# --- 4. database ------------------------------------------------------------
cd "$REPO/backend"
say "applying migrations"
"$PY" manage.py migrate --no-input >/dev/null

PUNCHES=$("$PY" manage.py shell -c \
  'from biometric.models import AttendancePunch; print(AttendancePunch.objects.count())' 2>/dev/null | tail -1)
say "biometric punches in the local database: ${PUNCHES:-unknown}"
[[ "${PUNCHES:-0}" == "0" ]] && warn "no punch history — import it with: manage.py golive_import --device $DEVICE_LABEL --since 2000-01-01"

# --- 5. device reachability -------------------------------------------------
DEVICE_HOST=$("$PY" manage.py shell -c \
  "from biometric.models import BiometricDevice as D; d=D.objects.filter(label='$DEVICE_LABEL').first(); print(d.host if d else '')" \
  2>/dev/null | tail -1)
if [[ -n "$DEVICE_HOST" ]] && timeout 4 bash -c "exec 3<>/dev/tcp/$DEVICE_HOST/4370" 2>/dev/null; then
  say "terminal $DEVICE_HOST:4370 reachable"
elif [[ -n "$DEVICE_HOST" ]]; then
  warn "terminal $DEVICE_HOST:4370 NOT reachable — historical data still shows;"
  warn "today's new punches will not arrive until the LAN path is back."
else
  warn "no device labelled '$DEVICE_LABEL' is registered"
fi

if [[ "$CHECK_ONLY" == "1" ]]; then say "check complete"; exit 0; fi

# --- 6. start everything ----------------------------------------------------
port_busy "$BACKEND_PORT" && die "port $BACKEND_PORT is in use — set BACKEND_PORT=…"
port_busy "$FRONTEND_PORT" && die "port $FRONTEND_PORT is in use — set FRONTEND_PORT=…"

PIDS=()
cleanup() {
  trap - INT TERM EXIT
  say "stopping"
  # The collector traps SIGTERM and finishes its current cycle, so it is asked
  # to stop rather than killed — a half-written batch is not a thing we want.
  for pid in "${PIDS[@]}"; do kill "$pid" 2>/dev/null || true; done
  wait 2>/dev/null || true
}
trap cleanup INT TERM EXIT

say "backend      http://localhost:$BACKEND_PORT"
"$PY" manage.py runserver "0.0.0.0:$BACKEND_PORT" & PIDS+=($!)

if [[ "$WITH_SYNC" == "1" ]]; then
  say "collector    every ${SYNC_INTERVAL}s from $DEVICE_LABEL"
  "$PY" manage.py device_sync_loop --device "$DEVICE_LABEL" \
    --interval "$SYNC_INTERVAL" --timeout "$DEVICE_TIMEOUT" & PIDS+=($!)
fi

cd "$REPO/frontend"
# Vite reads this to proxy /api/v1, /media and /ws at the backend.
export VITE_API_URL="http://localhost:$BACKEND_PORT"
say "frontend     http://localhost:$FRONTEND_PORT"
# --strictPort: Vite's default is to walk to the next free port, which would
# print one URL here and serve on another. That matters more than usual because
# the WebSocket dials `window.location.host` — on the drifted port the browser
# still loads, the API still proxies, and only the live feed quietly fails.
npm run dev -- --port "$FRONTEND_PORT" --strictPort & PIDS+=($!)

say "up — Ctrl-C to stop everything"
wait
