/**
 * `services/api` for the QA harness (Phase 100.1).
 *
 * WHY A STUB AT THE AXIOS LAYER RATHER THAN PER-SERVICE MOCKS
 *
 * The harness seeds react-query caches directly, which works for Memo, Minute, Circular
 * and Inventory because those pages are react-query pages. The Leave module is not: its
 * pages are `useState` + `useEffect` calling `leaveService` (which calls `api`) straight
 * out. There is no cache to seed, so those screens rendered their error state and were
 * simply left out of the audit — the coverage gap Blockers 4, 5 and 6 name.
 *
 * Every one of the 24 service modules imports this one axios instance. Aliasing THIS is
 * therefore a single edit that unlocks all of them, and it keeps the stub honest: it
 * answers URLs, so a service that changes its endpoint stops matching and falls through
 * to the loud 404 below rather than silently serving stale data.
 *
 * Aliased in by qa/vite.qa.config.js, exactly as auth-stub.jsx is for useAuth.
 */
import fixtures from './leave-fixtures.json';
/* Phase 203. The Work Queue and Home fan out across every module, so the stub
   needs the other four generators' payloads too. All real serializer output -
   nothing here is hand-written, per the rule at the top of visual-qa.jsx. */
import memoFixtures from './memo-fixtures.json';
import minuteFixtures from './fixtures.json';
import circularFixtures from './circular-fixtures.json';
import inventoryFixtures from './inventory-fixtures.json';

/**
 * The asset register's own rows (Phase D1).
 *
 * Held here rather than in inventory-fixtures.json because that file is
 * GENERATED by inventory/tests/test_qa_fixture.py - anything hand-added to it
 * disappears the next time the generator runs. These six rows exist to give the
 * register capture one asset at each of the statuses whose styling this phase
 * touched, which is a QA concern rather than a backend snapshot.
 */
const REGISTER = {
  categories: [
    { id: 'c1', name: 'Laptops' },
    { id: 'c2', name: 'Furniture' },
    { id: 'c3', name: 'Vehicles' },
  ],
  employees: [
    { id: 'u1', full_name: 'Sunita Thapa', employee_id: 'NIF-014' },
    { id: 'u2', full_name: 'Bikash Karki', employee_id: 'NIF-021' },
  ],
  items: [
    { id: 'i1', asset_code: 'NIF-INV-0001', name: 'Dell Latitude 5540',
      asset_type_display: 'IT / Computing', category_name: 'Laptops',
      status: 'assigned', status_display: 'Assigned', brand: 'Dell', model: '5540',
      serial_number: 'DL5540-9931', assigned_to_name: 'Sunita Thapa' },
    { id: 'i2', asset_code: 'NIF-INV-0002', name: 'HP LaserJet Pro M404',
      asset_type_display: 'Peripheral', category_name: 'Laptops',
      status: 'available', status_display: 'Available', brand: 'HP', model: 'M404',
      serial_number: 'HP404-2210', assigned_to_name: null },
    { id: 'i3', asset_code: 'NIF-INV-0003', name: 'Executive Desk (Teak)',
      asset_type_display: 'Furniture', category_name: 'Furniture',
      status: 'available', status_display: 'Available', brand: '', model: '',
      serial_number: '', assigned_to_name: null },
    { id: 'i4', asset_code: 'NIF-INV-0004', name: 'Toyota Hilux 4x4',
      asset_type_display: 'Vehicle', category_name: 'Vehicles',
      status: 'out', status_display: 'Taken Out', brand: 'Toyota', model: 'Hilux',
      serial_number: 'BA-2-CHA-4471', assigned_to_name: 'Bikash Karki' },
    { id: 'i5', asset_code: 'NIF-INV-0005', name: 'Lenovo ThinkPad T14',
      asset_type_display: 'IT / Computing', category_name: 'Laptops',
      status: 'maintenance', status_display: 'Maintenance', brand: 'Lenovo', model: 'T14',
      serial_number: 'LT14-5580', assigned_to_name: null },
    { id: 'i6', asset_code: 'NIF-INV-0006', name: 'Epson EB-X51 Projector',
      asset_type_display: 'Peripheral', category_name: 'Laptops',
      status: 'retired', status_display: 'Retired', brand: 'Epson', model: 'EB-X51',
      serial_number: 'EPX51-0093', assigned_to_name: null },
  ],
};

/* An empty DRF page, for the two queue sources that have no fixture generator
   yet (inventory take-outs and attendance corrections). Serving an honest empty
   list is the alternative to inventing rows - the harness's founding rule. */
const EMPTY_PAGE = { count: 0, next: null, previous: null, results: [] };

/* Endpoint → payload. Ordered: the first pattern that matches wins, so the specific
   `/leaves/<id>/` entries must precede the bare `/leaves/` collection. */
const ROUTES = [
  // --- leave -----------------------------------------------------------------
  [/^\/leaves\/my-entitlements\/?$/,   () => fixtures.my_entitlements],
  [/^\/leaves\/leave-policy\/?$/,      () => fixtures.leave_policy],
  [/^\/leaves\/balance\/?$/,           () => fixtures.my_balance],
  [/^\/leaves\/([^/]+)\/?$/, (m) => {
    const byId = {
      [fixtures.pending_id]: fixtures.pending_detail,
      [fixtures.approved_id]: fixtures.approved_detail,
      [fixtures.rejected_id]: fixtures.rejected_detail,
    };
    return byId[m[1]] || fixtures.pending_detail;
  }],
  // The collection serves the reviewer queue when asked for it and the applicant's
  // own list otherwise — the same split `leaveService.getPendingApprovals()` makes
  // with `?queue=actionable`.
  [/^\/leaves\/?$/, (_m, config) => (
    config?.params?.queue === 'actionable' ? fixtures.pending_queue : fixtures.my_leaves
  )],

  // --- Phase 203: the six Work Queue sources + Home's own widgets ------------
  [/^\/attendance\/today\/?$/, () => ({
    status: 'present', check_in_local: '09:52', check_out_local: null,
    working_hours: '2.40', can_check_in: false, can_check_out: true,
  })],
  [/^\/drafts\/?$/, () => []],
  [/^\/memos\/dashboard\/?$/, () => memoFixtures.dashboard],
  [/^\/memos\/employees\/?$/, () => [
    { id: 'p1', full_name: 'Sunita Thapa', designation: 'Budget Officer',
      department: 'Finance', role_display: 'Employee' },
  ]],
  [/^\/memos\/?$/, () => memoFixtures.list],
  [/^\/minutes\/dashboard\/?$/, () => minuteFixtures.dashboard],
  [/^\/minutes\/?$/, () => minuteFixtures.list],
  [/^\/circulars\/dashboard\/?$/, () => circularFixtures.dashboard],
  [/^\/circulars\/?$/, () => circularFixtures.list],
  // Phase D1. The register page reads these three directly (no react-query
  // cache to seed), so the stub has to serve them or the capture is a blank.
  [/^\/inventory\/dashboard\/?$/, () => inventoryFixtures.dashboard],
  [/^\/inventory\/categories\/?$/, () => REGISTER.categories],
  [/^\/inventory\/employees\/?$/, () => REGISTER.employees],
  [/^\/inventory\/items\/?$/, (_m, config) => {
    const status = config?.params?.status;
    return status ? REGISTER.items.filter((r) => r.status === status) : REGISTER.items;
  }],
  [/^\/inventory\/takeouts\/?$/, () => EMPTY_PAGE],
  [/^\/inventory\/requests\/?$/, () => inventoryFixtures.requests],
  // Phase ASSET-LIFECYCLE-DISPOSAL. The detail route is matched FIRST: the list
  // pattern would otherwise swallow `/inventory/disposals/<id>/` and hand the
  // expanded row an array where it expects one record.
  [/^\/inventory\/disposals\/[^/]+\/?$/, () => inventoryFixtures.disposal_detail],
  [/^\/inventory\/disposals\/?$/, () => inventoryFixtures.disposals],
  [/^\/inventory\/disposal-options\/?$/, () => inventoryFixtures.disposal_options],
  // Phase ASSET-VISIBILITY-AND-CUSTODY-DASHBOARD.
  [/^\/inventory\/visibility-options\/?$/, () => inventoryFixtures.visibility_options],
  [/^\/inventory\/reports\/([a-z_]+)\/?$/, (m) => inventoryFixtures.reports[m[1]] || { rows: [] }],
  [/^\/inventory\/items\/[^/]+\/lifecycle-summary\/?$/,
    () => inventoryFixtures.lifecycle_summary],
  [/^\/inventory\/assignments\/mine\/?$/, () => inventoryFixtures.profile?.assigned || []],
  [/^\/workforce\/corrections\/queue-counts\/?$/,
    () => ({ manager_stage: 0, hr_stage: 0, mine_open: 0 })],
  [/^\/workforce\/corrections\/?$/, () => EMPTY_PAGE],

  // --- notifications ----------------------------------------------------------
  [/^\/notifications\/unread-count\/?$/, () => fixtures.notification_unread],
  [/^\/notifications\/preferences\/?$/,  () => fixtures.notification_prefs],
  [/^\/notifications\/?$/, (_m, config) => {
    const category = config?.params?.category;
    if (!category) return fixtures.notifications;
    const rows = (fixtures.notifications.results || fixtures.notifications)
      .filter((row) => row.category === category);
    return { ...fixtures.notifications, count: rows.length, results: rows };
  }],

  // --- reports ------------------------------------------------------------------
  [/^\/reports\/?$/, (_m, config) => (
    config?.params?.mine ? fixtures.reports_mine : fixtures.reports_all
  )],

  // --- user directory (ApplyLeave's approver <select>) --------------------------
  [/^\/users\/?$/, () => fixtures.users],
];

/**
 * A URL that nothing matches must FAIL LOUDLY.
 *
 * Returning `{}` would render an empty page, and an empty page has nothing to overflow —
 * so the probe would call it clean. That exact failure mode (a blank screen certified as
 * passing) is what the harness's character-count floor exists to catch, and a silently
 * permissive stub would reintroduce it one layer lower.
 */
const resolve = (url, config) => {
  const path = String(url).split('?')[0];
  for (const [pattern, handler] of ROUTES) {
    const match = pattern.exec(path);
    if (match) return handler(match, config);
  }
  const error = new Error(`[qa api-stub] no fixture for ${path}`);
  error.qaUnrouted = path;
  throw error;
};

const respond = (url, config) => Promise.resolve({
  data: resolve(url, config), status: 200, statusText: 'OK', headers: {}, config: config || {},
});

/* Writes are no-ops that echo success. The harness measures LAYOUT, and a mutation that
   really changed state would make a screen's appearance depend on capture order. */
const accept = (url, body) => Promise.resolve({
  data: body ?? {}, status: 200, statusText: 'OK', headers: {}, config: {},
});

const api = (config) => respond(config?.url ?? config, config);
api.get = (url, config) => respond(url, config);
api.post = (url, body) => accept(url, body);
api.put = (url, body) => accept(url, body);
api.patch = (url, body) => accept(url, body);
api.delete = () => accept();
api.request = (config) => respond(config?.url, config);
/* Services never add interceptors, but axios instances expose these and a missing
   property would throw at import time rather than at call time. */
api.interceptors = {
  request: { use: () => 0, eject: () => {} },
  response: { use: () => 0, eject: () => {} },
};
api.defaults = { baseURL: '/api/v1', headers: {} };

export default api;
