/* eslint-disable react-refresh/only-export-components */
/**
 * Visual QA harness for the minute module (Phase 46 item 1, rebuilt for Phase 47 item 1).
 *
 * WHAT CHANGED IN PHASE 47, and why it matters:
 *
 *  1. Fixtures are no longer hand-written. `fixtures.json` is generated by
 *     backend/minutes/tests/test_qa_fixture.py, which builds a real minute through the
 *     real API and dumps what the serializers actually return. The Phase 46 harness
 *     invented its chart payload (`monthly`, `decisions`, `actions`); the server sends
 *     `open_decisions` and `open_action_items`, so two of the dashboard's four charts
 *     screenshotted EMPTY and the capture certified a page nobody had really seen.
 *
 *  2. One screen per page load, selected with ?screen=NAME, instead of every component
 *     stacked in one column. Stacking forced a `maxWidth: 1180` wrapper, which meant the
 *     1920px capture was not a 1920px capture at all.
 *
 *  3. The page is mounted inside the app's own `.shell` / `.sidebar` / `.main` chrome, so
 *     the content area is the width it really is: 280px narrower on desktop, and full
 *     width at 1023px and below where the sidebar becomes an off-canvas drawer. Testing
 *     the page at the full viewport width would be a laxer test than production.
 *
 *  4. Findings are appended in document flow and mirrored onto `window.__QA__`, so the
 *     capture script can read them out of --dump-dom rather than off a screenshot.
 *
 * Usage: npm run qa:build && npm run qa:capture   (see package.json / qa/capture.sh)
 */
import React from 'react';
import { createRoot } from 'react-dom/client';
import { MemoryRouter, Route, Routes } from 'react-router-dom';
import { QueryClient, QueryClientProvider } from '@tanstack/react-query';

import '../src/index.css';
import fixtures from './fixtures.json';
/* Phase 49: the memo module shares `.memo-detail-grid` and `.memo-create-grid` with the
   minute module, so the Phase 48 clipping defect had to be tested here too rather than
   inferred from the shared selector. Generated by memos/tests/test_qa_fixture.py.
   Phase 100.1 moved it from ../qa-out/ to here: qa-out is gitignored capture output, so
   the build broke on any fresh checkout — see the note in that generator. */
import memoFixtures from './memo-fixtures.json';
/* Phase 50: the circular module. Generated by circulars/tests/test_qa_fixture.py -
   a reviewed, issued, broadcast circular with a partly-read audience and a mixed
   acknowledgement register, so every state in the panels renders. */
import circularFixtures from './circular-fixtures.json';
/* Phase 70: the inventory module. Generated by inventory/tests/test_qa_fixture.py -
   one asset walked through the entire lifecycle, so the timeline and every
   register have real content rather than an empty state. */
import inventoryFixtures from './inventory-fixtures.json';

import MinuteDashboard from '../src/pages/minute/MinuteDashboard';
import MinuteForm from '../src/pages/minute/MinuteForm';
import MinuteDetail from '../src/pages/minute/MinuteDetail';
import { ArchivedMinutes } from '../src/pages/minute/scopePages';

import AcknowledgementPanel from '../src/components/minute/AcknowledgementPanel';
import AttachmentPanel from '../src/components/minute/AttachmentPanel';
import MemberEditor from '../src/components/minute/MemberEditor';
/* Phase 203 - the workspace pages. Both are react-query pages fed by
   qa/api-stub.js, so they render from the same real fixture payloads the
   module screens use rather than a seeded cache. */
import CommandPalette from '../src/components/search/CommandPalette';
import AppSidebar from '../src/components/layout/AppSidebar';
import MobileTabBar from '../src/components/layout/MobileTabBar';
import CreateSheet from '../src/components/layout/CreateSheet';
import ProfileWorkspace from '../src/pages/ProfileWorkspace';
import DocumentsLauncher from '../src/pages/launchers/DocumentsLauncher';
import Home from '../src/pages/Home';
import WorkQueue from '../src/pages/WorkQueue';
import MemoDashboard from '../src/pages/memo/MemoDashboard';
import CircularDashboard from '../src/pages/circular/CircularDashboard';
import CircularDetail from '../src/pages/circular/CircularDetail';
import CircularForm from '../src/pages/circular/CircularForm';
import { BroadcastedCirculars } from '../src/pages/circular/scopePages';
import InventoryDashboard from '../src/pages/inventory/InventoryDashboard';
import InventoryList from '../src/pages/inventory/InventoryList';
import AssetRequests from '../src/pages/inventory/AssetRequests';
import MaintenanceTickets from '../src/pages/inventory/MaintenanceTickets';
import InventoryReports from '../src/pages/inventory/InventoryReports';
import AssetDisposals from '../src/pages/inventory/AssetDisposals';
import AssetVisibility from '../src/pages/inventory/AssetVisibility';
import MemoDetail from '../src/pages/memo/MemoDetail';
import CreateMemo from '../src/pages/memo/CreateMemo';
/* Phase 100.1 (Blockers 4, 5, 6): the three modules the Phase 100 audit could not
   measure. These pages talk to `services/api`, which qa/vite.qa.config.js aliases to
   api-stub.js — so they fetch their real payloads out of leave-fixtures.json, which
   backend/leaves/tests/test_qa_fixture.py generated from the real endpoints. */
import leaveFixtures from './leave-fixtures.json';
import LeaveDashboard from '../src/pages/leave/Dashboard';
import MyApplications from '../src/pages/leave/MyApplications';
import PendingApprovals from '../src/pages/leave/PendingApprovals';
import ApplyLeave from '../src/pages/leave/ApplyLeave';
import LeaveReviewModal from '../src/components/leave/LeaveReviewModal';
import NotificationsPage from '../src/pages/NotificationsPage';
import ReportsHub from '../src/pages/reports/ReportsHub';

const { archived, draft, taxonomy } = fixtures;
const ARCHIVED_ID = fixtures.archived_id;
const DRAFT_ID = fixtures.draft_id;

/*
 * staleTime Infinity and refetchOnMount false are REQUIRED, not tidiness: every page
 * below is fed by a pre-seeded cache entry, and with the default staleTime of 0 each
 * mounted query immediately refetches, hits no server, and the page renders its error
 * state. The first run of this harness screenshotted exactly that - "Request failed with
 * status code 404" where the dashboard should have been.
 */
const qc = new QueryClient({
  defaultOptions: {
    queries: {
      retry: false, staleTime: Infinity, gcTime: Infinity,
      refetchOnMount: false, refetchOnWindowFocus: false, refetchInterval: false,
    },
  },
});

/*
 * The dashboard counters come from a single-minute test database, so they are all 0-6 -
 * which tells the layout nothing. The SHAPE stays exactly as the server
 * sends it; only the magnitudes are raised, to the widest figure a tile will ever carry
 * (five digits) plus the longest hint. A tile that fits 1 and breaks at 12,840 is a bug
 * that only a large number finds.
 */
const inflate = (row, scale) => Object.fromEntries(Object.entries(row).map(
  ([key, value]) => [key, typeof value === 'number' ? value * scale : value]));

const DASHBOARD = inflate(fixtures.dashboard, 137);
const CHARTS = {
  by_status: (fixtures.charts.by_status || []).map((r) => inflate(r, 411)),
  by_type: [
    { label: 'DEPARTMENT', value: 4127 },
    { label: 'BRANCH', value: 3884 },
    { label: 'MANCOM', value: 2910 },
  ],
};

qc.setQueryData(['minutes', 'dashboard'], DASHBOARD);
qc.setQueryData(['minutes', 'dashboard', 'charts'], CHARTS);
qc.setQueryData(['minutes', 'taxonomy'], taxonomy);
qc.setQueryData(['minute', ARCHIVED_ID], archived);
qc.setQueryData(['minute', DRAFT_ID], draft);
qc.setQueryData(['minute', ARCHIVED_ID, 'audit-trail'], fixtures.audit_trail);
qc.setQueryData(['minutes', 'archived', '', ''], fixtures.archived_list);
qc.setQueryData(['minutes', 'all', '', ''], fixtures.list);

const MEMO_ID = memoFixtures.memo_id;
qc.setQueryData(['memo', MEMO_ID], memoFixtures.detail);

/*
 * Phase 100.1 Blockers 1 and 2 — an ACTIONABLE copy of the memo.
 *
 * The generated fixture is an ARCHIVED memo: every `can_*` flag is false and all four
 * workflow steps are `completed`, so MemoDetail renders no action buttons at all. That
 * is correct for the archive screenshot and useless for measuring a decision modal —
 * there is nothing to click. Blocker 2 asks whether Recommend / Support / Approve /
 * Reject can be completed at 390px, which cannot be answered against a memo where none
 * of them exist.
 *
 * Only the SERVER-CONTROLLED PERMISSION FLAGS are changed, never the layout-bearing
 * content: same subject, same body, same matrix, same four people. The step under test
 * is turned back to `active` and handed to the current user, which is exactly the state
 * the server sends when a memo is sitting with you.
 *
 * Rendered under a separate screen name so the archive capture keeps testing the
 * archive, and this one tests the decision path.
 */
const ACTING_STEP = 3;                                   // the supporter step
const ACTING_ASSIGNEE = memoFixtures.detail.workflow_steps
  .find((step) => step.sequence === ACTING_STEP)?.assignee;

/* `my_step` is a SERVER-COMPUTED field, not something MemoDetail derives from
   workflow_steps — `myTurn` reads `memo.my_step.is_my_turn` directly. On the archived
   fixture it is null, which is why flipping the step's own status was not enough to
   make Support and Reject appear on the first attempt. */
const ACTING_STEP_ROW = memoFixtures.detail.workflow_steps
  .find((step) => step.sequence === ACTING_STEP);

const ACTIONABLE_MEMO = {
  ...memoFixtures.detail,
  status: 'in_review',
  can_act: true,
  can_archive: true,
  can_withdraw: true,
  can_delete: true,
  my_step: {
    ...ACTING_STEP_ROW,
    status: 'active',
    is_my_turn: true,
    /* The supporter step does not require a comment; the reviewer step does. Left
       false so the modal's confirm button is reachable without typing, which is what
       the footer-position measurement needs. The remarks-required variant is covered
       by `memo-modal-remarks` below. */
    requires_comment: false,
  },
  workflow_steps: memoFixtures.detail.workflow_steps.map((step) => (
    step.sequence === ACTING_STEP
      ? { ...step, status: 'active', is_my_turn: true }
      : step.sequence > ACTING_STEP
        ? { ...step, status: 'pending' }
        : step
  )),
};
const ACTIONABLE_MEMO_ID = `${MEMO_ID}-actionable`;
qc.setQueryData(['memo', ACTIONABLE_MEMO_ID], ACTIONABLE_MEMO);
qc.setQueryData(['memos', 'dashboard-counts'], memoFixtures.dashboard);
qc.setQueryData(['memos', 'dashboard-charts'], memoFixtures.charts);
qc.setQueryData(['memos', 'dashboard-pending'], { items: [], total: 0 });

const CIRCULAR_ID = circularFixtures.circular_id;
qc.setQueryData(['circular', CIRCULAR_ID], circularFixtures.detail);
qc.setQueryData(['circulars', 'dashboard'], circularFixtures.dashboard);
qc.setQueryData(['circulars', 'taxonomy'], circularFixtures.taxonomy);
qc.setQueryData(['circulars', 'audiences'], circularFixtures.audiences);
qc.setQueryData(['circulars', 'broadcasted', '', '', ''],
                circularFixtures.broadcasted_list);
/* The merged register the detail page builds from two endpoints. Seeded already
   merged, because the harness has no server to do the merging against. */
qc.setQueryData(['circular', CIRCULAR_ID, 'registers'],
  (circularFixtures.recipients.recipients || []).map((row) => {
    const ack = (circularFixtures.acknowledgements.recipients || [])
      .find((a) => a.recipient_id === row.id);
    return {
      ...row,
      ack_state: ack?.state,
      ack_state_label: ack?.state_label,
      ack_responded_at: ack?.responded_at,
      ack_remarks: ack?.remarks,
      ack_is_late: ack?.is_late,
    };
  }));

/* Phase 70. Seeded from the generator's real payloads. The requests and
   maintenance endpoints are paginated, so the pages read `.results` - unwrapped
   here because the harness has no server to paginate against. */
qc.setQueryData(['inventory', 'dashboard'], inventoryFixtures.dashboard);
qc.setQueryData(['inventory', 'requests'],
                inventoryFixtures.requests.results || inventoryFixtures.requests);
qc.setQueryData(['inventory', 'maintenance'],
                inventoryFixtures.maintenance.results || inventoryFixtures.maintenance);
qc.setQueryData(['inventory', 'categories'], []);
qc.setQueryData(['inventory', 'report', 'by_department'],
                inventoryFixtures.reports.by_department);

/* NotificationsPage and ReportsHub ARE react-query pages, so seed them the way every
   other screen here is seeded. The leave pages are not and go through the api stub. */
qc.setQueryData(['notifications', ''],
                leaveFixtures.notifications.results || leaveFixtures.notifications);
qc.setQueryData(['notif-prefs'], leaveFixtures.notification_prefs);
qc.setQueryData(['notif-unread'], leaveFixtures.notification_unread?.unread ?? 0);
qc.setQueryData(['notif-recent'],
                (leaveFixtures.notifications.results || leaveFixtures.notifications).slice(0, 5));
qc.setQueryData(['reports', 'mine'],
                leaveFixtures.reports_mine.results || leaveFixtures.reports_mine);

const noop = () => {};

/* A panel rendered on its own still needs the page background it lives on. */
const Panel = ({ children }) => (
  <div className="page memo-page memo-detail">
    <div className="memo-detail-main">{children}</div>
  </div>
);

/*
 * The 13 screens Phase 47 item 1 names. `detail` is the one that carries eight of them
 * in situ; the focused entries capture the same panels alone, where a layout fault is
 * legible instead of buried 6000px down a scroll.
 */
const SCREENS = {
  /* --- Phase 203: Home and the Work Queue -------------------------------- */
  home: () => <Home />,
  /* Phase E. The launcher, and the contextual rail that replaces the 76-link
     sidebar - the harness mounts the real .sidebar chrome, so this captures
     both at once. */
  'documents-launcher': () => <DocumentsLauncher />,
  'memo-rail': () => <MemoDashboard />,
  /* Phase F. The bar is fixed-position, so it is rendered WITH a page beneath
     it - a bar on its own would not catch it covering content. */
  'mobile-home': () => (<><Home /><MobileTabBar onCreate={() => {}} onSearch={() => {}} /></>),
  'mobile-queue': () => (
    <><Routes><Route path="/queue" element={<WorkQueue />} /></Routes>
      <MobileTabBar onCreate={() => {}} onSearch={() => {}} /></>
  ),
  'mobile-profile': () => (<><ProfileWorkspace /><MobileTabBar onCreate={() => {}} onSearch={() => {}} /></>),
  'mobile-create': () => (
    <><Home /><CreateSheet open onClose={() => {}} />
      <MobileTabBar onCreate={() => {}} onSearch={() => {}} /></>
  ),
  /* Phase 204. Rendered open with a seeded query so the capture shows real
     grouped results rather than the idle prompt. */
  'command-palette': () => (
    <><Home /><CommandPalette open onClose={() => {}} initialQuery="budget" /></>
  ),
  'work-queue': () => (
    <Routes><Route path="/queue" element={<WorkQueue />} /></Routes>
  ),

  dashboard: () => <MinuteDashboard />,

  'create-minute': () => (
    <Routes><Route path="/minutes/create"
      element={<MinuteForm mode="create" />} /></Routes>
  ),
  'edit-minute': () => (
    <Routes><Route path="/minutes/:id/edit"
      element={<MinuteForm mode="edit" />} /></Routes>
  ),
  'minute-detail': () => (
    <Routes><Route path="/minutes/:id" element={<MinuteDetail />} /></Routes>
  ),
  'archive-view': () => <ArchivedMinutes />,

  /* Editable, because the add/remove controls only exist when it is not read-only -
     a read-only capture would show the panel and hide the controls under test. */
  'attachment-panel': () => (
    <Panel><AttachmentPanel attachments={archived.attachments} canEdit
      onUpload={noop} onDelete={noop} /></Panel>
  ),
  'member-register': () => (
    <Panel><MemberEditor
      rows={archived.participants.map((p) => ({
        user_id: p.user?.id, full_name: p.name, designation: p.designation,
        department: p.department_label, attendance: p.attendance,
      }))}
      onChange={noop} /></Panel>
  ),
  'acknowledgement-register': () => (
    <Panel><AcknowledgementPanel
      summary={archived.acknowledgement} deadline={archived.acknowledgement_deadline}
      participants={archived.participants} canAcknowledge canRemind
      onAcknowledge={noop} onRemind={noop} /></Panel>
  ),
  /* --- Phase 50: the circular module ------------------------------------- */
  'circular-dashboard': () => <CircularDashboard />,
  'circular-detail': () => (
    <Routes><Route path="/circulars/:id" element={<CircularDetail />} /></Routes>
  ),
  'circular-create': () => (
    <Routes><Route path="/circulars/create"
      element={<CircularForm mode="create" />} /></Routes>
  ),
  'circular-broadcasted': () => <BroadcastedCirculars />,

  /* --- Phase 70: the inventory module ------------------------------------ */
  'inventory-dashboard': () => <InventoryDashboard />,
  /* Phase D1. The register: header, summary, filter chips and the table. The
     add/edit panel is captured too, through the MODALS matrix in capture.sh -
     it clicks "Add asset" and probes the panel at the four phone widths. */
  'inventory-register': () => <InventoryList />,
  'inventory-requests': () => <AssetRequests />,
  'inventory-maintenance': () => <MaintenanceTickets />,
  'inventory-reports': () => (
    <Routes><Route path="/inventory/reports/:name"
      element={<InventoryReports />} /></Routes>
  ),
  /* Phase ASSET-LIFECYCLE-DISPOSAL. The default "Awaiting my decision" tab is
     fine here: the stub ignores query params, so every fixture row renders and
     the capture measures a populated page rather than an empty state. */
  'inventory-disposals': () => <AssetDisposals />,
  /* Phase ASSET-VISIBILITY-AND-CUSTODY-DASHBOARD. Two wide tables and a
     five-control filter row - the shape most likely to overflow a phone. */
  'inventory-visibility': () => <AssetVisibility />,

  /* --- Phase 49: the memo module, on the same shared page chrome ---------- */
  'memo-dashboard': () => <MemoDashboard />,
  'memo-detail': () => (
    <Routes><Route path="/memos/:id" element={<MemoDetail />} /></Routes>
  ),
  'memo-create': () => (
    <Routes><Route path="/memos/create" element={<CreateMemo />} /></Routes>
  ),

  /* --- Phase 100.1: the memo decision path, so its modals can be opened ---- */
  'memo-actionable': () => (
    <Routes><Route path="/memos/:id" element={<MemoDetail />} /></Routes>
  ),

  /* --- Phase 100.1: leave, notifications and reports ---------------------- */
  'leave-dashboard': () => <LeaveDashboard />,
  'leave-my-applications': () => <MyApplications />,
  'leave-pending': () => <PendingApprovals />,
  'leave-apply': () => <ApplyLeave />,
  /* The review drawer rendered directly rather than reached by a click: it is the
     screen that carries Approve and Reject, so it is the one Blocker 2 turns on, and
     mounting it directly makes the capture independent of the queue rendering first. */
  /* `canApprove` is REQUIRED, and the callback is `onDecided` (not `onDone`) — the
     first draft passed neither correctly and the drawer rendered without its
     Approve/Reject row, which is the single thing this screen exists to measure.
     The pending fixture is `status: 'pending'`, which is the other half of the
     condition the component checks. */
  'leave-review-drawer': () => (
    <LeaveReviewModal leaveId={leaveFixtures.pending_id} canApprove
      onClose={noop} onDecided={noop} />
  ),
  notifications: () => <NotificationsPage />,
  'reports-hub': () => <ReportsHub />,
};

const ROUTE_FOR = {
  'create-minute': '/minutes/create',
  'edit-minute': `/minutes/${DRAFT_ID}/edit`,
  'minute-detail': `/minutes/${ARCHIVED_ID}`,
  'memo-detail': `/memos/${MEMO_ID}`,
  'memo-actionable': `/memos/${ACTIONABLE_MEMO_ID}`,
  'memo-create': '/memos/create',
  'circular-detail': `/circulars/${CIRCULAR_ID}`,
  'circular-create': '/circulars/create',
  'inventory-register': '/inventory',
  'inventory-reports': '/inventory/reports/by_department',
  'inventory-disposals': '/inventory/disposals',
  'inventory-visibility': '/inventory/visibility',
  'leave-dashboard': '/leave',
  'leave-my-applications': '/leave/my-applications',
  'leave-pending': '/leave/pending',
  'leave-apply': '/leave/apply',
  home: '/',
  'documents-launcher': '/documents',
  'memo-rail': '/memos',
  'mobile-home': '/',
  'mobile-queue': '/queue',
  'mobile-profile': '/me',
  'mobile-create': '/',
  'command-palette': '/',
  'work-queue': '/queue',
  'leave-review-drawer': '/leave/pending',
  notifications: '/notifications',
  'reports-hub': '/reports',
};

/*
 * A render that throws leaves an empty #root, and an empty page has nothing to overflow -
 * so the probe reports it clean. That happened on the first Phase 47 capture. The boundary
 * turns a silent blank into a visible, screenshotted failure, and the character count in
 * the report line below turns it into one the capture script can fail on.
 */
class Boundary extends React.Component {
  constructor(props) { super(props); this.state = { error: null }; }
  static getDerivedStateFromError(error) { return { error }; }
  render() {
    if (!this.state.error) return this.props.children;
    return (
      <pre id="qa-render-error" style={{
        margin: 0, padding: 16, background: '#7f1d1d', color: '#fff',
        font: '12px/1.6 ui-monospace,monospace', whiteSpace: 'pre-wrap',
      }}>
        RENDER FAILED: {String(this.state.error?.stack || this.state.error)}
      </pre>
    );
  }
}

/** Screens that need the real navigation rendered rather than a dark rectangle. */
const REAL_RAIL = new Set(['documents-launcher', 'memo-rail']);

const params = new URLSearchParams(window.location.search);
const name = params.get('screen') || 'dashboard';
const Screen = SCREENS[name];

const Harness = () => {
  if (!Screen) {
    return <pre id="qa-unknown-screen">Unknown screen: {name}
      {'\n'}Known: {Object.keys(SCREENS).join(', ')}</pre>;
  }
  return (
    <Boundary>
    <QueryClientProvider client={qc}>
      <MemoryRouter initialEntries={[ROUTE_FOR[name] || '/minutes']}>
        {/* The app's real chrome. `.sidebar` is a flex sibling above 1023px and an
            off-canvas drawer at and below it, so the content area under test is the
            width it really is at every captured viewport.

            ONLY `height` is overridden, and it has to be: `.shell` is `calc(100vh - 72px)`
            with the page scrolling INSIDE `.main`, so a screenshot would capture one
            viewport of a six-thousand-pixel page. Every other property is left alone.
            An earlier draft also forced `overflow: visible` here and on `.main` so the
            whole page would lay out - and that manufactured eleven overflow findings out
            of nothing, because `.main`'s `overflow-x: hidden` is exactly what makes it a
            shrinkable flex item. Removing it stopped `.main` shrinking, so every wide
            register "overflowed". The lesson is in the report: do not relax the property
            under test in order to photograph it. */}
        {/* Phase 100.2: the sticky header, as a structural stand-in — same pattern as
            the `.sidebar` placeholder beside it, and for the same reason. It is not
            cosmetic. `.header` is what carries `padding-top: env(safe-area-inset-top)`,
            so it is what pushes `.page` clear of the notch. Without it the page began
            at y=0 and the device matrix reported every "Back" button as sitting under
            the Dynamic Island — 352 findings that production does not have, because in
            production a 72px header sits above them. Rendering the real <Header/> would
            drag in auth and notification queries; the class and the height are what the
            layout under test actually depends on. */}
        <header className="header" aria-hidden="true">
          <div className="hd-brand">NIF</div>
          <div className="hd-right" />
        </header>
        <div className="shell" style={{ height: 'auto' }}>
          {/* Phase E screens mount the real contextual rail; every other screen
              keeps the inert placeholder so its existing capture is unchanged. */}
          {REAL_RAIL.has(name)
            ? <AppSidebar open={false} onClose={() => {}} />
            : <nav className="sidebar" aria-hidden="true" />}
          <main className="main"><Screen /></main>
        </div>
      </MemoryRouter>
    </QueryClientProvider>
    </Boundary>
  );
};

createRoot(document.getElementById('root')).render(<Harness />);

/*
 * After paint, run the overflow probe and append its findings in document flow (not as a
 * fixed overlay, which would cover the very layout being screenshotted) and mirror them
 * onto window.__QA__ so --dump-dom carries them out. Two animation frames then a timeout:
 * the first frame commits the React tree, the timeout lets fonts settle, and font metrics
 * are what decide whether a nowrap pill fits.
 */
import { probeOverflow } from './overflow-probe';
/* Phase 100: touch-target size and off-viewport actions — the two mobile faults the
   overflow probe is blind to. Returns [] above 1023px so desktop stays unchanged. */
import { probeMobile, probeModalFooters, probeBoxLabels } from './mobile-probe';

/**
 * Phase 100.1 Blockers 1 and 2: open a modal before probing.
 *
 * A modal that is never opened is a modal that is never measured — which is how 13
 * modals reached the Phase 100 report with "audited by reading the CSS" against them.
 * `?click=<text>` finds the control whose visible text or aria-label starts with that
 * text and clicks it, so the capture script can drive a real workflow:
 *
 *   frame.html?screen=memo-detail&w=390&click=Reject
 *
 * Returns whether the click landed, so a fixture that stopped rendering the button
 * fails the capture instead of quietly probing the un-opened page underneath.
 */
const clickByLabel = (label) => {
  const wanted = label.trim().toLowerCase();
  const controls = [...document.querySelectorAll('button, a[href], [role=button]')];
  const hit = controls.find((el) => {
    const text = (el.textContent || '').trim().toLowerCase();
    const aria = (el.getAttribute('aria-label') || '').trim().toLowerCase();
    return !el.disabled && (text.startsWith(wanted) || aria.startsWith(wanted));
  });
  hit?.click();
  return Boolean(hit);
};

const report = () => {
  const findings = probeOverflow()
    .concat(probeMobile(window.innerWidth))
    /* Called separately, NOT from inside probeMobile: that one returns early above
       1023px, and a modal footer that unpins is a defect at every width — the sticky
       rule it checks is not inside a media query. */
    .concat(probeModalFooters(window.innerWidth))
    .concat(probeBoxLabels());
  // How much the page actually rendered. Reported on EVERY line, clean or not, because
  // "no findings" from an empty page is the failure this exists to make impossible.
  const chars = (document.getElementById('root')?.textContent || '').trim().length;
  const crashed = Boolean(document.getElementById('qa-render-error'));
  if (wanted && clickResult !== 'clicked') {
    findings.push({ kind: 'click-target-missing', label: wanted });
  }
  window.__QA__ = { screen: name, width: window.innerWidth, findings, chars, crashed,
                    click: clickResult };
  const box = document.createElement('pre');
  box.id = 'overflow-report';
  box.dataset.screen = name;
  box.dataset.width = String(window.innerWidth);
  box.dataset.count = String(findings.length);
  box.dataset.chars = String(chars);
  box.style.cssText = 'margin:0;padding:10px 14px;background:#111827;'
    + `color:${findings.length || crashed ? '#fca5a5' : '#6ee7b7'};`
    + 'font:11px/1.5 ui-monospace,monospace;white-space:pre-wrap';
  box.textContent = `[${name} @ ${window.innerWidth}px, ${chars} chars]`
    + (wanted ? ` [click "${wanted}": ${clickResult}]` : '') + ' '
    + (crashed ? 'RENDER FAILED — see #qa-render-error\n' : '')
    + (findings.length
      ? `${findings.length} overflow finding(s):\n`
        + findings.map((f) => JSON.stringify(f)).join('\n')
      : 'NO OVERFLOW FINDINGS');
  document.body.appendChild(box);
  document.documentElement.dataset.qaReady = '1';
};

const wanted = params.get('click');
let clickResult = null;

/* Two frames commit the tree, then the click, then a further settle before probing:
   a modal mounts through a portal and its sticky footer only takes its final position
   after layout, which is the very thing being measured. */
requestAnimationFrame(() => requestAnimationFrame(() => setTimeout(() => {
  if (wanted) clickResult = clickByLabel(wanted) ? 'clicked' : 'NOT FOUND';
  setTimeout(report, wanted ? 600 : 0);
}, 500)));
