# Generated by Django 5.2.16 on 2026-08-03 09:45

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BiometricDevice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text="Human-friendly name, e.g. 'Main Gate'.", max_length=100, unique=True)),
                ('label', models.CharField(help_text="Must match the collector's device label (MORX_DEVICE_NAME, or the device IP if unset).", max_length=100, unique=True)),
                ('host', models.CharField(blank=True, default='', help_text='LAN address, informational only.', max_length=255)),
                ('port', models.PositiveIntegerField(default=4370)),
                ('location', models.CharField(blank=True, default='', max_length=255)),
                ('device_timezone', models.CharField(default='Asia/Kathmandu', max_length=64)),
                ('is_active', models.BooleanField(default=True)),
                ('api_key_prefix', models.CharField(blank=True, db_index=True, default='', max_length=32)),
                ('api_key_hash', models.CharField(blank=True, default='', max_length=64)),
                ('api_key_set_at', models.DateTimeField(blank=True, null=True)),
                ('connection_status', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline'), ('unknown', 'Unknown')], default='unknown', max_length=10)),
                ('last_seen_at', models.DateTimeField(blank=True, help_text='Last authenticated request from this device.', null=True)),
                ('last_sync_at', models.DateTimeField(blank=True, help_text='Last successful punch ingest.', null=True)),
                ('last_punch_at', models.DateTimeField(blank=True, help_text='Newest punch timestamp ingested from this device.', null=True)),
                ('clock_drift_seconds', models.IntegerField(blank=True, help_text='Device clock minus server clock, in seconds, at last sync.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='biometric_devices_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Biometric Device',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BiometricEmployee',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('device_user_id', models.CharField(max_length=64)),
                ('device_name', models.CharField(blank=True, default='', max_length=150)),
                ('privilege', models.PositiveSmallIntegerField(default=0)),
                ('card', models.BigIntegerField(default=0)),
                ('group_id', models.CharField(blank=True, default='', max_length=32)),
                ('is_active', models.BooleanField(default=True)),
                ('first_seen_at', models.DateTimeField(auto_now_add=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('mapped_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='biometric.biometricdevice')),
                ('mapped_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='biometric_mappings_made', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='biometric_identities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Biometric Employee Mapping',
                'ordering': ['device', 'device_user_id'],
            },
        ),
        migrations.CreateModel(
            name='AttendancePunch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('employee_device_id', models.CharField(max_length=64)),
                ('employee_name', models.CharField(blank=True, default='', help_text='Name as enrolled on the device at punch time.', max_length=150)),
                ('timestamp', models.DateTimeField()),
                ('local_date', models.DateField()),
                ('punch', models.PositiveSmallIntegerField(help_text='Device punch code: 0 in, 1 out, 2/3 break, 4/5 overtime.')),
                ('punch_label', models.CharField(max_length=20)),
                ('verify_status', models.PositiveSmallIntegerField(default=0, help_text="Device verify mode (the collector's `status` field): fingerprint, card, password.")),
                ('source', models.CharField(choices=[('HISTORY', 'History (backlog pull)'), ('LIVE', 'Live (streamed)'), ('IMPORT', 'Manual import')], default='LIVE', max_length=10)),
                ('raw', models.JSONField(blank=True, default=dict, help_text='Original payload, for forensics on odd firmware.')),
                ('received_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('is_processed', models.BooleanField(default=False)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='biometric_punches', to=settings.AUTH_USER_MODEL)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='punches', to='biometric.biometricdevice')),
                ('biometric_employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='punches', to='biometric.biometricemployee')),
            ],
            options={
                'verbose_name': 'Attendance Punch',
                'verbose_name_plural': 'Attendance Punches',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='DeviceSyncLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sync_type', models.CharField(choices=[('history', 'History backlog'), ('live', 'Live punch'), ('roster', 'Employee roster'), ('import', 'Manual import')], max_length=10)),
                ('status', models.CharField(choices=[('started', 'Started'), ('success', 'Success'), ('partial', 'Partial'), ('failed', 'Failed')], default='started', max_length=10)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('records_received', models.PositiveIntegerField(default=0)),
                ('records_created', models.PositiveIntegerField(default=0)),
                ('records_duplicate', models.PositiveIntegerField(default=0)),
                ('records_unmapped', models.PositiveIntegerField(default=0)),
                ('records_invalid', models.PositiveIntegerField(default=0)),
                ('error', models.TextField(blank=True, default='')),
                ('client_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_logs', to='biometric.biometricdevice')),
            ],
            options={
                'verbose_name': 'Device Sync Log',
                'ordering': ['-started_at'],
            },
        ),
        migrations.AddIndex(
            model_name='biometricemployee',
            index=models.Index(fields=['device', 'is_active'], name='idx_bioemp_dev_active'),
        ),
        migrations.AddConstraint(
            model_name='biometricemployee',
            constraint=models.UniqueConstraint(fields=('device', 'device_user_id'), name='uniq_biometric_device_user'),
        ),
        migrations.AddConstraint(
            model_name='biometricemployee',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True), ('user__isnull', False)), fields=('device', 'user'), name='uniq_biometric_active_user'),
        ),
        migrations.AddIndex(
            model_name='attendancepunch',
            index=models.Index(fields=['user', 'local_date'], name='idx_punch_user_date'),
        ),
        migrations.AddIndex(
            model_name='attendancepunch',
            index=models.Index(fields=['device', 'local_date'], name='idx_punch_dev_date'),
        ),
        migrations.AddIndex(
            model_name='attendancepunch',
            index=models.Index(fields=['local_date'], name='idx_punch_date'),
        ),
        migrations.AddIndex(
            model_name='attendancepunch',
            index=models.Index(condition=models.Q(('is_processed', False)), fields=['local_date'], name='idx_punch_unprocessed'),
        ),
        migrations.AddConstraint(
            model_name='attendancepunch',
            constraint=models.UniqueConstraint(fields=('device', 'employee_device_id', 'timestamp', 'punch'), name='uniq_biometric_punch'),
        ),
        migrations.AddIndex(
            model_name='devicesynclog',
            index=models.Index(fields=['device', '-started_at'], name='idx_synclog_dev_start'),
        ),
        migrations.AddIndex(
            model_name='devicesynclog',
            index=models.Index(fields=['status', '-started_at'], name='idx_synclog_status'),
        ),
    ]
