# Generated by Django 5.2.16 on 2026-08-03 10:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biometric', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='biometricemployee',
            name='uniq_biometric_device_user',
        ),
        migrations.AddField(
            model_name='biometricemployee',
            name='effective_from',
            field=models.DateField(blank=True, help_text='Punches on or after this date belong to this mapping. Bounds backfill.', null=True),
        ),
        migrations.AddField(
            model_name='biometricemployee',
            name='effective_until',
            field=models.DateField(blank=True, help_text='Set when the mapping is retired, so a later occupant of the same device ID cannot claim earlier punches.', null=True),
        ),
        migrations.AddField(
            model_name='biometricemployee',
            name='superseded_by',
            field=models.ForeignKey(blank=True, help_text='The mapping that replaced this one when the device ID was reassigned.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supersedes', to='biometric.biometricemployee'),
        ),
        migrations.AddConstraint(
            model_name='biometricemployee',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('device', 'device_user_id'), name='uniq_biometric_active_device_user'),
        ),
    ]
