# Generated by Django 5.2.16 on 2026-08-03 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biometric', '0002_mapping_validity'),
    ]

    operations = [
        migrations.AddField(
            model_name='biometricdevice',
            name='failed_batches',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='biometricdevice',
            name='pending_punches',
            field=models.PositiveIntegerField(default=0, help_text="Punches sitting unsent in the collector's spool at last contact."),
        ),
        migrations.AddField(
            model_name='biometricdevice',
            name='successful_batches',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='devicesynclog',
            name='queue_depth',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
