# Generated by Django 6.0.6 on 2026-08-06 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biometric', '0003_device_sync_metrics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biometricdevice',
            name='host',
            field=models.CharField(blank=True, default='', help_text="The terminal's LAN address. `device_sync` connects to it, so it must be reachable from the server.", max_length=255),
        ),
        migrations.AlterField(
            model_name='biometricdevice',
            name='label',
            field=models.CharField(help_text="Short handle, e.g. 'main-gate'. Used by `device_sync --device`, and must match the device label on any pushed ingest payload.", max_length=100, unique=True),
        ),
    ]
