# Generated by Django 6.0.6 on 2026-08-06 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biometric', '0004_device_help_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='biometricdevice',
            name='serial_number',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Device serial number (device menu: Info > Device). Required for PUSH/ADMS terminals — it is how they identify themselves.', max_length=64),
        ),
    ]
