# Generated by Django 5.2.16 on 2026-10-04 12:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biometric', '0007_phase_a_organization_required'),
        ('tenancy', '0005_phase_s3_media_path_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='biometricdevice',
            constraint=models.UniqueConstraint(condition=models.Q(('serial_number', ''), _negated=True), fields=('serial_number',), name='uniq_biometric_device_serial_global'),
        ),
    ]
