# Generated by Django 5.2.17 on 2026-10-04 14:51

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biometric', '0012_phase_c_organization_required'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='biometricemployee',
            managers=[
                ('all_tenants', django.db.models.manager.Manager()),
            ],
        ),
    ]
