# Generated by Django 5.2.17 on 2026-10-04 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biometric', '0013_phase_s5_user_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='biometricemployee',
            managers=[
            ],
        ),
    ]
