# Generated by Django 5.2.17 on 2026-10-07 06:24

import django.db.models.deletion
from django.conf import settings
from django.conf import settings as django_settings
from django.db import migrations, models


def keep_existing_cadence(apps, schema_editor):
    """Existing terminals keep the schedule they already had.

    Until now one crontab line ran `device_sync` every 5 minutes, using the
    deployment-wide BIOMETRIC_DEVICE_COMM_KEY. The scheduler that replaces it
    reads each device's own interval and key, so an existing device with an
    address gets 5 minutes and the deployment's key -- the same cadence and
    the same handshake as the morning before this migration. A device with
    no address was never pulled (it pushes), so it is set to manual.
    """
    Device = apps.get_model("biometric", "BiometricDevice")
    manager = Device._base_manager
    try:
        key = int(getattr(django_settings, "BIOMETRIC_DEVICE_COMM_KEY", 0) or 0)
    except (TypeError, ValueError):
        key = 0
    manager.exclude(host="").update(sync_interval_minutes=5, comm_key=key)
    manager.filter(host="").update(sync_interval_minutes=0)


class Migration(migrations.Migration):

    dependencies = [
        ('biometric', '0014_phase_s5_biometric_managers'),
        ('tenancy', '0020_customer_success'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='biometricdevice',
            name='comm_key',
            field=models.PositiveIntegerField(db_default=0, default=0),
        ),
        migrations.AddField(
            model_name='biometricdevice',
            name='device_info',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='biometricdevice',
            name='device_info_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='biometricdevice',
            name='device_type',
            field=models.CharField(choices=[('zkteco', 'ZKTeco'), ('zk_compatible', 'ZK-compatible (eSSL, Realtime, Identix)')], db_default='zkteco', default='zkteco', max_length=20),
        ),
        migrations.AddField(
            model_name='biometricdevice',
            name='hardware_serial',
            field=models.CharField(blank=True, db_default='', default='', help_text='Serial reported by the terminal on first contact. A pull from a terminal reporting a different serial is refused.', max_length=64),
        ),
        migrations.AddField(
            model_name='biometricdevice',
            name='last_sync_attempt_at',
            field=models.DateTimeField(blank=True, help_text='Last time a pull was attempted, successful or not. Drives the schedule.', null=True),
        ),
        migrations.AddField(
            model_name='biometricdevice',
            name='last_sync_error',
            field=models.TextField(blank=True, db_default='', default=''),
        ),
        migrations.AddField(
            model_name='biometricdevice',
            name='last_sync_imported',
            field=models.PositiveIntegerField(db_default=0, default=0, help_text='New punches stored by the last pull.'),
        ),
        migrations.AddField(
            model_name='biometricdevice',
            name='last_sync_status',
            field=models.CharField(blank=True, db_default='', default='', max_length=10),
        ),
        migrations.AddField(
            model_name='biometricdevice',
            name='sync_interval_minutes',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Manual sync only'), (5, 'Every 5 minutes'), (15, 'Every 15 minutes'), (30, 'Every 30 minutes')], db_default=15, default=15, help_text='How often the server pulls this terminal. 0 = manual only.'),
        ),
        migrations.AddField(
            model_name='devicesynclog',
            name='trigger',
            field=models.CharField(blank=True, choices=[('auto', 'Scheduled'), ('manual', 'Manual (Sync now)'), ('test', 'Connection test')], db_default='', default='', max_length=10),
        ),
        migrations.AddField(
            model_name='devicesynclog',
            name='triggered_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='devicesynclog',
            name='status',
            field=models.CharField(choices=[('started', 'Started'), ('success', 'Success'), ('partial', 'Partial'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='started', max_length=10),
        ),
        migrations.AlterField(
            model_name='devicesynclog',
            name='sync_type',
            field=models.CharField(choices=[('history', 'History backlog'), ('live', 'Live punch'), ('roster', 'Employee roster'), ('import', 'Manual import'), ('pull', 'Device pull'), ('test', 'Connection test')], max_length=10),
        ),
        migrations.AddConstraint(
            model_name='biometricdevice',
            constraint=models.UniqueConstraint(condition=models.Q(('hardware_serial', ''), _negated=True), fields=('hardware_serial',), name='uniq_biometric_device_hw_serial_global'),
        ),
        migrations.RunPython(keep_existing_cadence, migrations.RunPython.noop),
    ]
