# Generated by Django 5.2.16 on 2026-08-31 07:16

import django.db.models.deletion
import tasks.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0017_merge_20260806_1728'),
        ('tasks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='progress_is_auto',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='taskattachment',
            name='is_removed',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='taskattachment',
            name='link_url',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='taskattachment',
            name='removed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='taskattachment',
            name='removed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_attachments_removed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='taskattachment',
            name='removed_by_name',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='taskcomment',
            name='edited_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='taskcomment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='tasks.taskcomment'),
        ),
        migrations.AlterField(
            model_name='taskattachment',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=tasks.models.task_attachment_path),
        ),
        migrations.AlterField(
            model_name='taskauditlog',
            name='action',
            field=models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('assigned', 'Assigned'), ('assignees_changed', 'Assignees changed'), ('accepted', 'Accepted'), ('clarification_requested', 'Clarification requested'), ('started', 'Work started'), ('progress_updated', 'Progress updated'), ('checklist_updated', 'Checklist updated'), ('evidence_uploaded', 'Evidence uploaded'), ('commented', 'Comment added'), ('comment_edited', 'Comment edited'), ('attachment_added', 'Attachment added'), ('attachment_removed', 'Attachment removed'), ('link_added', 'Link added'), ('evidence_flagged', 'Evidence flag changed'), ('template_saved', 'Saved as template'), ('template_applied', 'Created from template'), ('submitted_for_review', 'Submitted for review'), ('review_approved', 'Review approved'), ('rework_requested', 'Rework requested'), ('closed', 'Closed'), ('blocked', 'Blocked'), ('unblocked', 'Unblocked'), ('cancelled', 'Cancelled'), ('deleted', 'Deleted')], max_length=32),
        ),
        migrations.CreateModel(
            name='TaskAttachmentDownload',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_name', models.CharField(blank=True, default='', max_length=150)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('downloaded_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('attachment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='downloads', to='tasks.taskattachment')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_attachment_downloads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'task attachment download',
                'ordering': ['-downloaded_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskChecklistGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=150)),
                ('position', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_groups', to='tasks.task')),
            ],
            options={
                'ordering': ['position', 'created_at'],
            },
        ),
        migrations.AddField(
            model_name='taskchecklistitem',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='tasks.taskchecklistgroup'),
        ),
        migrations.CreateModel(
            name='TaskTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, default='')),
                ('title_template', models.CharField(blank=True, default='', help_text='Default title for tasks raised from this template. Falls back to the template name.', max_length=255)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=10)),
                ('default_due_in_days', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('department_name', models.CharField(blank=True, default='', max_length=150)),
                ('created_by_name', models.CharField(blank=True, default='', max_length=150)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('usage_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_templates_created', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_templates', to='leaves.department')),
            ],
            options={
                'ordering': ['-usage_count', 'name'],
            },
        ),
        migrations.AddField(
            model_name='task',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks_created', to='tasks.tasktemplate'),
        ),
        migrations.CreateModel(
            name='TaskTemplateGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=150)),
                ('position', models.PositiveIntegerField(default=0)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='tasks.tasktemplate')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='TaskTemplateItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=255)),
                ('position', models.PositiveIntegerField(default=0)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='tasks.tasktemplategroup')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='tasks.tasktemplate')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='TaskCommentMention',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_name', models.CharField(blank=True, default='', max_length=150)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentions', to='tasks.taskcomment')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_mentions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user_name'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('comment', 'user'), name='task_comment_mention_unique')],
            },
        ),
        migrations.AddConstraint(
            model_name='tasktemplate',
            constraint=models.UniqueConstraint(fields=('name',), name='task_template_name_unique'),
        ),
    ]
