# Generated by Django 5.2.16 on 2026-08-31 08:41

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0017_merge_20260806_1728'),
        ('tasks', '0002_task_progress_is_auto_taskattachment_is_removed_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='archived_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.CreateModel(
            name='TaskGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('department_name', models.CharField(blank=True, default='', max_length=150)),
                ('created_by_name', models.CharField(blank=True, default='', max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_groups_created', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_groups', to='leaves.department')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='groups_created', to='tasks.tasktemplate')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='task',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='tasks.taskgroup'),
        ),
        migrations.CreateModel(
            name='TaskReminderLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('due_7', 'Due in 7 days'), ('due_3', 'Due in 3 days'), ('due_1', 'Due tomorrow'), ('due_today', 'Due today'), ('overdue', 'Overdue'), ('review_pending', 'Review pending'), ('escalated_supervisor', 'Escalated to supervisor'), ('escalated_hr', 'Escalated to HR'), ('escalated_management', 'Escalated to management')], db_index=True, max_length=32)),
                ('sent_on', models.DateField(db_index=True)),
                ('recipients', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='tasks.task')),
            ],
            options={
                'ordering': ['-sent_on', 'kind'],
                'indexes': [models.Index(fields=['kind', 'sent_on'], name='task_reminder_kind_idx')],
                'constraints': [models.UniqueConstraint(fields=('task', 'kind', 'sent_on'), name='task_reminder_once_per_day')],
            },
        ),
    ]
