# Generated by Django 5.2.16 on 2026-08-31 09:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_task_archived_at_taskgroup_task_group_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeTaskEvidenceSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('employee_name', models.CharField(blank=True, default='', max_length=150)),
                ('department_name', models.CharField(blank=True, default='', max_length=150)),
                ('snapshot_date', models.DateField(db_index=True)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('tasks_assigned', models.PositiveIntegerField(default=0)),
                ('tasks_completed', models.PositiveIntegerField(default=0)),
                ('tasks_open', models.PositiveIntegerField(default=0)),
                ('tasks_overdue', models.PositiveIntegerField(default=0)),
                ('completed_with_due_date', models.PositiveIntegerField(default=0)),
                ('completed_on_time', models.PositiveIntegerField(default=0)),
                ('completion_percent', models.PositiveSmallIntegerField(default=0)),
                ('on_time_percent', models.PositiveSmallIntegerField(default=0)),
                ('average_completion_days', models.DecimalField(blank=True, decimal_places=1, help_text='Null means nothing completed in the window — not zero days.', max_digits=7, null=True)),
                ('reviews_performed', models.PositiveIntegerField(default=0)),
                ('checklist_items_total', models.PositiveIntegerField(default=0)),
                ('checklist_items_completed', models.PositiveIntegerField(default=0)),
                ('evidence_files_submitted', models.PositiveIntegerField(default=0)),
                ('comments_posted', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_evidence_snapshots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'employee task evidence snapshot',
                'ordering': ['-snapshot_date', 'employee_name'],
                'indexes': [models.Index(fields=['snapshot_date', 'employee'], name='task_evidence_date_idx')],
                'constraints': [models.UniqueConstraint(fields=('employee', 'snapshot_date'), name='task_evidence_one_per_day')],
            },
        ),
    ]
