# Generated by Django 5.2.16 on 2026-08-31 09:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_employeetaskevidencesnapshot'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='employeetaskevidencesnapshot',
            name='task_evidence_one_per_day',
        ),
        migrations.AddField(
            model_name='employeetaskevidencesnapshot',
            name='period_type',
            field=models.CharField(choices=[('daily', 'Daily'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('annual', 'Annual')], db_index=True, default='daily', max_length=12),
        ),
        migrations.AddIndex(
            model_name='employeetaskevidencesnapshot',
            index=models.Index(fields=['period_type', 'snapshot_date'], name='task_evidence_period_idx'),
        ),
        migrations.AddConstraint(
            model_name='employeetaskevidencesnapshot',
            constraint=models.UniqueConstraint(fields=('employee', 'period_type', 'snapshot_date'), name='task_evidence_one_per_period'),
        ),
    ]
