# Generated by Django 5.2.16 on 2026-09-16 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_remove_employeetaskevidencesnapshot_task_evidence_one_per_day_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='task_type',
            field=models.CharField(choices=[('personal', 'Personal Task'), ('department', 'Department Task'), ('assigned', 'Assigned Task')], db_index=True, default='assigned', max_length=12),
        ),
    ]
