# Generated by Django 5.2.16 on 2026-09-16 07:39

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_task_task_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskauditlog',
            name='action',
            field=models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('assigned', 'Assigned'), ('assignees_changed', 'Assignees changed'), ('accepted', 'Accepted'), ('clarification_requested', 'Clarification requested'), ('started', 'Work started'), ('progress_updated', 'Progress updated'), ('checklist_updated', 'Checklist updated'), ('evidence_uploaded', 'Evidence uploaded'), ('commented', 'Comment added'), ('comment_edited', 'Comment edited'), ('attachment_added', 'Attachment added'), ('attachment_removed', 'Attachment removed'), ('link_added', 'Link added'), ('evidence_flagged', 'Evidence flag changed'), ('template_saved', 'Saved as template'), ('template_applied', 'Created from template'), ('dependency_added', 'Dependency added'), ('dependency_removed', 'Dependency removed'), ('submitted_for_review', 'Submitted for review'), ('review_approved', 'Review approved'), ('rework_requested', 'Rework requested'), ('closed', 'Closed'), ('blocked', 'Blocked'), ('unblocked', 'Unblocked'), ('cancelled', 'Cancelled'), ('deleted', 'Deleted')], max_length=32),
        ),
        migrations.CreateModel(
            name='TaskDependency',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('blocked_by', 'Blocked by'), ('depends_on', 'Depends on')], default='blocked_by', max_length=12)),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('created_by_name', models.CharField(blank=True, default='', max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_dependencies_added', to=settings.AUTH_USER_MODEL)),
                ('depends_on', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependents', to='tasks.task')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependencies', to='tasks.task')),
            ],
            options={
                'verbose_name': 'task dependency',
                'verbose_name_plural': 'task dependencies',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['depends_on'], name='task_dep_target_idx')],
                'constraints': [models.UniqueConstraint(fields=('task', 'depends_on'), name='task_dependency_unique'), models.CheckConstraint(condition=models.Q(('task', models.F('depends_on')), _negated=True), name='task_dependency_not_self')],
            },
        ),
    ]
