# Generated by Django 5.2.16 on 2026-09-16 10:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0021_leave_board_action_date_leave_board_reviewer'),
        ('tasks', '0007_alter_taskauditlog_action_taskdependency'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentGoal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('department_name', models.CharField(blank=True, default='', max_length=150)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('period', models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('annual', 'Annual')], db_index=True, default='quarterly', max_length=10)),
                ('starts_on', models.DateField(db_index=True)),
                ('ends_on', models.DateField(db_index=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('achieved', 'Achieved'), ('missed', 'Missed'), ('cancelled', 'Cancelled')], db_index=True, default='active', max_length=10)),
                ('created_by_name', models.CharField(blank=True, default='', max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='department_goals_created', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_goals', to='leaves.department')),
            ],
            options={
                'verbose_name': 'department goal',
                'verbose_name_plural': 'department goals',
                'ordering': ['-starts_on', 'title'],
            },
        ),
        migrations.AddField(
            model_name='task',
            name='goal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='tasks.departmentgoal'),
        ),
        migrations.AddIndex(
            model_name='departmentgoal',
            index=models.Index(fields=['department', 'status'], name='goal_dept_status_idx'),
        ),
        migrations.AddIndex(
            model_name='departmentgoal',
            index=models.Index(fields=['starts_on', 'ends_on'], name='goal_window_idx'),
        ),
        migrations.AddConstraint(
            model_name='departmentgoal',
            constraint=models.CheckConstraint(condition=models.Q(('ends_on__gte', models.F('starts_on'))), name='goal_window_not_backwards'),
        ),
    ]
