# Generated by Django 5.2.16 on 2026-09-25 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_departmentgoal_task_goal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskassignee',
            name='progress_percent',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='taskassignee',
            name='progress_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
