# Generated by Django 5.2.16 on 2026-10-01 07:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0009_taskassignee_progress_percent_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='description_format',
            field=models.CharField(choices=[('text', 'Plain text'), ('html', 'Rich text')], default='text', max_length=4),
        ),
        migrations.AlterField(
            model_name='taskauditlog',
            name='action',
            field=models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('assigned', 'Assigned'), ('assignees_changed', 'Assignees changed'), ('accepted', 'Accepted'), ('clarification_requested', 'Clarification requested'), ('started', 'Work started'), ('progress_updated', 'Progress updated'), ('checklist_updated', 'Checklist updated'), ('evidence_uploaded', 'Evidence uploaded'), ('commented', 'Comment added'), ('comment_edited', 'Comment edited'), ('attachment_added', 'Attachment added'), ('attachment_removed', 'Attachment removed'), ('link_added', 'Link added'), ('evidence_flagged', 'Evidence flag changed'), ('template_saved', 'Saved as template'), ('template_applied', 'Created from template'), ('dependency_added', 'Dependency added'), ('dependency_removed', 'Dependency removed'), ('subtask_added', 'Subtask added'), ('subtask_assigned', 'Subtask assigned'), ('subtask_completed', 'Subtask completed'), ('subtask_removed', 'Subtask removed'), ('submitted_for_review', 'Submitted for review'), ('review_approved', 'Review approved'), ('rework_requested', 'Rework requested'), ('closed', 'Closed'), ('blocked', 'Blocked'), ('unblocked', 'Unblocked'), ('cancelled', 'Cancelled'), ('deleted', 'Deleted')], max_length=32),
        ),
        migrations.CreateModel(
            name='TaskSubtask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('position', models.PositiveIntegerField(default=0)),
                ('assignee_name', models.CharField(blank=True, default='', max_length=150)),
                ('due_date', models.DateField(blank=True, db_index=True, null=True)),
                ('is_done', models.BooleanField(default=False)),
                ('done_by_name', models.CharField(blank=True, default='', max_length=150)),
                ('done_at', models.DateTimeField(blank=True, null=True)),
                ('created_by_name', models.CharField(blank=True, default='', max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subtasks', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('done_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtasks', to='tasks.task')),
            ],
            options={
                'ordering': ['position', 'created_at'],
            },
        ),
        migrations.AddField(
            model_name='taskattachment',
            name='subtask',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='tasks.tasksubtask'),
        ),
        migrations.AddField(
            model_name='taskcomment',
            name='subtask',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='tasks.tasksubtask'),
        ),
        migrations.AddIndex(
            model_name='tasksubtask',
            index=models.Index(fields=['task', 'is_done'], name='subtask_task_done_idx'),
        ),
        migrations.AddIndex(
            model_name='tasksubtask',
            index=models.Index(fields=['is_done', 'due_date'], name='subtask_due_idx'),
        ),
    ]
