# Generated by Django 5.2.16 on 2026-10-01 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0010_task_subtasks_and_rich_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskreminderlog',
            name='kind',
            field=models.CharField(choices=[('due_7', 'Due in 7 days'), ('due_3', 'Due in 3 days'), ('due_1', 'Due tomorrow'), ('due_today', 'Due today'), ('overdue', 'Overdue'), ('review_pending', 'Review pending'), ('subtask_overdue', 'Subtask overdue'), ('escalated_supervisor', 'Escalated to supervisor'), ('escalated_hr', 'Escalated to HR'), ('escalated_management', 'Escalated to management')], db_index=True, max_length=32),
        ),
    ]
