# Generated by Django 5.2.16 on 2026-10-04 12:33

import tasks.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0013_phase_a_organization_required'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskattachment',
            name='file',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to=tasks.models.task_attachment_path),
        ),
    ]
