# Generated by Django 6.0.6 on 2026-07-09 09:19

import memos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memos', '0004_seed_default_templates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memo',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to=memos.models.memo_attachment_path),
        ),
    ]
