# Generated by Django 5.2.16 on 2026-08-12 06:22

import django.db.models.deletion
import memos.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0017_merge_20260806_1728'),
        ('memos', '0006_memonumbersequence'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MemoAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to=memos.models.memo_attachment_path)),
                ('original_name', models.CharField(blank=True, default='', max_length=255)),
                ('size', models.PositiveIntegerField(default=0)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='MemoWorkflowStep',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sequence', models.PositiveIntegerField(help_text='1-based position in the approval chain. Contiguous and unique per memo.')),
                ('role_type', models.CharField(choices=[('reviewer', 'Reviewer'), ('recommender', 'Recommender'), ('supporter', 'Supporter'), ('approver', 'Approver')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Awaiting Action'), ('completed', 'Completed'), ('rejected', 'Rejected'), ('skipped', 'Skipped')], db_index=True, default='pending', max_length=20)),
                ('designation', models.CharField(blank=True, default='', max_length=120)),
                ('department_label', models.CharField(blank=True, default='', max_length=150)),
                ('acted_at', models.DateTimeField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['memo', 'sequence'],
            },
        ),
        migrations.AddField(
            model_name='memo',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='memo',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='memo',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='memos', to='leaves.department'),
        ),
        migrations.AddField(
            model_name='memo',
            name='department_name',
            field=models.CharField(blank=True, default='', help_text='Department label captured at creation. Populated even when the author has only the legacy free-text department and no FK.', max_length=150),
        ),
        migrations.AlterField(
            model_name='memo',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('draft_for_review', 'Draft For Review'), ('submitted', 'Submitted'), ('under_review', 'Under Review'), ('recommended', 'Recommended'), ('supported', 'Supported'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('archived', 'Archived'), ('cancelled', 'Cancelled')], db_index=True, default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='memoapprovalstep',
            name='action',
            field=models.CharField(choices=[('created', 'Created'), ('submitted', 'Submitted'), ('sent_for_review', 'Sent for Review'), ('reviewed', 'Reviewed'), ('recommended', 'Recommended'), ('supported', 'Supported'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('returned', 'Returned'), ('archived', 'Archived'), ('cancelled', 'Cancelled'), ('commented', 'Commented')], max_length=20),
        ),
        migrations.AddIndex(
            model_name='memo',
            index=models.Index(fields=['status', 'created_by'], name='memo_status_author_idx'),
        ),
        migrations.AddIndex(
            model_name='memo',
            index=models.Index(fields=['status', 'department'], name='memo_status_dept_idx'),
        ),
        migrations.AddIndex(
            model_name='memo',
            index=models.Index(fields=['memo_type'], name='memo_type_idx'),
        ),
        migrations.AddIndex(
            model_name='memo',
            index=models.Index(fields=['-created_at'], name='memo_created_desc_idx'),
        ),
        migrations.AddField(
            model_name='memoattachment',
            name='memo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='memos.memo'),
        ),
        migrations.AddField(
            model_name='memoattachment',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='memo_attachments_uploaded', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='memoworkflowstep',
            name='assignee',
            field=models.ForeignKey(help_text='PROTECT, not CASCADE: deleting a user must never silently erase a row of a completed approval matrix.', on_delete=django.db.models.deletion.PROTECT, related_name='memo_workflow_steps', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='memoworkflowstep',
            name='memo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_steps', to='memos.memo'),
        ),
        migrations.AddIndex(
            model_name='memoworkflowstep',
            index=models.Index(fields=['assignee', 'status'], name='memo_step_assignee_idx'),
        ),
        migrations.AddConstraint(
            model_name='memoworkflowstep',
            constraint=models.UniqueConstraint(fields=('memo', 'sequence'), name='uniq_memo_step_sequence'),
        ),
        migrations.AddConstraint(
            model_name='memoworkflowstep',
            constraint=models.UniqueConstraint(fields=('memo', 'assignee'), name='uniq_memo_step_assignee'),
        ),
    ]
