# Generated by Django 5.2.16 on 2026-08-12 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memos', '0011_remove_memo_current_approver_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='memo',
            name='classification',
            field=models.CharField(choices=[('normal', 'Normal'), ('confidential', 'Confidential'), ('highly_confidential', 'Highly Confidential'), ('urgent', 'Urgent')], db_index=True, default='normal', help_text='Document sensitivity, shown as a badge on screen and printed on the face of the PDF. Confidential and above also narrow who may read the memo.', max_length=24),
        ),
        migrations.AddField(
            model_name='memo',
            name='reference_number',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Optional external reference this memo relates to (tender, contract, board minute, incoming letter).', max_length=100),
        ),
    ]
