# Generated by Django 5.2.16 on 2026-08-14 07:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('leaves', '0017_merge_20260806_1728'),
        ('memos', '0012_memo_classification_memo_reference_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MemoNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('opened_at', models.DateTimeField(auto_now_add=True)),
                ('memo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='note_round', to='memos.memo')),
                ('opened_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='memo_note_rounds_opened', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'memo note round',
            },
        ),
        migrations.CreateModel(
            name='MemoNoteRecipient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_name', models.CharField(blank=True, default='', max_length=150)),
                ('designation', models.CharField(blank=True, default='', max_length=120)),
                ('department_label', models.CharField(blank=True, default='', max_length=150)),
                ('status', models.CharField(choices=[('pending', 'Pending Note'), ('noted', 'Noted')], db_index=True, default='pending', max_length=12)),
                ('remarks', models.TextField(blank=True, default='')),
                ('noted_at', models.DateTimeField(blank=True, null=True)),
                ('notified_at', models.DateTimeField(blank=True, null=True)),
                ('reminded_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='memo_notes_requested', to=settings.AUTH_USER_MODEL)),
                ('note_round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to='memos.memonote')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='memo_notes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='MemoNoteAudit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('requested', 'Note requested'), ('noted', 'Noted'), ('removed', 'Note request withdrawn'), ('reminded', 'Note reminder sent')], max_length=12)),
                ('actor_name', models.CharField(blank=True, default='', max_length=150)),
                ('subject_name', models.CharField(blank=True, default='', help_text='Who the action was about, snapshotted - the recipient FK is SET_NULL and a withdrawn request deletes the recipient row.', max_length=150)),
                ('remarks', models.TextField(blank=True, default='')),
                ('at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='memo_note_actions', to=settings.AUTH_USER_MODEL)),
                ('note_round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_entries', to='memos.memonote')),
                ('recipient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_entries', to='memos.memonoterecipient')),
            ],
            options={
                'ordering': ['at'],
            },
        ),
        migrations.CreateModel(
            name='MemoStepUnavailability',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('original_assignee_name', models.CharField(blank=True, default='', max_length=150)),
                ('role_type', models.CharField(blank=True, default='', max_length=20)),
                ('reason', models.CharField(choices=[('annual_leave', 'Annual Leave'), ('sick_leave', 'Sick Leave'), ('training', 'Training'), ('meeting', 'Meeting'), ('official_visit', 'Official Visit'), ('emergency', 'Emergency')], max_length=20)),
                ('reason_note', models.TextField(blank=True, default='')),
                ('marked_by_name', models.CharField(blank=True, default='', max_length=150)),
                ('marked_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_by_name', models.CharField(blank=True, default='', max_length=150)),
                ('marked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='memo_unavailabilities_marked', to=settings.AUTH_USER_MODEL)),
                ('memo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unavailabilities', to='memos.memo')),
                ('original_assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='memo_unavailabilities', to=settings.AUTH_USER_MODEL)),
                ('resolved_by', models.ForeignKey(blank=True, help_text='Who approved the replacement. Distinct from marked_by: declaring an absence and authorising a stand-in are two different acts and an audit needs both names.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='memo_unavailabilities_resolved', to=settings.AUTH_USER_MODEL)),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unavailabilities', to='memos.memoworkflowstep')),
            ],
            options={
                'ordering': ['-marked_at'],
            },
        ),
        migrations.CreateModel(
            name='MemoAssignmentTransfer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sequence', models.PositiveIntegerField(default=0, help_text="The step's sequence, snapshotted so the record survives the step row being deleted.")),
                ('role_type', models.CharField(blank=True, default='', max_length=20)),
                ('kind', models.CharField(choices=[('alternate', 'Alternate approver'), ('acting', 'Acting approver'), ('self_assign', 'Self assigned'), ('assign_new', 'Reassigned'), ('transfer_ownership', 'Ownership transferred')], max_length=20)),
                ('from_user_name', models.CharField(blank=True, default='', max_length=150)),
                ('to_user_name', models.CharField(blank=True, default='', max_length=150)),
                ('reason', models.TextField()),
                ('actor_name', models.CharField(blank=True, default='', max_length=150)),
                ('at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='memo_assignment_transfers', to=settings.AUTH_USER_MODEL)),
                ('from_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='memo_steps_transferred_away', to=settings.AUTH_USER_MODEL)),
                ('memo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_transfers', to='memos.memo')),
                ('step', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers', to='memos.memoworkflowstep')),
                ('to_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='memo_steps_transferred_in', to=settings.AUTH_USER_MODEL)),
                ('unavailability', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers', to='memos.memostepunavailability')),
            ],
            options={
                'ordering': ['at'],
            },
        ),
        migrations.CreateModel(
            name='MemoArchiveAccess',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('target', models.CharField(choices=[('department', 'Department or unit'), ('employee', 'Employee'), ('group', 'Employee group')], max_length=12)),
                ('include_children', models.BooleanField(default=True, help_text='Departments only: also grant to every department beneath this one in the tree.')),
                ('target_label', models.CharField(blank=True, default='', help_text='Who was granted, snapshotted for the audit and the PDF.', max_length=200)),
                ('reason', models.TextField()),
                ('granted_by_name', models.CharField(blank=True, default='', max_length=150)),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_by_name', models.CharField(blank=True, default='', max_length=150)),
                ('revoke_reason', models.TextField(blank=True, default='')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='memo_archive_grants', to='leaves.department')),
                ('granted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='memo_archive_grants_made', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='memo_archive_grants', to='auth.group')),
                ('memo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archive_grants', to='memos.memo')),
                ('revoked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='memo_archive_grants_revoked', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='memo_archive_grants', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-granted_at'],
                'indexes': [models.Index(fields=['memo', 'revoked_at'], name='memo_grant_live_idx'), models.Index(fields=['user', 'revoked_at'], name='memo_grant_user_idx'), models.Index(fields=['department', 'revoked_at'], name='memo_grant_dept_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('department__isnull', False), ('group__isnull', True), ('target', 'department'), ('user__isnull', True)), models.Q(('department__isnull', True), ('group__isnull', True), ('target', 'employee'), ('user__isnull', False)), models.Q(('department__isnull', True), ('group__isnull', False), ('target', 'group'), ('user__isnull', True)), _connector='OR'), name='memo_grant_target_matches_column')],
            },
        ),
        migrations.AddIndex(
            model_name='memonoterecipient',
            index=models.Index(fields=['user', 'status'], name='memo_note_user_idx'),
        ),
        migrations.AddConstraint(
            model_name='memonoterecipient',
            constraint=models.UniqueConstraint(fields=('note_round', 'user'), name='uniq_memo_note_recipient'),
        ),
        migrations.AddIndex(
            model_name='memostepunavailability',
            index=models.Index(fields=['memo', 'resolved_at'], name='memo_unavail_open_idx'),
        ),
    ]
