# Generated by Django 5.2.16 on 2026-08-14 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memos', '0013_memonote_memonoterecipient_memonoteaudit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memoapprovalstep',
            name='action',
            field=models.CharField(choices=[('created', 'Created'), ('submitted', 'Submitted'), ('sent_for_review', 'Sent for Review'), ('reviewed', 'Reviewed'), ('recommended', 'Recommended'), ('supported', 'Supported'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('returned', 'Returned'), ('archived', 'Archived'), ('cancelled', 'Cancelled'), ('commented', 'Commented'), ('edited', 'Edited'), ('noted', 'Noted'), ('access_granted', 'Archive access granted'), ('access_revoked', 'Archive access revoked'), ('approver_changed', 'Approver changed'), ('recommender_changed', 'Recommender changed')], max_length=20),
        ),
        migrations.AlterField(
            model_name='memoassignmenttransfer',
            name='kind',
            field=models.CharField(choices=[('alternate', 'Alternate'), ('acting', 'Acting'), ('self_assign', 'Self assigned'), ('assign_new', 'Reassigned'), ('transfer_ownership', 'Ownership transferred')], max_length=20),
        ),
    ]
