# Generated by Django 5.2.16 on 2026-10-04 12:33

import memos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memos', '0017_phase_a_organization_required'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memo',
            name='attachment',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to=memos.models.memo_attachment_path),
        ),
        migrations.AlterField(
            model_name='memoattachment',
            name='file',
            field=models.FileField(max_length=255, upload_to=memos.models.memo_attachment_path),
        ),
    ]
