# Generated by Django 5.2.16 on 2026-07-14 07:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('leaves', '0015_alter_leave_leave_type_alter_leavebalance_leave_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Inventory categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('asset_code', models.CharField(editable=False, max_length=32, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('serial_number', models.CharField(blank=True, default='', max_length=120)),
                ('status', models.CharField(choices=[('available', 'Available'), ('assigned', 'Assigned'), ('out', 'Taken Out'), ('maintenance', 'Under Maintenance'), ('retired', 'Retired')], default='available', max_length=20)),
                ('condition', models.CharField(choices=[('new', 'New'), ('good', 'Good'), ('fair', 'Fair'), ('damaged', 'Damaged')], default='good', max_length=20)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='inventory.inventorycategory')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_items', to='leaves.department')),
            ],
            options={
                'ordering': ['asset_code'],
            },
        ),
        migrations.CreateModel(
            name='InventorySequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=8)),
                ('year', models.PositiveIntegerField(default=0)),
                ('last_value', models.PositiveIntegerField(default=0)),
            ],
            options={
                'unique_together': {('key', 'year')},
            },
        ),
        migrations.CreateModel(
            name='ItemAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('assigned_to_name', models.CharField(blank=True, default='', max_length=150)),
                ('assigned_by_name', models.CharField(blank=True, default='', max_length=150)),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('returned_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_assigned_by', to=settings.AUTH_USER_MODEL)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_assignments', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='inventory.inventoryitem')),
            ],
            options={
                'ordering': ['-assigned_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('item',), name='uniq_active_assignment_per_item')],
            },
        ),
        migrations.CreateModel(
            name='TakeOutRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference', models.CharField(editable=False, max_length=32, unique=True)),
                ('item_code', models.CharField(blank=True, default='', max_length=32)),
                ('item_name', models.CharField(blank=True, default='', max_length=150)),
                ('requested_by_name', models.CharField(blank=True, default='', max_length=150)),
                ('purpose', models.CharField(choices=[('home', 'Take Home'), ('outside', 'Use Outside Office'), ('repair', 'Repair / Servicing')], default='home', max_length=12)),
                ('reason', models.TextField()),
                ('expected_out_date', models.DateField()),
                ('expected_return_date', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('returned', 'Returned')], default='pending', max_length=12)),
                ('approver_name', models.CharField(blank=True, default='', max_length=150)),
                ('approver_remarks', models.TextField(blank=True, default='')),
                ('action_date', models.DateTimeField(blank=True, null=True)),
                ('actual_return_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='takeout_reviewed', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_takeouts', to='leaves.department')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='takeout_requests', to='inventory.inventoryitem')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='takeout_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='inventory_t_status_ba1db3_idx'), models.Index(fields=['requested_by', 'status'], name='inventory_t_request_095421_idx')],
            },
        ),
    ]
