# Generated by Django 5.2.16 on 2026-07-14 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_seed_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='accessories',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='asset_type',
            field=models.CharField(choices=[('it', 'IT / Computing'), ('peripheral', 'Peripheral'), ('furniture', 'Furniture'), ('vehicle', 'Vehicle'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='brand',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='cpu',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='gpu',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='mac_address',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='model',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='os',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='purchase_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='ram',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='screen_size',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='specifications',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='storage_size',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='storage_type',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='vendor',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='warranty_expiry',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='itemassignment',
            name='accessories',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='itemassignment',
            name='assigned_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='itemassignment',
            name='handover_condition',
            field=models.CharField(blank=True, choices=[('new', 'New'), ('good', 'Good'), ('fair', 'Fair'), ('damaged', 'Damaged')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='itemassignment',
            name='is_handover',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='itemassignment',
            name='return_condition',
            field=models.CharField(blank=True, choices=[('new', 'New'), ('good', 'Good'), ('fair', 'Fair'), ('damaged', 'Damaged')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='itemassignment',
            name='return_remarks',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
