# Generated by Django 5.2.16 on 2026-07-17 06:22
#
# Custody history must survive item deletion (the module's stated design, already
# true for TakeOutRequest): item FK CASCADE -> SET_NULL + asset_code/name snapshots.
# Existing rows are backfilled from their live item so pre-existing history keeps a
# readable label once the item is gone.

import django.db.models.deletion
from django.db import migrations, models


def backfill_item_snapshots(apps, schema_editor):
    ItemAssignment = apps.get_model("inventory", "ItemAssignment")
    InventoryItem = apps.get_model("inventory", "InventoryItem")
    # Joined F() refs are not allowed in UPDATE; correlate with a subquery instead.
    live = InventoryItem.objects.filter(pk=models.OuterRef("item_id"))
    ItemAssignment.objects.filter(item__isnull=False).update(
        item_code=models.Subquery(live.values("asset_code")[:1]),
        item_name=models.Subquery(live.values("name")[:1]),
    )


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_inventoryitem_accessories_inventoryitem_asset_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemassignment',
            name='item_code',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='itemassignment',
            name='item_name',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.RunPython(backfill_item_snapshots, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='itemassignment',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments', to='inventory.inventoryitem'),
        ),
    ]
