# Generated by Django 5.2.16 on 2026-08-14 10:17

import django.db.models.deletion
import inventory.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_itemassignment_item_code_itemassignment_item_name_and_more'),
        ('leaves', '0017_merge_20260806_1728'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetLifecycleEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('item_code', models.CharField(blank=True, default='', max_length=32)),
                ('item_name', models.CharField(blank=True, default='', max_length=150)),
                ('sequence', models.PositiveIntegerField(default=0)),
                ('event', models.CharField(choices=[('created', 'Created'), ('procurement', 'Procurement raised'), ('received', 'Received'), ('stocked', 'Placed in stock'), ('requested', 'Requested'), ('request_approved', 'Request approved'), ('request_rejected', 'Request rejected'), ('assigned', 'Assigned'), ('handed_over', 'Handed over'), ('accepted', 'Accepted by holder'), ('reassigned', 'Reassigned'), ('return_requested', 'Return requested'), ('returned', 'Returned'), ('taken_out', 'Taken out'), ('brought_back', 'Brought back'), ('maint_reported', 'Maintenance reported'), ('maint_started', 'Maintenance started'), ('maint_done', 'Maintenance completed'), ('condition_changed', 'Condition changed'), ('location_changed', 'Location changed'), ('disposed', 'Disposed'), ('archived', 'Archived'), ('updated', 'Details updated')], db_index=True, max_length=24)),
                ('from_status', models.CharField(blank=True, default='', max_length=20)),
                ('to_status', models.CharField(blank=True, default='', max_length=20)),
                ('actor_name', models.CharField(blank=True, default='', max_length=150)),
                ('subject_name', models.CharField(blank=True, default='', max_length=150)),
                ('remarks', models.TextField(blank=True, default='')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['at', 'sequence'],
            },
        ),
        migrations.CreateModel(
            name='AssetRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference', models.CharField(editable=False, max_length=32, unique=True)),
                ('item_code', models.CharField(blank=True, default='', max_length=32)),
                ('item_name', models.CharField(blank=True, default='', max_length=150)),
                ('requested_by_name', models.CharField(blank=True, default='', max_length=150)),
                ('purpose', models.TextField()),
                ('needed_by', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('supervisor_approved', 'Supervisor Approved'), ('inventory_approved', 'Inventory Approved'), ('handed_over', 'Handed Over'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=24)),
                ('supervisor_name', models.CharField(blank=True, default='', max_length=150)),
                ('supervisor_remarks', models.TextField(blank=True, default='')),
                ('supervisor_at', models.DateTimeField(blank=True, null=True)),
                ('inventory_officer_name', models.CharField(blank=True, default='', max_length=150)),
                ('inventory_remarks', models.TextField(blank=True, default='')),
                ('inventory_at', models.DateTimeField(blank=True, null=True)),
                ('handed_over_at', models.DateTimeField(blank=True, null=True)),
                ('handover_condition', models.CharField(blank=True, choices=[('new', 'New'), ('good', 'Good'), ('fair', 'Fair'), ('damaged', 'Damaged')], default='', max_length=20)),
                ('accessories', models.CharField(blank=True, default='', max_length=255)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('acceptance_remarks', models.TextField(blank=True, default='')),
                ('rejected_by_name', models.CharField(blank=True, default='', max_length=150)),
                ('rejection_reason', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AssetReturn',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference', models.CharField(editable=False, max_length=32, unique=True)),
                ('item_code', models.CharField(blank=True, default='', max_length=32)),
                ('item_name', models.CharField(blank=True, default='', max_length=150)),
                ('returned_by_name', models.CharField(blank=True, default='', max_length=150)),
                ('reason', models.TextField(blank=True, default='')),
                ('declared_condition', models.CharField(blank=True, choices=[('new', 'New'), ('good', 'Good'), ('fair', 'Fair'), ('damaged', 'Damaged')], default='', max_length=20)),
                ('declared_remarks', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('requested', 'Return Requested'), ('verifying', 'Under Verification'), ('inspected', 'Condition Inspected'), ('accepted', 'Return Accepted'), ('rejected', 'Return Rejected')], db_index=True, default='requested', max_length=12)),
                ('verified_by_name', models.CharField(blank=True, default='', max_length=150)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('inspected_condition', models.CharField(blank=True, choices=[('new', 'New'), ('good', 'Good'), ('fair', 'Fair'), ('damaged', 'Damaged')], default='', max_length=20)),
                ('inspection_remarks', models.TextField(blank=True, default='')),
                ('inspected_at', models.DateTimeField(blank=True, null=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, default='')),
                ('returned_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceTicket',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference', models.CharField(editable=False, max_length=32, unique=True)),
                ('item_code', models.CharField(blank=True, default='', max_length=32)),
                ('item_name', models.CharField(blank=True, default='', max_length=150)),
                ('reported_by_name', models.CharField(blank=True, default='', max_length=150)),
                ('issue', models.TextField()),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('critical', 'Critical')], default='normal', max_length=10)),
                ('status', models.CharField(choices=[('reported', 'Reported'), ('assigned', 'Assigned'), ('in_maintenance', 'In Maintenance'), ('completed', 'Completed'), ('returned', 'Returned to Service'), ('cancelled', 'Cancelled')], db_index=True, default='reported', max_length=16)),
                ('assigned_to_name', models.CharField(blank=True, default='', max_length=150)),
                ('vendor', models.CharField(blank=True, default='', help_text='External repairer, when the work is not done in house.', max_length=150)),
                ('assigned_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('returned_at', models.DateTimeField(blank=True, null=True)),
                ('resolution', models.TextField(blank=True, default='')),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('condition_after', models.CharField(blank=True, choices=[('new', 'New'), ('good', 'Good'), ('fair', 'Fair'), ('damaged', 'Damaged')], default='', max_length=20)),
                ('previous_item_status', models.CharField(blank=True, default='', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='disposal_method',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='disposal_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='disposal_value',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Proceeds of sale, if any. Null means disposed at no value.', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='disposed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='document',
            field=models.FileField(blank=True, help_text='Invoice, warranty card or delivery note.', null=True, upload_to=inventory.models.asset_document_path),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='document_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='location',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Where the asset physically is - room, floor, site. Distinct from department, which is who it belongs to: a laptop owned by Finance can sit in the server room.', max_length=150),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=inventory.models.asset_photo_path),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='warranty_start',
            field=models.DateField(blank=True, help_text='Warranty START. The module already had an expiry; without a start date a warranty cannot be shown as a period, only as a deadline.', null=True),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='status',
            field=models.CharField(choices=[('procurement', 'On Order'), ('received', 'Received'), ('available', 'In Stock'), ('assigned', 'Assigned'), ('out', 'Taken Out'), ('maintenance', 'Under Maintenance'), ('retired', 'Retired'), ('disposed', 'Disposed'), ('archived', 'Archived')], default='available', max_length=20),
        ),
        migrations.AddIndex(
            model_name='inventoryitem',
            index=models.Index(fields=['status'], name='asset_status_idx'),
        ),
        migrations.AddIndex(
            model_name='inventoryitem',
            index=models.Index(fields=['status', 'department'], name='asset_status_dept_idx'),
        ),
        migrations.AddIndex(
            model_name='inventoryitem',
            index=models.Index(fields=['warranty_expiry'], name='asset_warranty_idx'),
        ),
        migrations.AddField(
            model_name='assetlifecycleevent',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assetlifecycleevent',
            name='item',
            field=models.ForeignKey(blank=True, help_text='SET_NULL with a snapshot, matching every other history table here: deleting an asset must not erase the record that it existed and who held it.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lifecycle_events', to='inventory.inventoryitem'),
        ),
        migrations.AddField(
            model_name='assetrequest',
            name='assignment',
            field=models.OneToOneField(blank=True, help_text='Created at handover. The request is the paperwork; the assignment is the custody record, and they are separate because an asset can be assigned without a request (a direct issue by an officer) but never the reverse.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='request', to='inventory.itemassignment'),
        ),
        migrations.AddField(
            model_name='assetrequest',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_requests', to='leaves.department'),
        ),
        migrations.AddField(
            model_name='assetrequest',
            name='inventory_officer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_requests_processed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assetrequest',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_requests', to='inventory.inventoryitem'),
        ),
        migrations.AddField(
            model_name='assetrequest',
            name='requested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assetrequest',
            name='requested_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_requests', to='inventory.inventorycategory'),
        ),
        migrations.AddField(
            model_name='assetrequest',
            name='supervisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_requests_supervised', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assetreturn',
            name='assignment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='returns', to='inventory.itemassignment'),
        ),
        migrations.AddField(
            model_name='assetreturn',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_returns', to='inventory.inventoryitem'),
        ),
        migrations.AddField(
            model_name='assetreturn',
            name='returned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_returns', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assetreturn',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_returns_verified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='maintenanceticket',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_assigned', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='maintenanceticket',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_tickets', to='inventory.inventoryitem'),
        ),
        migrations.AddField(
            model_name='maintenanceticket',
            name='reported_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_reported', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='assetlifecycleevent',
            index=models.Index(fields=['item', 'at'], name='asset_event_item_idx'),
        ),
        migrations.AddIndex(
            model_name='assetrequest',
            index=models.Index(fields=['status'], name='asset_req_status_idx'),
        ),
        migrations.AddIndex(
            model_name='assetrequest',
            index=models.Index(fields=['requested_by', 'status'], name='asset_req_user_idx'),
        ),
        migrations.AddIndex(
            model_name='assetreturn',
            index=models.Index(fields=['status'], name='asset_ret_status_idx'),
        ),
        migrations.AddIndex(
            model_name='maintenanceticket',
            index=models.Index(fields=['status'], name='maint_status_idx'),
        ),
        migrations.AddIndex(
            model_name='maintenanceticket',
            index=models.Index(fields=['item', 'status'], name='maint_item_idx'),
        ),
    ]
