# Generated by Django 5.2.16 on 2026-08-24 07:37

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_inventory_officer_group'),
        ('leaves', '0017_merge_20260806_1728'),
    ]
    
    operations = [
        migrations.AddConstraint(
            model_name='inventoryitem',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('serial_number'), condition=models.Q(('serial_number', ''), _negated=True), name='uniq_inventory_serial_number'),
        ),
    ]
