# Generated by Django 5.2.16 on 2026-09-13 08:51

import django.db.models.deletion
import inventory.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_inventoryitem_uniq_inventory_serial_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetlifecycleevent',
            name='event',
            field=models.CharField(choices=[('created', 'Created'), ('procurement', 'Procurement raised'), ('received', 'Received'), ('stocked', 'Placed in stock'), ('requested', 'Requested'), ('request_approved', 'Request approved'), ('request_rejected', 'Request rejected'), ('assigned', 'Assigned'), ('handed_over', 'Handed over'), ('accepted', 'Accepted by holder'), ('reassigned', 'Reassigned'), ('transferred', 'Transferred'), ('department_changed', 'Department changed'), ('return_requested', 'Return requested'), ('returned', 'Returned'), ('taken_out', 'Taken out'), ('brought_back', 'Brought back'), ('maint_reported', 'Maintenance reported'), ('maint_started', 'Maintenance started'), ('maint_done', 'Maintenance completed'), ('condition_changed', 'Condition changed'), ('location_changed', 'Location changed'), ('disposed', 'Disposed'), ('archived', 'Archived'), ('updated', 'Details updated')], db_index=True, max_length=24),
        ),
        migrations.CreateModel(
            name='AssetTransfer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transfer_number', models.CharField(editable=False, max_length=20, unique=True)),
                ('item_code', models.CharField(blank=True, default='', max_length=32)),
                ('item_name', models.CharField(blank=True, default='', max_length=150)),
                ('from_employee_name', models.CharField(blank=True, default='', max_length=150)),
                ('from_department_name', models.CharField(blank=True, default='', max_length=150)),
                ('to_employee_name', models.CharField(blank=True, default='', max_length=150)),
                ('to_department_name', models.CharField(blank=True, default='', max_length=150)),
                ('transfer_date', models.DateField()),
                ('reason', models.CharField(choices=[('employee_exit', 'Employee Exit'), ('department_transfer', 'Department Transfer'), ('role_change', 'Role Change'), ('asset_replacement', 'Asset Replacement'), ('temporary_assignment', 'Temporary Assignment'), ('project_assignment', 'Project Assignment'), ('other', 'Other')], max_length=24)),
                ('condition', models.CharField(choices=[('excellent', 'Excellent'), ('good', 'Good'), ('fair', 'Fair'), ('damaged', 'Damaged'), ('lost', 'Lost')], max_length=12)),
                ('remarks', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('dept_head_review', 'Department Head Review'), ('hr_review', 'HR Review'), ('admin_approval', 'Admin Approval'), ('completed', 'Completed'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], db_index=True, default='draft', max_length=20)),
                ('requested_by_name', models.CharField(blank=True, default='', max_length=150)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('dept_head_name', models.CharField(blank=True, default='', max_length=150)),
                ('dept_head_at', models.DateTimeField(blank=True, null=True)),
                ('dept_head_remarks', models.TextField(blank=True, default='')),
                ('hr_name', models.CharField(blank=True, default='', max_length=150)),
                ('hr_at', models.DateTimeField(blank=True, null=True)),
                ('hr_remarks', models.TextField(blank=True, default='')),
                ('approved_by_name', models.CharField(blank=True, default='', max_length=150)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('admin_remarks', models.TextField(blank=True, default='')),
                ('rejected_by_name', models.CharField(blank=True, default='', max_length=150)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_stage', models.CharField(blank=True, default='', max_length=20)),
                ('rejection_remarks', models.TextField(blank=True, default='')),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, help_text='The Admin who gave final approval. Completion follows at once.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_transfers_approved', to=settings.AUTH_USER_MODEL)),
                ('closed_assignment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='inventory.itemassignment')),
                ('dept_head_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('from_employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_transfers_out', to=settings.AUTH_USER_MODEL)),
                ('hr_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers', to='inventory.inventoryitem')),
                ('opened_assignment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='inventory.itemassignment')),
                ('rejected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_transfers_requested', to=settings.AUTH_USER_MODEL)),
                ('to_employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_transfers_in', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AssetTransferAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(max_length=255, upload_to=inventory.models.transfer_attachment_path)),
                ('original_name', models.CharField(max_length=255)),
                ('size', models.PositiveIntegerField(default=0)),
                ('uploaded_by_name', models.CharField(blank=True, default='', max_length=150)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('transfer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='inventory.assettransfer')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='AssetTransferEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sequence', models.PositiveIntegerField(default=0)),
                ('action', models.CharField(choices=[('created', 'Transfer created'), ('submitted', 'Submitted'), ('dept_head_approved', 'Approved by Department Head'), ('hr_approved', 'Approved by HR'), ('admin_approved', 'Approved by Admin'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled'), ('completed', 'Completed'), ('owner_changed', 'Owner changed'), ('department_changed', 'Department changed'), ('attachment_added', 'Attachment added')], db_index=True, max_length=24)),
                ('from_status', models.CharField(blank=True, default='', max_length=20)),
                ('to_status', models.CharField(blank=True, default='', max_length=20)),
                ('actor_name', models.CharField(blank=True, default='', max_length=150)),
                ('remarks', models.TextField(blank=True, default='')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('transfer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='inventory.assettransfer')),
            ],
            options={
                'ordering': ['at', 'sequence'],
            },
        ),
        migrations.AddIndex(
            model_name='assettransfer',
            index=models.Index(fields=['status'], name='transfer_status_idx'),
        ),
        migrations.AddIndex(
            model_name='assettransfer',
            index=models.Index(fields=['item', 'status'], name='transfer_item_idx'),
        ),
        migrations.AddConstraint(
            model_name='assettransfer',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['draft', 'dept_head_review', 'hr_review', 'admin_approval'])), fields=('item',), name='uniq_open_transfer_per_item'),
        ),
    ]
