# Generated by Django 5.2.16 on 2026-09-13 10:19

import django.db.models.deletion
import inventory.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_alter_assetlifecycleevent_event_assettransfer_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorycategory',
            name='default_useful_life_months',
            field=models.PositiveIntegerField(blank=True, help_text='Months over which assets in this category are depreciated.', null=True),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='amc_contract_number',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='amc_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='amc_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='amc_provider',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='amc_start',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='salvage_value',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Residual value at the end of its useful life. Blank means zero.', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='useful_life_months',
            field=models.PositiveIntegerField(blank=True, help_text="Overrides the category's useful life for this asset.", null=True),
        ),
        migrations.AlterField(
            model_name='assetlifecycleevent',
            name='event',
            field=models.CharField(choices=[('created', 'Created'), ('procurement', 'Procurement raised'), ('received', 'Received'), ('stocked', 'Placed in stock'), ('requested', 'Requested'), ('request_approved', 'Request approved'), ('request_rejected', 'Request rejected'), ('assigned', 'Assigned'), ('handed_over', 'Handed over'), ('accepted', 'Accepted by holder'), ('reassigned', 'Reassigned'), ('transferred', 'Transferred'), ('department_changed', 'Department changed'), ('return_requested', 'Return requested'), ('returned', 'Returned'), ('taken_out', 'Taken out'), ('brought_back', 'Brought back'), ('maint_reported', 'Maintenance reported'), ('maint_started', 'Maintenance started'), ('maint_done', 'Maintenance completed'), ('condition_changed', 'Condition changed'), ('location_changed', 'Location changed'), ('disposed', 'Disposed'), ('lost', 'Reported lost'), ('archived', 'Archived'), ('updated', 'Details updated')], db_index=True, max_length=24),
        ),
        migrations.CreateModel(
            name='AssetDisposal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('disposal_number', models.CharField(editable=False, max_length=20, unique=True)),
                ('item_code', models.CharField(blank=True, default='', max_length=32)),
                ('item_name', models.CharField(blank=True, default='', max_length=150)),
                ('department_name', models.CharField(blank=True, default='', max_length=150)),
                ('disposal_type', models.CharField(choices=[('sale', 'Sold'), ('scrap', 'Scrapped'), ('donation', 'Donated'), ('recycle', 'E-waste recycling'), ('write_off', 'Written off'), ('lost', 'Lost or stolen')], max_length=12)),
                ('reason', models.TextField()),
                ('expected_proceeds', models.DecimalField(blank=True, decimal_places=2, help_text='What a sale is expected to raise. Ignored for types with no proceeds.', max_digits=12, null=True)),
                ('remarks', models.TextField(blank=True, default='')),
                ('last_holder_name', models.CharField(blank=True, default='', max_length=150)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('dept_head_review', 'Department Head Review'), ('admin_approval', 'Admin Approval'), ('disposed', 'Disposed'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], db_index=True, default='draft', max_length=20)),
                ('requested_by_name', models.CharField(blank=True, default='', max_length=150)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('dept_head_name', models.CharField(blank=True, default='', max_length=150)),
                ('dept_head_at', models.DateTimeField(blank=True, null=True)),
                ('dept_head_remarks', models.TextField(blank=True, default='')),
                ('approved_by_name', models.CharField(blank=True, default='', max_length=150)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('admin_remarks', models.TextField(blank=True, default='')),
                ('rejected_by_name', models.CharField(blank=True, default='', max_length=150)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_stage', models.CharField(blank=True, default='', max_length=20)),
                ('rejection_remarks', models.TextField(blank=True, default='')),
                ('disposed_at', models.DateTimeField(blank=True, null=True)),
                ('purchase_cost_at_disposal', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('accumulated_at_disposal', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('book_value_at_disposal', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('proceeds', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_disposals_approved', to=settings.AUTH_USER_MODEL)),
                ('dept_head_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(blank=True, help_text='PROTECT: an asset with a disposal record can never be deleted.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='disposals', to='inventory.inventoryitem')),
                ('last_holder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('rejected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_disposals_requested', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AssetDisposalAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(max_length=255, upload_to=inventory.models.disposal_attachment_path)),
                ('original_name', models.CharField(max_length=255)),
                ('size', models.PositiveIntegerField(default=0)),
                ('uploaded_by_name', models.CharField(blank=True, default='', max_length=150)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('disposal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attachments', to='inventory.assetdisposal')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='AssetDisposalEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sequence', models.PositiveIntegerField(default=0)),
                ('action', models.CharField(choices=[('created', 'Disposal requested'), ('submitted', 'Submitted'), ('dept_head_approved', 'Approved by Department Head'), ('admin_approved', 'Approved by Admin'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled'), ('custody_closed', 'Custody closed'), ('disposed', 'Asset disposed'), ('attachment_added', 'Attachment added')], db_index=True, max_length=24)),
                ('from_status', models.CharField(blank=True, default='', max_length=20)),
                ('to_status', models.CharField(blank=True, default='', max_length=20)),
                ('actor_name', models.CharField(blank=True, default='', max_length=150)),
                ('remarks', models.TextField(blank=True, default='')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('disposal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='inventory.assetdisposal')),
            ],
            options={
                'ordering': ['at', 'sequence'],
            },
        ),
        migrations.AddIndex(
            model_name='assetdisposal',
            index=models.Index(fields=['status'], name='disposal_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='assetdisposal',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['draft', 'dept_head_review', 'admin_approval'])), fields=('item',), name='uniq_open_disposal_per_item'),
        ),
    ]
