# Generated by Django 5.2.16 on 2026-10-04 12:33

import inventory.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_phase_a_organization_required'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryitem',
            name='document',
            field=models.FileField(blank=True, help_text='Invoice, warranty card or delivery note.', max_length=255, null=True, upload_to=inventory.models.asset_document_path),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='photo',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to=inventory.models.asset_photo_path),
        ),
    ]
