# Generated by Django 5.2.16 on 2026-08-26 09:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentDraft',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('memo', 'Memo'), ('minute', 'Minute'), ('circular', 'Circular')], db_index=True, max_length=16)),
                ('document_key', models.CharField(db_index=True, max_length=64)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('version', models.PositiveIntegerField(default=0)),
                ('autosave_count', models.PositiveIntegerField(default=0)),
                ('device_label', models.CharField(blank=True, default='', max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('saved_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_drafts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-saved_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentDraftVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version', models.PositiveIntegerField()),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('reason', models.CharField(choices=[('manual_save', 'Manual save'), ('tab_hidden', 'Switched away'), ('interval', 'Periodic'), ('before_restore', 'Superseded by a restore')], default='interval', max_length=20)),
                ('saved_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('draft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='drafts.documentdraft')),
                ('saved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-version'],
            },
        ),
        migrations.AddIndex(
            model_name='documentdraft',
            index=models.Index(fields=['saved_at'], name='draft_saved_at_idx'),
        ),
        migrations.AddIndex(
            model_name='documentdraft',
            index=models.Index(fields=['owner', '-saved_at'], name='draft_owner_recent_idx'),
        ),
        migrations.AddConstraint(
            model_name='documentdraft',
            constraint=models.UniqueConstraint(fields=('kind', 'document_key', 'owner'), name='uniq_draft_per_document_per_user'),
        ),
        migrations.AddIndex(
            model_name='documentdraftversion',
            index=models.Index(fields=['draft', '-version'], name='draftver_recent_idx'),
        ),
    ]
