# Generated by Django 5.2.16 on 2026-08-03 10:24

import django.db.models.deletion
from django.db import migrations, models

# marked_by has carried this information since the app was written; `source`
# becomes the canonical field in Phase 5, so existing rows are translated rather
# than defaulted to 'browser' (which would mislabel every HR correction).
_MARKED_BY_TO_SOURCE = {"self": "browser", "hr": "hr", "system": "biometric"}


def backfill_source(apps, schema_editor):
    Attendance = apps.get_model("attendance", "Attendance")
    for marked_by, source in _MARKED_BY_TO_SOURCE.items():
        Attendance.objects.filter(marked_by=marked_by).update(source=source)


def reverse_backfill(apps, schema_editor):
    """No-op: `source` is dropped by the reverse AddField, and `marked_by` —
    the field it was derived from — was never modified."""


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_attendance_location'),
        ('biometric', '0002_mapping_validity'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='browser_check_in',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='browser_check_out',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_records', to='biometric.biometricdevice'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='first_punch_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='last_punch_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='punch_count',
            field=models.PositiveSmallIntegerField(default=0, help_text='All raw punches for the day, including breaks and overtime.'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='source',
            field=models.CharField(choices=[('browser', 'Browser check-in'), ('biometric', 'Biometric device'), ('hr', 'HR entry')], default='browser', max_length=20),
        ),
        migrations.RunPython(backfill_source, reverse_backfill),
    ]
