# Generated by Django 5.2.16 on 2026-08-04 07:07

import datetime
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_attendance_source_fields'),
        ('leaves', '0016_comp_attendance_unique'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.SlugField(max_length=40, unique=True)),
                ('name', models.CharField(max_length=60, unique=True)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('grace_minutes', models.PositiveSmallIntegerField(default=0, help_text='Minutes after start_time before a check-in counts as late.')),
                ('break_minutes', models.PositiveSmallIntegerField(default=0, help_text='Unpaid break length. Only deducted when the policy says so.')),
                ('crosses_midnight', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['start_time', 'name'],
            },
        ),
        migrations.AddField(
            model_name='attendance',
            name='comp_off_days',
            field=models.DecimalField(db_default=Decimal('0.00'), decimal_places=2, default=Decimal('0.00'), help_text='Comp days earned by working this Saturday/holiday: 0, 0.5 or 1.', max_digits=4),
        ),
        migrations.AddField(
            model_name='attendance',
            name='comp_off_eligible',
            field=models.BooleanField(db_default=False, default=False),
        ),
        migrations.AddField(
            model_name='attendance',
            name='is_wfh',
            field=models.BooleanField(db_default=False, default=False, help_text='An approved WFH request covers this day. On its own this is NOT attendance — a check-in is still required.'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='late_minutes',
            field=models.PositiveSmallIntegerField(db_default=0, default=0, help_text='Minutes late after the shift/policy grace period.'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='overtime_hours',
            field=models.DecimalField(db_default=Decimal('0.00'), decimal_places=2, default=Decimal('0.00'), help_text='Hours beyond the policy threshold. Payroll-ready.', max_digits=5),
        ),
        migrations.AddField(
            model_name='attendance',
            name='regular_hours',
            field=models.DecimalField(db_default=Decimal('0.00'), decimal_places=2, default=Decimal('0.00'), max_digits=5),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('late', 'Late'), ('half_day', 'Half Day'), ('on_leave', 'On Leave'), ('holiday', 'Holiday'), ('wfh', 'Work From Home')], default='absent', max_length=20),
        ),
        migrations.CreateModel(
            name='AttendancePolicy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('office_start_time', models.TimeField(default=datetime.time(10, 0))),
                ('grace_minutes', models.PositiveSmallIntegerField(default=0)),
                ('absent_cutoff_time', models.TimeField(default=datetime.time(18, 0), help_text='Local time after which today may be judged Absent.')),
                ('half_day_hours', models.DecimalField(decimal_places=2, default=Decimal('5.00'), max_digits=4)),
                ('full_day_hours', models.DecimalField(decimal_places=2, default=Decimal('8.00'), max_digits=4)),
                ('deduct_breaks', models.BooleanField(default=False, help_text='Subtract paired break punches from worked hours. The live device has recorded zero break punches, so this is off.')),
                ('overtime_threshold_hours', models.DecimalField(blank=True, decimal_places=2, help_text='Hours beyond which time counts as overtime. NULL disables overtime entirely.', max_digits=4, null=True)),
                ('overtime_min_minutes', models.PositiveSmallIntegerField(default=30, help_text='Ignore overtime shorter than this.')),
                ('comp_off_enabled', models.BooleanField(default=False)),
                ('comp_off_on_saturday', models.BooleanField(default=True)),
                ('comp_off_on_holiday', models.BooleanField(default=True)),
                ('comp_off_min_hours', models.DecimalField(decimal_places=2, default=Decimal('4.00'), help_text='Absolute floor: below this, nothing is earned.', max_digits=4)),
                ('comp_off_half_day_hours', models.DecimalField(decimal_places=2, default=Decimal('4.00'), help_text='Worked hours earning 0.5 comp days.', max_digits=4)),
                ('comp_off_full_day_hours', models.DecimalField(decimal_places=2, default=Decimal('6.00'), help_text='Worked hours earning 1.0 comp days.', max_digits=4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_policies_created', to=settings.AUTH_USER_MODEL)),
                ('default_shift', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='policies', to='attendance.shift')),
            ],
            options={
                'verbose_name_plural': 'attendance policies',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='attendance',
            name='applied_policy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_records', to='attendance.attendancepolicy'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='applied_shift',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_records', to='attendance.shift'),
        ),
        migrations.CreateModel(
            name='PolicyAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scope', models.CharField(choices=[('global', 'Global'), ('department', 'Department'), ('user', 'User')], max_length=12)),
                ('effective_from', models.DateField()),
                ('effective_until', models.DateField(blank=True, help_text='Leave empty for an open-ended assignment. Setting it is the supported way to retire an assignment without losing history.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_policy_assignments_created', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendance_policy_assignments', to='leaves.department')),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='attendance.attendancepolicy')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendance_policy_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-effective_from'],
                'indexes': [models.Index(fields=['scope', 'effective_from'], name='attendance__scope_033c83_idx'), models.Index(fields=['user', 'effective_from'], name='attendance__user_id_98ff2d_idx'), models.Index(fields=['department', 'effective_from'], name='attendance__departm_53aeaa_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('department__isnull', True), ('scope', 'global'), ('user__isnull', True)), models.Q(('department__isnull', False), ('scope', 'department'), ('user__isnull', True)), models.Q(('department__isnull', True), ('scope', 'user'), ('user__isnull', False)), _connector='OR'), name='attendance_policy_assignment_scope_target'), models.UniqueConstraint(condition=models.Q(('effective_until__isnull', True), ('scope', 'global')), fields=('scope',), name='uniq_open_global_policy_assignment'), models.UniqueConstraint(condition=models.Q(('effective_until__isnull', True), ('scope', 'department')), fields=('department',), name='uniq_open_department_policy_assignment'), models.UniqueConstraint(condition=models.Q(('effective_until__isnull', True), ('scope', 'user')), fields=('user',), name='uniq_open_user_policy_assignment')],
            },
        ),
        migrations.CreateModel(
            name='EmployeeShift',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('effective_from', models.DateField()),
                ('effective_until', models.DateField(blank=True, null=True)),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shift_assignments_made', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shift_assignments', to=settings.AUTH_USER_MODEL)),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='attendance.shift')),
            ],
            options={
                'ordering': ['-effective_from'],
                'indexes': [models.Index(fields=['user', 'effective_from'], name='attendance__user_id_152afc_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'effective_from'), name='uniq_employee_shift_start'), models.UniqueConstraint(condition=models.Q(('effective_until__isnull', True)), fields=('user',), name='uniq_open_employee_shift')],
            },
        ),
        migrations.CreateModel(
            name='WFHRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('reason', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', max_length=12)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_note', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wfh_requests_reviewed', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wfh_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-start_date'],
                'indexes': [models.Index(fields=['user', 'start_date', 'end_date'], name='attendance__user_id_739713_idx'), models.Index(fields=['status'], name='attendance__status_f71924_idx')],
            },
        ),
    ]
