# Generated by Django 5.2.16 on 2026-08-04 07:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_seed_global_policy'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancepolicy',
            name='half_day_after_time',
            field=models.TimeField(blank=True, default=datetime.time(13, 0), help_text='Check-in at or after this is Half Day regardless of hours worked. Leave empty to disable the arrival-based half-day rule.', null=True),
        ),
        migrations.AddField(
            model_name='attendancepolicy',
            name='late_after_time',
            field=models.TimeField(blank=True, default=datetime.time(11, 45), help_text='Check-in at or before this is Present; after it is Late. Leave empty to use office_start_time + grace_minutes instead.', null=True),
        ),
        migrations.AlterField(
            model_name='attendancepolicy',
            name='grace_minutes',
            field=models.PositiveSmallIntegerField(default=0, help_text='Legacy grace window. Only consulted when late_after_time is empty.'),
        ),
    ]
