# Generated by Django 5.2.16 on 2026-08-04 08:51

import attendance.workforce.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0007_nif_arrival_policy_cutover'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceCorrectionRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('attendance_date', models.DateField()),
                ('requested_check_in', models.DateTimeField(blank=True, null=True)),
                ('requested_check_out', models.DateTimeField(blank=True, null=True)),
                ('requested_status', models.CharField(blank=True, default='', help_text="Optional explicit status. Empty means: derive it from the requested times under the employee's policy.", max_length=20)),
                ('reason', models.TextField()),
                ('attachment', models.FileField(blank=True, null=True, upload_to=attendance.workforce.models.correction_attachment_path)),
                ('remarks', models.CharField(blank=True, default='', max_length=255)),
                ('previous_check_in', models.DateTimeField(blank=True, null=True)),
                ('previous_check_out', models.DateTimeField(blank=True, null=True)),
                ('previous_status', models.CharField(blank=True, default='', max_length=20)),
                ('previous_source', models.CharField(blank=True, default='', max_length=20)),
                ('had_attendance_row', models.BooleanField(default=False, help_text='False means the correction created the row; reverting deletes it.')),
                ('status', models.CharField(choices=[('pending', 'Pending (Department Head)'), ('manager_approved', 'Pending (HR)'), ('hr_approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20)),
                ('manager_action_at', models.DateTimeField(blank=True, null=True)),
                ('manager_remarks', models.CharField(blank=True, default='', max_length=255)),
                ('hr_action_at', models.DateTimeField(blank=True, null=True)),
                ('hr_remarks', models.CharField(blank=True, default='', max_length=255)),
                ('rejection_reason', models.CharField(blank=True, default='', max_length=255)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('reverted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attendance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='correction_requests', to='attendance.attendance')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_corrections', to=settings.AUTH_USER_MODEL)),
                ('hr_actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_corrections_finalised', to=settings.AUTH_USER_MODEL)),
                ('manager', models.ForeignKey(blank=True, help_text="Resolved at submit time from the employee's department head.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_corrections_to_review', to=settings.AUTH_USER_MODEL)),
                ('rejected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_corrections_rejected', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-attendance_date', '-created_at'],
                'indexes': [models.Index(fields=['status', 'attendance_date'], name='attendance__status_380c31_idx'), models.Index(fields=['employee', 'attendance_date'], name='attendance__employe_3d7f1d_idx'), models.Index(fields=['manager', 'status'], name='attendance__manager_9723fb_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status__in', ['pending', 'manager_approved'])), fields=('employee', 'attendance_date'), name='uniq_open_attendance_correction'), models.CheckConstraint(condition=models.Q(('requested_check_in__isnull', False), ('requested_check_out__isnull', False), models.Q(('requested_status', ''), _negated=True), _connector='OR'), name='attendance_correction_requests_something')],
            },
        ),
    ]
