# Generated by Django 5.2.16 on 2026-08-06 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_attendance_geofence'),
        ('attendance', '0008_attendance_correction_request'),
    ]

    operations = [
    ]
