# Generated by Django 5.2.16 on 2026-10-04 12:33

import attendance.workforce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0011_phase_a_organization_required'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancecorrectionrequest',
            name='attachment',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to=attendance.workforce.models.correction_attachment_path),
        ),
    ]
