# Generated by Django 5.2.17 on 2026-10-06 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0014_phase_b_organization_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='check_in_location_source',
            field=models.CharField(blank=True, choices=[('gps', 'Device GPS'), ('network', 'Wi-Fi / cell network'), ('ip', 'IP address lookup'), ('unknown', 'Not reported')], default='', max_length=10),
        ),
        migrations.AddField(
            model_name='attendance',
            name='check_in_user_agent',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AddField(
            model_name='attendance',
            name='check_out_location_source',
            field=models.CharField(blank=True, choices=[('gps', 'Device GPS'), ('network', 'Wi-Fi / cell network'), ('ip', 'IP address lookup'), ('unknown', 'Not reported')], default='', max_length=10),
        ),
        migrations.AddField(
            model_name='attendance',
            name='check_out_user_agent',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
    ]
