# Generated by Django 5.2.17 on 2026-10-07 06:24

from django.db import migrations, models
from django.db.models import F


def backfill_sources(apps, schema_editor):
    """Each existing end of the day came from the row's own source.

    Before this migration a row had one source for both ends, so that is the
    truthful answer for history. Rows with a browser snapshot were web-app
    check-ins later overridden by a device (no mobile client existed).
    """
    Attendance = apps.get_model("attendance", "Attendance")
    manager = Attendance._base_manager
    manager.filter(check_in__isnull=False).update(check_in_source=F("source"))
    manager.filter(check_out__isnull=False).update(check_out_source=F("source"))
    manager.filter(browser_check_in__isnull=False).update(app_source="browser")


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0015_attendance_check_in_location_source_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='app_source',
            field=models.CharField(blank=True, choices=[('browser', 'Web app'), ('mobile', 'Mobile app'), ('biometric', 'Biometric device'), ('hr', 'HR entry')], db_default='', default='', max_length=20),
        ),
        migrations.AddField(
            model_name='attendance',
            name='check_in_source',
            field=models.CharField(blank=True, choices=[('browser', 'Web app'), ('mobile', 'Mobile app'), ('biometric', 'Biometric device'), ('hr', 'HR entry')], db_default='', default='', max_length=20),
        ),
        migrations.AddField(
            model_name='attendance',
            name='check_out_source',
            field=models.CharField(blank=True, choices=[('browser', 'Web app'), ('mobile', 'Mobile app'), ('biometric', 'Biometric device'), ('hr', 'HR entry')], db_default='', default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='source',
            field=models.CharField(choices=[('browser', 'Web app'), ('mobile', 'Mobile app'), ('biometric', 'Biometric device'), ('hr', 'HR entry')], default='browser', max_length=20),
        ),
        migrations.RunPython(backfill_sources, migrations.RunPython.noop),
    ]
