# Generated by Django 5.2.16 on 2026-08-31 10:35

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('leaves', '0017_merge_20260806_1728'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Competency',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.SlugField(max_length=40, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('ordering', models.PositiveIntegerField(default=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'competencies',
                'ordering': ['ordering', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Appraisal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('employee_name', models.CharField(blank=True, default='', max_length=150)),
                ('designation', models.CharField(blank=True, default='', max_length=120)),
                ('department_name', models.CharField(blank=True, default='', max_length=150)),
                ('supervisor_name', models.CharField(blank=True, default='', max_length=150)),
                ('status', models.CharField(choices=[('goal_setting', 'Goal Setting'), ('mid_year_review', 'Mid-Year Review'), ('self_assessment', 'Self Assessment'), ('supervisor_review', 'Supervisor Review'), ('review_committee', 'Review Committee'), ('final_review', 'Final Review'), ('development_plan', 'Development Plan'), ('training_plan', 'Training Plan'), ('closed', 'Closed')], db_index=True, default='goal_setting', max_length=24)),
                ('self_assessment', models.TextField(blank=True, default='')),
                ('supervisor_comments', models.TextField(blank=True, default='')),
                ('committee_comments', models.TextField(blank=True, default='')),
                ('final_summary', models.TextField(blank=True, default='')),
                ('promotion_recommended', models.BooleanField(blank=True, null=True)),
                ('promotion_rationale', models.TextField(blank=True, default='')),
                ('successor_for', models.CharField(blank=True, default='', help_text='A role this person is being developed towards, if any. Free text and human-entered; nothing computes it.', max_length=150)),
                ('goals_agreed_at', models.DateTimeField(blank=True, null=True)),
                ('mid_year_at', models.DateTimeField(blank=True, null=True)),
                ('self_assessed_at', models.DateTimeField(blank=True, null=True)),
                ('supervisor_reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('committee_reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('finalised_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('committee', models.ManyToManyField(blank=True, related_name='appraisals_on_committee', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appraisals', to='leaves.department')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appraisals', to=settings.AUTH_USER_MODEL)),
                ('supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appraisals_supervising', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', 'employee_name'],
            },
        ),
        migrations.CreateModel(
            name='AppraisalAuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('actor_name', models.CharField(blank=True, default='', max_length=150)),
                ('action', models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('goals_agreed', 'Goals agreed'), ('goal_changed', 'Goal changed'), ('mid_year_recorded', 'Mid-year review recorded'), ('self_assessed', 'Self assessment submitted'), ('supervisor_reviewed', 'Supervisor review recorded'), ('committee_reviewed', 'Committee review recorded'), ('finalised', 'Final review recorded'), ('development_planned', 'Development plan agreed'), ('training_planned', 'Training plan agreed'), ('returned', 'Returned to an earlier stage'), ('closed', 'Closed'), ('rated', 'Competency rated'), ('evidence_attached', 'Evidence attached')], max_length=32)),
                ('from_status', models.CharField(blank=True, default='', max_length=24)),
                ('to_status', models.CharField(blank=True, default='', max_length=24)),
                ('remarks', models.TextField(blank=True, default='')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appraisal_actions', to=settings.AUTH_USER_MODEL)),
                ('appraisal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_entries', to='appraisal.appraisal')),
            ],
            options={
                'verbose_name': 'appraisal audit entry',
                'verbose_name_plural': 'appraisal audit entries',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='AppraisalCycle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('closed', 'Closed')], db_index=True, default='draft', max_length=10)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('goal_setting_deadline', models.DateField(blank=True, null=True)),
                ('self_assessment_deadline', models.DateField(blank=True, null=True)),
                ('review_deadline', models.DateField(blank=True, null=True)),
                ('created_by_name', models.CharField(blank=True, default='', max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appraisal_cycles_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-period_start', 'name'],
            },
        ),
        migrations.AddField(
            model_name='appraisal',
            name='cycle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appraisals', to='appraisal.appraisalcycle'),
        ),
        migrations.CreateModel(
            name='CompetencyRating',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('competency_name', models.CharField(blank=True, default='', max_length=100)),
                ('level', models.CharField(choices=[('needs_development', 'Needs Development'), ('developing', 'Developing'), ('meets', 'Meets Expectations'), ('exceeds', 'Exceeds Expectations'), ('outstanding', 'Outstanding')], max_length=24)),
                ('comment', models.TextField(help_text='Why. A level without reasoning is a number in disguise.')),
                ('rated_by_role', models.CharField(choices=[('employee', 'Self assessment'), ('supervisor', 'Supervisor'), ('committee', 'Review committee')], max_length=12)),
                ('rated_by_name', models.CharField(blank=True, default='', max_length=150)),
                ('rated_at', models.DateTimeField(auto_now_add=True)),
                ('appraisal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competency_ratings', to='appraisal.appraisal')),
                ('competency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ratings', to='appraisal.competency')),
                ('rated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='competency_ratings_given', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['competency__ordering', 'rated_by_role'],
            },
        ),
        migrations.CreateModel(
            name='DevelopmentPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('area', models.CharField(help_text='The capability being developed.', max_length=150)),
                ('action', models.TextField(help_text='What will actually be done.')),
                ('support_required', models.TextField(blank=True, default='')),
                ('target_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('deferred', 'Deferred')], default='planned', max_length=12)),
                ('accountable_name', models.CharField(blank=True, default='', max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('accountable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='development_plans_accountable', to=settings.AUTH_USER_MODEL)),
                ('appraisal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='development_plans', to='appraisal.appraisal')),
                ('competency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='development_plans', to='appraisal.competency')),
            ],
            options={
                'ordering': ['target_date', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('objective', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('weight', models.PositiveSmallIntegerField(help_text='Percentage weight. All goals on an appraisal must total 100.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('target', models.TextField(blank=True, default='', help_text="What success looks like, in the employee's and supervisor's own words.")),
                ('achievement', models.TextField(blank=True, default='', help_text='What actually happened. Written by the employee, discussed with the supervisor.')),
                ('progress_percent', models.PositiveSmallIntegerField(default=0, help_text="The employee's own assessment of progress. Not computed.", validators=[django.core.validators.MaxValueValidator(100)])),
                ('due_date', models.DateField(blank=True, null=True)),
                ('owner_name', models.CharField(blank=True, default='', max_length=150)),
                ('position', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('appraisal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='appraisal.appraisal')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appraisal_goals_owned', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['position', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='EvidenceReference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source', models.CharField(db_index=True, default='task', max_length=32)),
                ('contract_version', models.CharField(blank=True, default='', max_length=12)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('period_type', models.CharField(default='annual', max_length=12)),
                ('metrics', models.JSONField(blank=True, default=list)),
                ('disclaimer', models.TextField(blank=True, default='')),
                ('note', models.TextField(blank=True, default='', help_text="Why this evidence was attached, in the attacher's words.")),
                ('captured_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('attached_by_name', models.CharField(blank=True, default='', max_length=150)),
                ('appraisal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence_references', to='appraisal.appraisal')),
                ('attached_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appraisal_evidence_attached', to=settings.AUTH_USER_MODEL)),
                ('goal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evidence_references', to='appraisal.goal')),
            ],
            options={
                'verbose_name': 'evidence reference',
                'ordering': ['-captured_at'],
            },
        ),
        migrations.CreateModel(
            name='TrainingPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('justification', models.TextField(blank=True, default='')),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=8)),
                ('status', models.CharField(choices=[('identified', 'Identified'), ('approved', 'Approved'), ('scheduled', 'Scheduled'), ('completed', 'Completed'), ('declined', 'Declined')], default='identified', max_length=12)),
                ('target_period', models.CharField(blank=True, default='', help_text='When it is wanted — a quarter or a month, not a fixed date.', max_length=100)),
                ('decided_by_name', models.CharField(blank=True, default='', max_length=150)),
                ('decision_note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('appraisal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_plans', to='appraisal.appraisal')),
                ('competency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='training_plans', to='appraisal.competency')),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='training_plans_decided', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-priority', 'created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='appraisal',
            index=models.Index(fields=['cycle', 'status'], name='appraisal_cycle_idx'),
        ),
        migrations.AddIndex(
            model_name='appraisal',
            index=models.Index(fields=['supervisor', 'status'], name='appraisal_supervisor_idx'),
        ),
        migrations.AddConstraint(
            model_name='appraisal',
            constraint=models.UniqueConstraint(fields=('cycle', 'employee'), name='appraisal_one_per_cycle'),
        ),
        migrations.AddConstraint(
            model_name='competencyrating',
            constraint=models.UniqueConstraint(fields=('appraisal', 'competency', 'rated_by_role'), name='appraisal_one_rating_per_role'),
        ),
    ]
