# Generated by Django 5.2.12 on 2026-04-29 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='handover_notes',
            field=models.TextField(blank=True, default=''),
        ),
    ]
