# Generated by Django 6.0.6 on 2026-07-08 06:07

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0003_leave_handover_notes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(unique=True)),
                ('name', models.CharField(max_length=150)),
                ('holiday_type', models.CharField(choices=[('public', 'Public'), ('optional', 'Optional'), ('religious', 'Religious')], default='public', max_length=20)),
                ('description', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='LeaveType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('default_days_per_year', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6)),
                ('is_paid', models.BooleanField(default=True)),
                ('allow_half_day', models.BooleanField(default=True)),
                ('allow_carry_forward', models.BooleanField(default=False)),
                ('max_carry_forward_days', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('requires_document', models.BooleanField(default=False)),
                ('min_notice_days', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('display_color', models.CharField(default='#6B7280', max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('code', models.CharField(max_length=30, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('head', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='departments_headed', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='leaves.department')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='LeavePolicy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(blank=True, choices=[('maker', 'Maker'), ('checker', 'Checker'), ('approver', 'Approver'), ('admin', 'Admin')], max_length=20, null=True)),
                ('days_per_year', models.DecimalField(decimal_places=2, max_digits=6)),
                ('effective_from', models.DateField()),
                ('effective_until', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leave_policies_created', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leave_policies', to='leaves.department')),
                ('leave_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='policies', to='leaves.leavetype')),
            ],
            options={
                'ordering': ['-effective_from'],
                'constraints': [models.UniqueConstraint(fields=('leave_type', 'department', 'role', 'effective_from'), name='uniq_policy_scope_effective')],
            },
        ),
        migrations.CreateModel(
            name='LeaveDayRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('day_portion', models.CharField(choices=[('full', 'Full Day'), ('first_half', 'First Half'), ('second_half', 'Second Half')], default='full', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('is_holiday', models.BooleanField(default=False)),
                ('is_weekend', models.BooleanField(default=False)),
                ('week_number', models.PositiveSmallIntegerField()),
                ('month', models.PositiveSmallIntegerField()),
                ('year', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('leave_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='day_records', to='leaves.leave')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_day_records', to=settings.AUTH_USER_MODEL)),
                ('leave_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='day_records', to='leaves.leavetype')),
            ],
            options={
                'ordering': ['date'],
                'indexes': [models.Index(fields=['user', 'year', 'month'], name='leaves_leav_user_id_8eace8_idx'), models.Index(fields=['user', 'year', 'week_number'], name='leaves_leav_user_id_43f6c4_idx'), models.Index(fields=['date', 'status'], name='leaves_leav_date_97c2b3_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'date', 'day_portion', 'leave_request'), name='uniq_leave_day_booking')],
            },
        ),
        migrations.CreateModel(
            name='EnterpriseLeaveBalance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('year', models.PositiveIntegerField()),
                ('entitled_days', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=7)),
                ('carried_forward_days', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=7)),
                ('used_days', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=7)),
                ('pending_days', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=7)),
                ('encashed_days', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=7)),
                ('forfeited_days', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=7)),
                ('last_recomputed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enterprise_balances', to=settings.AUTH_USER_MODEL)),
                ('leave_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balances', to='leaves.leavetype')),
            ],
            options={
                'ordering': ['-year', 'leave_type'],
                'constraints': [models.UniqueConstraint(fields=('user', 'leave_type', 'year'), name='uniq_enterprise_balance')],
            },
        ),
        migrations.CreateModel(
            name='MonthlyLeaveSummary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('year', models.PositiveIntegerField()),
                ('month', models.PositiveSmallIntegerField()),
                ('total_leave_days', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6)),
                ('by_type', models.JSONField(blank=True, default=dict)),
                ('approved_days', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6)),
                ('pending_days', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6)),
                ('working_days', models.PositiveSmallIntegerField(default=0)),
                ('attendance_percentage', models.DecimalField(decimal_places=2, default=Decimal('100.00'), max_digits=5)),
                ('carry_forward_earned', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6)),
                ('last_recomputed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_summaries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-year', '-month'],
                'constraints': [models.UniqueConstraint(fields=('user', 'year', 'month'), name='uniq_monthly_summary')],
            },
        ),
        migrations.CreateModel(
            name='WeeklyLeaveSummary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('year', models.PositiveIntegerField()),
                ('week_number', models.PositiveSmallIntegerField()),
                ('week_start_date', models.DateField()),
                ('week_end_date', models.DateField()),
                ('total_leave_days', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6)),
                ('by_type', models.JSONField(blank=True, default=dict)),
                ('approved_days', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6)),
                ('pending_days', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6)),
                ('rejected_days', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6)),
                ('working_days', models.PositiveSmallIntegerField(default=0)),
                ('attendance_percentage', models.DecimalField(decimal_places=2, default=Decimal('100.00'), max_digits=5)),
                ('last_recomputed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_summaries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-year', '-week_number'],
                'constraints': [models.UniqueConstraint(fields=('user', 'year', 'week_number'), name='uniq_weekly_summary')],
            },
        ),
    ]
