# Generated by Django 6.0.6 on 2026-07-08 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0005_seed_leave_types_and_holidays'),
    ]

    operations = [
        migrations.AddField(
            model_name='enterpriseleavebalance',
            name='locked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leave',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leave',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
