# Generated by Django 6.0.6 on 2026-07-08 07:07

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0006_enterpriseleavebalance_locked_at_leave_deleted_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enterpriseleavebalance',
            name='adjustment_days',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=7),
        ),
    ]
