# Generated by Django 5.2.16 on 2026-07-13 07:00

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0011_backfill_simple_balances'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompensatoryLedger',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entry_type', models.CharField(choices=[('earn', 'Earned'), ('use', 'Used')], max_length=8)),
                ('days', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=6)),
                ('source', models.CharField(choices=[('attendance', 'Attendance (weekend/holiday work)'), ('hr_grant', 'HR manual grant'), ('leave_use', 'Comp leave taken')], max_length=12)),
                ('status', models.CharField(choices=[('pending', 'Pending confirmation'), ('confirmed', 'Confirmed')], default='pending', max_length=12)),
                ('source_date', models.DateField(blank=True, help_text='Weekend/holiday worked (for earn entries).', null=True)),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comp_approved', to=settings.AUTH_USER_MODEL)),
                ('leave', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comp_entries', to='leaves.leave')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comp_ledger', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'entry_type', 'status'], name='leaves_comp_user_id_9580a4_idx')],
            },
        ),
        migrations.CreateModel(
            name='EntitlementRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('A', 'Category A — Permanent (>3 yrs)'), ('B', 'Category B — Permanent (1–3 yrs)'), ('C', 'Category C — Post-Probation / Permanent (<1 yr)'), ('D', 'Category D — Intern / Volunteer'), ('PROBATION', 'Probation (<3 mo)')], max_length=12)),
                ('entitlement_days', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6)),
                ('is_working_day_based', models.BooleanField(default=True)),
                ('applicable', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('leave_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entitlement_rules', to='leaves.leavetype')),
            ],
            options={
                'ordering': ['category', 'leave_type__code'],
                'constraints': [models.UniqueConstraint(fields=('category', 'leave_type'), name='uniq_entitlement_category_type')],
            },
        ),
    ]
