
# Generated by Django 5.2.16 on 2026-08-04 06:33

from django.conf import settings
from django.db import migrations, models


def drop_duplicate_earns(apps, schema_editor):
    """Collapse pre-existing duplicates so AddConstraint cannot fail.

    Expected to be a no-op: nothing has ever written Source.ATTENDANCE — that
    is the gap this phase closes. Present so the migration is also safe on a
    database where such rows were created by hand.
    """
    CompensatoryLedger = apps.get_model("leaves", "CompensatoryLedger")
    seen, duplicates = set(), []
    rows = (CompensatoryLedger.objects
            .filter(source="attendance", entry_type="earn", source_date__isnull=False)
            # Confirmed entries win over pending ones; then oldest wins.
            .order_by("status", "created_at")
            .values_list("id", "user_id", "source_date"))
    for pk, user_id, source_date in rows:
        key = (user_id, source_date)
        if key in seen:
            duplicates.append(pk)
        else:
            seen.add(key)
    if duplicates:
        CompensatoryLedger.objects.filter(id__in=duplicates).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0015_alter_leave_leave_type_alter_leavebalance_leave_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(drop_duplicate_earns, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='compensatoryledger',
            constraint=models.UniqueConstraint(condition=models.Q(('source', 'attendance'), ('source_date__isnull', False)), fields=('user', 'source_date', 'entry_type'), name='uniq_attendance_comp_earn_per_day'),
        ),
    ]
