# Generated by Django 5.2.16 on 2026-07-27 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0015_alter_leave_leave_type_alter_leavebalance_leave_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='day_portion',
            field=models.CharField(choices=[('full', 'Full Day'), ('first_half', 'First Half'), ('second_half', 'Second Half')], default='full', max_length=20),
        ),
    ]
