# Generated by Django 5.2.16 on 2026-08-06 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0016_comp_attendance_unique'),
        ('leaves', '0016_leave_day_portion'),
    ]

    operations = [
    ]
