# Generated by Django 5.2.16 on 2026-09-07 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0017_merge_20260806_1728'),
    ]

    operations = [
        migrations.AddField(
            model_name='entitlementrule',
            name='by_arrangement',
            field=models.BooleanField(default=False, help_text='Granted case-by-case under organisation policy rather than as a fixed yearly allocation.'),
        ),
        migrations.AlterField(
            model_name='entitlementrule',
            name='category',
            field=models.CharField(choices=[('A', 'Category A — Permanent (>3 yrs)'), ('B', 'Category B — Permanent (1–3 yrs)'), ('C', 'Category C — Post-Probation / Permanent (<1 yr)'), ('D', 'Category D — Intern'), ('E', 'Category E — Volunteer'), ('PROBATION', 'Probation (<3 mo)')], max_length=12),
        ),
    ]
