# Generated by Django 5.2.16 on 2026-09-09 08:19

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0019_policy_intern_volunteer_split'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(db_index=True)),
                ('name', models.CharField(max_length=150)),
                ('name_np', models.CharField(blank=True, default='', help_text='Devanagari name, shown on the calendar. Falls back to `name`.', max_length=150)),
                ('event_type', models.CharField(choices=[('festival', 'Festival'), ('national', 'National day'), ('religious', 'Religious observance'), ('jayanti', 'Jayanti'), ('observance', 'Observance')], default='festival', max_length=20)),
                ('tithi', models.CharField(blank=True, default='', max_length=80)),
                ('detail', models.TextField(blank=True, default='')),
                ('is_public_holiday', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['date', '-is_public_holiday', 'name'],
                'indexes': [models.Index(fields=['date', 'is_active'], name='leaves_cale_date_605472_idx')],
                'constraints': [models.UniqueConstraint(fields=('date', 'name'), name='uniq_calendar_event_date_name')],
            },
        ),
    ]
