# Generated by Django 5.2.16 on 2026-08-13 07:23

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('leaves', '0017_merge_20260806_1728'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MinuteNumberSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(unique=True)),
                ('last_value', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'minute number sequence',
            },
        ),
        migrations.CreateModel(
            name='MinutePriority',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=40, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('ordering', models.PositiveIntegerField(default=100)),
                ('is_active', models.BooleanField(default=True)),
                ('rank', models.PositiveIntegerField(default=0)),
                ('sla_days', models.PositiveIntegerField(default=5, help_text='Working days allowed per approval step at this priority.')),
            ],
            options={
                'ordering': ['rank', 'ordering'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MinuteRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=40, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('ordering', models.PositiveIntegerField(default=100)),
                ('is_active', models.BooleanField(default=True)),
                ('rank', models.PositiveIntegerField(default=0, help_text="Hierarchy position. A chain's ranks may not decrease.")),
                ('is_final_approval', models.BooleanField(default=False, help_text='Completing a step with this role approves the minute. Exactly one role should carry this.')),
                ('requires_remarks', models.BooleanField(default=False, help_text="Force a comment when acting on this role's step.")),
            ],
            options={
                'ordering': ['rank', 'ordering'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MinuteSubType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=40, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('ordering', models.PositiveIntegerField(default=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['minute_type__ordering', 'ordering', 'name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MinuteType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=40, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('ordering', models.PositiveIntegerField(default=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['ordering', 'name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Minute',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('minute_number', models.CharField(db_index=True, max_length=32, unique=True)),
                ('reference_number', models.CharField(blank=True, help_text='External or board reference, if the minute cites one.', max_length=64)),
                ('subject', models.CharField(max_length=255)),
                ('minute_date', models.DateField(default=django.utils.timezone.localdate)),
                ('department_name', models.CharField(blank=True, help_text='Snapshot, so a renamed or deleted department does not rewrite history on an archived minute.', max_length=120)),
                ('background', models.TextField(blank=True, help_text='Sanitized HTML. Why the matter came to the meeting.')),
                ('analysis', models.TextField(blank=True, help_text='Sanitized HTML. Discussion and analysis.')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('draft_for_review', 'Draft For Review'), ('under_review', 'Under Review'), ('recommended', 'Recommended'), ('supported', 'Supported'), ('approved', 'Approved'), ('archived', 'Archived'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], db_index=True, default='draft', max_length=24)),
                ('acknowledgement_opened_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('cc_users', models.ManyToManyField(blank=True, related_name='minutes_copied', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(help_text="The initiator. This is the 'From' on the header.", on_delete=django.db.models.deletion.CASCADE, related_name='minutes_initiated', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='minutes', to='leaves.department')),
                ('to_users', models.ManyToManyField(blank=True, related_name='minutes_addressed', to=settings.AUTH_USER_MODEL)),
                ('priority', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='minutes', to='minutes.minutepriority')),
                ('minute_sub_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='minutes', to='minutes.minutesubtype')),
                ('minute_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='minutes', to='minutes.minutetype')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MinuteAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='minutes/attachments/%Y/%m/')),
                ('original_name', models.CharField(blank=True, max_length=255)),
                ('content_type', models.CharField(blank=True, max_length=100)),
                ('size', models.PositiveIntegerField(default=0)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('minute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='minutes.minute')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='minute_attachments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='MinuteDecision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sequence', models.PositiveIntegerField(default=1)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('owner_name', models.CharField(blank=True, max_length=150)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('deferred', 'Deferred'), ('completed', 'Completed')], db_index=True, default='pending', max_length=16)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('minute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decisions', to='minutes.minute')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='minute_decisions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['sequence', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='MinuteActionItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sequence', models.PositiveIntegerField(default=1)),
                ('task', models.CharField(max_length=255)),
                ('owner_name', models.CharField(blank=True, max_length=150)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('closed', 'Closed')], db_index=True, default='pending', max_length=16)),
                ('remarks', models.TextField(blank=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('minute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_items', to='minutes.minute')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='minute_action_items', to=settings.AUTH_USER_MODEL)),
                ('decision', models.ForeignKey(blank=True, help_text='The decision this task implements, when it came from one.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='action_items', to='minutes.minutedecision')),
            ],
            options={
                'ordering': ['sequence', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='MinuteInvolvement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('assignment_type', models.CharField(choices=[('action_required', 'Action Required'), ('review_required', 'Review Required'), ('information_only', 'Information Only')], db_index=True, default='information_only', max_length=20)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('acted_at', models.DateTimeField(blank=True, null=True)),
                ('minute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='involvements', to='minutes.minute')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='minute_involvements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['assignment_type', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='MinuteParticipant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_name', models.CharField(blank=True, max_length=150)),
                ('designation', models.CharField(blank=True, max_length=120)),
                ('department_label', models.CharField(blank=True, max_length=120)),
                ('participant_role', models.CharField(choices=[('chair', 'Meeting Chair'), ('recorder', 'Minute Recorder'), ('participant', 'Participant'), ('invitee', 'Invitee')], default='participant', max_length=16)),
                ('ack_status', models.CharField(choices=[('pending', 'Pending Acknowledgement'), ('acknowledged', 'Acknowledged'), ('declined', 'Declined Acknowledgement')], db_index=True, default='pending', max_length=16)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True)),
                ('reminded_at', models.DateTimeField(blank=True, help_text='Last acknowledgement reminder sent.', null=True)),
                ('minute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='minutes.minute')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='minute_participations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['participant_role', 'user_name'],
            },
        ),
        migrations.AddField(
            model_name='minutesubtype',
            name='minute_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_types', to='minutes.minutetype'),
        ),
        migrations.CreateModel(
            name='MinuteWorkflowStep',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sequence', models.PositiveIntegerField()),
                ('assignee_name', models.CharField(blank=True, max_length=150)),
                ('designation', models.CharField(blank=True, max_length=120)),
                ('department_label', models.CharField(blank=True, max_length=120)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('completed', 'Completed'), ('rejected', 'Rejected'), ('skipped', 'Skipped')], db_index=True, default='pending', max_length=16)),
                ('activated_at', models.DateTimeField(blank=True, help_text="When this step became the active one - the clock the SLA runs against. Distinct from the minute's submission time, which would make step 4 look as old as step 1.", null=True)),
                ('acted_at', models.DateTimeField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True)),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='minute_steps', to=settings.AUTH_USER_MODEL)),
                ('minute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_steps', to='minutes.minute')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='steps', to='minutes.minuterole')),
            ],
            options={
                'ordering': ['sequence'],
            },
        ),
        migrations.CreateModel(
            name='MinuteAuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('actor_name', models.CharField(blank=True, max_length=150)),
                ('action', models.CharField(choices=[('created', 'Created'), ('updated', 'Edited'), ('submitted', 'Submitted'), ('reviewed', 'Reviewed'), ('recommended', 'Recommended'), ('supported', 'Supported'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn'), ('archived', 'Archived'), ('matrix_changed', 'Workflow changed'), ('decision_changed', 'Decision updated'), ('action_changed', 'Action item updated'), ('participants_changed', 'Participants updated'), ('acknowledged', 'Acknowledged'), ('ack_declined', 'Acknowledgement declined'), ('ack_reminded', 'Acknowledgement reminder sent'), ('exported', 'Exported')], db_index=True, max_length=24)),
                ('remarks', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=512)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='minute_audit_entries', to=settings.AUTH_USER_MODEL)),
                ('minute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_entries', to='minutes.minute')),
            ],
            options={
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['minute', 'created_at'], name='minutes_min_minute__004813_idx'), models.Index(fields=['action', '-created_at'], name='minutes_min_action_386e87_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='minutedecision',
            index=models.Index(fields=['minute', 'sequence'], name='minutes_min_minute__91269c_idx'),
        ),
        migrations.AddIndex(
            model_name='minutedecision',
            index=models.Index(fields=['owner', 'status'], name='minutes_min_owner_i_a75255_idx'),
        ),
        migrations.AddIndex(
            model_name='minutedecision',
            index=models.Index(fields=['status', 'due_date'], name='minutes_min_status_8e119a_idx'),
        ),
        migrations.AddIndex(
            model_name='minuteactionitem',
            index=models.Index(fields=['minute', 'sequence'], name='minutes_min_minute__e40c88_idx'),
        ),
        migrations.AddIndex(
            model_name='minuteactionitem',
            index=models.Index(fields=['owner', 'status'], name='minutes_min_owner_i_cac065_idx'),
        ),
        migrations.AddIndex(
            model_name='minuteactionitem',
            index=models.Index(fields=['status', 'deadline'], name='minutes_min_status_42f32a_idx'),
        ),
        migrations.AddIndex(
            model_name='minuteinvolvement',
            index=models.Index(fields=['user', 'assignment_type'], name='minutes_min_user_id_35dabc_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='minuteinvolvement',
            unique_together={('minute', 'user')},
        ),
        migrations.AddIndex(
            model_name='minuteparticipant',
            index=models.Index(fields=['user', 'ack_status'], name='minutes_min_user_id_58e634_idx'),
        ),
        migrations.AddIndex(
            model_name='minuteparticipant',
            index=models.Index(fields=['minute', 'ack_status'], name='minutes_min_minute__536695_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='minuteparticipant',
            unique_together={('minute', 'user')},
        ),
        migrations.AddIndex(
            model_name='minute',
            index=models.Index(fields=['status', '-created_at'], name='minutes_min_status_513674_idx'),
        ),
        migrations.AddIndex(
            model_name='minute',
            index=models.Index(fields=['created_by', 'status'], name='minutes_min_created_0200b8_idx'),
        ),
        migrations.AddIndex(
            model_name='minute',
            index=models.Index(fields=['department', 'status'], name='minutes_min_departm_9cbe8a_idx'),
        ),
        migrations.AddIndex(
            model_name='minuteworkflowstep',
            index=models.Index(fields=['assignee', 'status'], name='minutes_min_assigne_5bd324_idx'),
        ),
        migrations.AddIndex(
            model_name='minuteworkflowstep',
            index=models.Index(fields=['minute', 'sequence'], name='minutes_min_minute__480dc2_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='minuteworkflowstep',
            unique_together={('minute', 'sequence')},
        ),
    ]
