# Generated by Django 5.2.16 on 2026-08-13 09:01

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_references(apps, schema_editor):
    """
    Give every existing decision and action item a tracking number before the unique
    constraint goes on (Phase 42 items 5, 6).

    Numbered by CREATION ORDER within each calendar year, so the references read in the
    order the records were actually made rather than in whatever order the rows happen
    to come back. The per-year counter rows are advanced to match, so the next reference
    the application allocates continues the sequence instead of colliding with a
    backfilled one.

    Historical models only - and note they carry FIELDS but not METHODS, so nothing here
    may call a model helper.
    """
    MinuteDecision = apps.get_model("minutes", "MinuteDecision")
    MinuteActionItem = apps.get_model("minutes", "MinuteActionItem")
    MinuteChildSequence = apps.get_model("minutes", "MinuteChildSequence")

    for kind, model in (("DEC", MinuteDecision), ("ACT", MinuteActionItem)):
        counters = {}
        for row in model.objects.order_by("created_at", "id"):
            year = row.created_at.year
            counters[year] = counters.get(year, 0) + 1
            row.reference = f"{kind}-{year}-{counters[year]:03d}"
            row.save(update_fields=["reference"])
        for year, last in counters.items():
            sequence, _ = MinuteChildSequence.objects.get_or_create(
                kind=kind, year=year, defaults={"last_value": 0})
            if sequence.last_value < last:
                sequence.last_value = last
                sequence.save(update_fields=["last_value"])


def unbackfill(apps, schema_editor):
    """Reversible: clearing the references is safe once the constraint is gone."""
    for name in ("MinuteDecision", "MinuteActionItem"):
        apps.get_model("minutes", name).objects.update(reference="")


class Migration(migrations.Migration):

    dependencies = [
        ('minutes', '0002_seed_taxonomy'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MinuteChildSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('DEC', 'Decision'), ('ACT', 'Action item')], max_length=4)),
                ('year', models.PositiveIntegerField()),
                ('last_value', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'minute child sequence',
            },
        ),
        migrations.AddField(
            model_name='minute',
            name='meeting_date',
            field=models.DateField(blank=True, help_text='When the meeting was held.', null=True),
        ),
        migrations.AddField(
            model_name='minute',
            name='meeting_end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='minute',
            name='meeting_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='minute',
            name='meeting_title',
            field=models.CharField(blank=True, help_text="The meeting's own title, if it differs from the minute subject.", max_length=255),
        ),
        migrations.AddField(
            model_name='minute',
            name='venue',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='minuteactionitem',
            name='completion_percent',
            field=models.PositiveSmallIntegerField(default=0, help_text='Progress 0-100. Kept consistent with `status`: completing a task sets it to 100 and reopening a completed one clears it back off 100.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='minuteactionitem',
            name='reference',
            # Added non-unique; backfilled below; the unique constraint is applied
            # afterwards. Adding it unique in one step fails on any database that
            # already holds rows: they would all take the implicit '' default and
            # collide on the very first duplicate.
            #
            # NOT db_index=True here. On PostgreSQL an indexed varchar column also
            # gets a companion `..._like` index (varchar_pattern_ops), and AddField
            # DEFERS both CREATE INDEX statements to the end of the migration. The
            # AlterField further down adds unique=True, which emits its own `_like`
            # index immediately - so the deferred one then collides with it:
            #   relation "minutes_minuteactionitem_reference_50fc12d3_like"
            #   already exists
            # The index is not lost: unique=True below creates the unique btree
            # constraint and the `_like` index. SQLite emits no `_like` index at
            # all, which is why this only ever failed on Postgres/CI.
            field=models.CharField(blank=True, max_length=24),
        ),
        migrations.AddField(
            model_name='minuteattachment',
            name='is_current',
            field=models.BooleanField(db_index=True, default=True, help_text='False once a newer version supersedes this row.'),
        ),
        migrations.AddField(
            model_name='minuteattachment',
            name='replaces',
            field=models.ForeignKey(blank=True, help_text='The version this one replaces. SET_NULL so deleting an old version does not cascade away the current one.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='superseded_by', to='minutes.minuteattachment'),
        ),
        migrations.AddField(
            model_name='minuteattachment',
            name='version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='minutedecision',
            name='reference',
            # Same as minuteactionitem.reference above - no db_index here, or the
            # deferred `_like` index collides with the one unique=True creates.
            field=models.CharField(blank=True, max_length=24),
        ),
        migrations.AddField(
            model_name='minuteparticipant',
            name='attendance',
            field=models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('excused', 'Excused')], db_index=True, default='present', max_length=16),
        ),
        migrations.AddIndex(
            model_name='minuteattachment',
            index=models.Index(fields=['minute', 'is_current'], name='minutes_min_minute__cd226a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='minutechildsequence',
            unique_together={('kind', 'year')},
        ),
        # Backfill, THEN constrain. Order matters: see backfill_references.
        migrations.RunPython(backfill_references, unbackfill),
        migrations.AlterField(
            model_name='minutedecision',
            name='reference',
            field=models.CharField(blank=True, max_length=24, unique=True),
        ),
        migrations.AlterField(
            model_name='minuteactionitem',
            name='reference',
            field=models.CharField(blank=True, max_length=24, unique=True),
        ),
    ]
