# Generated by Django 5.2.16 on 2026-08-13 09:57

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


# The four meeting types Phase 43 names, in that order.
#
# Existing rows are RENAMED rather than replaced: `code` is the identity a minute points
# at, so changing only the label leaves every existing minute intact while the dropdown
# reads the way the brief asks. "Committee Meeting" is new. The pre-existing extras stay
# active - deactivating types nobody asked to remove would hide them from the dropdown
# for no stated reason - but they sort after the four.
MEETING_TYPES = [
    ("board-meeting", "Board Meeting", 10),
    ("management-committee", "Management Meeting", 20),
    ("departmental", "Department Meeting", 30),
    ("committee-meeting", "Committee Meeting", 40),
]

EXTRA_ORDERING = [
    ("audit-committee", 50),
    ("governance", 60),
    ("general", 70),
]

# Sub types for the newly added Committee Meeting.
COMMITTEE_SUB_TYPES = [
    ("committee-audit", "Audit Committee", 10),
    ("committee-risk", "Risk Committee", 20),
    ("committee-remuneration", "Remuneration Committee", 30),
    ("committee-other", "Other Committee", 40),
]


def align_meeting_types(apps, schema_editor):
    """
    Bring the meeting-type taxonomy in line with Phase 43 without disturbing data.

    Historical models only, and they carry FIELDS but not METHODS - nothing here may call
    a model helper.
    """
    MinuteType = apps.get_model("minutes", "MinuteType")
    MinuteSubType = apps.get_model("minutes", "MinuteSubType")

    for code, name, ordering in MEETING_TYPES:
        existing = MinuteType.objects.filter(code=code).first()
        if existing is None:
            existing = MinuteType.objects.create(
                code=code, name=name, ordering=ordering, is_active=True)
        else:
            existing.name = name
            existing.ordering = ordering
            existing.is_active = True
            existing.save(update_fields=["name", "ordering", "is_active"])

        if code == "committee-meeting":
            for sub_code, sub_name, sub_ordering in COMMITTEE_SUB_TYPES:
                MinuteSubType.objects.get_or_create(
                    code=sub_code,
                    defaults={"name": sub_name, "ordering": sub_ordering,
                              "minute_type": existing})

    for code, ordering in EXTRA_ORDERING:
        MinuteType.objects.filter(code=code).update(ordering=ordering)


def unalign(apps, schema_editor):
    """
    Restore the previous labels. Deliberately does NOT delete Committee Meeting: a
    minute may already reference it, and PROTECT would make the reverse fail.
    """
    MinuteType = apps.get_model("minutes", "MinuteType")
    for code, name, ordering in (("management-committee", "Management Committee", 20),
                                 ("departmental", "Departmental Meeting", 50)):
        MinuteType.objects.filter(code=code).update(name=name, ordering=ordering)


class Migration(migrations.Migration):

    dependencies = [
        ('minutes', '0003_minutechildsequence_minute_meeting_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MinuteAgendaItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('number', models.PositiveIntegerField(help_text='Agenda item number as printed on the agenda paper.')),
                ('title', models.CharField(max_length=255)),
                ('presenter_name', models.CharField(blank=True, max_length=150)),
                ('presenter_designation', models.CharField(blank=True, max_length=120)),
                ('discussion', models.TextField(blank=True, help_text='Sanitized HTML. The minutes recorded under this agenda item.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('minute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agenda_items', to='minutes.minute')),
                ('presenter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='minute_agenda_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['number', 'created_at'],
            },
        ),
        migrations.AddField(
            model_name='minutedecision',
            name='agenda_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decisions', to='minutes.minuteagendaitem'),
        ),
        migrations.AddIndex(
            model_name='minuteagendaitem',
            index=models.Index(fields=['minute', 'number'], name='minutes_min_minute__765506_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='minuteagendaitem',
            unique_together={('minute', 'number')},
        ),
        migrations.RunPython(align_meeting_types, unalign),
    ]
