# Generated by Django 5.2.16 on 2026-08-13 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minutes', '0004_minuteagendaitem_minutedecision_agenda_item_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='minuteauditlog',
            name='action',
            field=models.CharField(choices=[('created', 'Created'), ('updated', 'Edited'), ('submitted', 'Submitted'), ('reviewed', 'Reviewed'), ('recommended', 'Recommended'), ('supported', 'Supported'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn'), ('archived', 'Archived'), ('matrix_changed', 'Workflow changed'), ('agenda_changed', 'Agenda updated'), ('decision_changed', 'Decision updated'), ('action_changed', 'Action item updated'), ('participants_changed', 'Participants updated'), ('acknowledged', 'Acknowledged'), ('ack_declined', 'Acknowledgement declined'), ('ack_reminded', 'Acknowledgement reminder sent'), ('exported', 'Exported')], db_index=True, max_length=24),
        ),
    ]
