# Generated by Django 5.2.16 on 2026-08-13 10:33

from django.conf import settings
from django.db import migrations, models


# The seven meeting types Phase 44.5 names, in that order.
#
# NOTE THE REVERSAL: Phase 43 asked for "Management Meeting" and this phase asks for
# "Management Committee" - the same row, renamed back. The later instruction wins, and
# because `code` is the identity a minute points at, both round trips left every existing
# minute untouched. That is exactly why the label is not the identity.
#
# ICT, HR and Procurement Committees are new. The generic "Committee Meeting" added in
# Phase 43 is DEACTIVATED rather than deleted: it is superseded by the three named
# committees, but a minute may already point at it and PROTECT would refuse the delete.
# Deactivating hides it from the dropdowns while leaving history intact.
MEETING_TYPES = [
    ("board-meeting", "Board Meeting", 10, []),
    ("management-committee", "Management Committee", 20, []),
    ("ict-committee", "ICT Committee", 30, [
        ("ict-infrastructure", "Infrastructure Review", 10),
        ("ict-security", "Information Security", 20),
        ("ict-procurement", "ICT Procurement", 30),
    ]),
    ("hr-committee", "HR Committee", 40, [
        ("hr-recruitment", "Recruitment", 10),
        ("hr-performance", "Performance Review", 20),
        ("hr-grievance", "Grievance", 30),
    ]),
    ("procurement-committee", "Procurement Committee", 50, [
        ("proc-tender", "Tender Evaluation", 10),
        ("proc-vendor", "Vendor Review", 20),
        ("proc-contract", "Contract Award", 30),
    ]),
    ("executive-meeting", "Executive Meeting", 60, [
        ("exec-regular", "Regular Executive", 10),
        ("exec-special", "Special Executive", 20),
    ]),
    ("departmental", "Department Meeting", 70, []),
]

# Superseded by the named committees above.
DEACTIVATE = ["committee-meeting"]

# Kept active but sorted last - nobody asked to remove them.
TRAILING = [("audit-committee", 80), ("governance", 90), ("general", 100)]


def align_governance_types(apps, schema_editor):
    """
    Bring the meeting-type taxonomy in line with Phase 44.5.

    Historical models only - they carry FIELDS but not METHODS, so nothing here may call
    a model helper.
    """
    MinuteType = apps.get_model("minutes", "MinuteType")
    MinuteSubType = apps.get_model("minutes", "MinuteSubType")

    for code, name, ordering, sub_types in MEETING_TYPES:
        row = MinuteType.objects.filter(code=code).first()
        if row is None:
            row = MinuteType.objects.create(
                code=code, name=name, ordering=ordering, is_active=True)
        else:
            row.name = name
            row.ordering = ordering
            row.is_active = True
            row.save(update_fields=["name", "ordering", "is_active"])
        for sub_code, sub_name, sub_ordering in sub_types:
            MinuteSubType.objects.get_or_create(
                code=sub_code,
                defaults={"name": sub_name, "ordering": sub_ordering,
                          "minute_type": row})

    MinuteType.objects.filter(code__in=DEACTIVATE).update(is_active=False)
    for code, ordering in TRAILING:
        MinuteType.objects.filter(code=code).update(ordering=ordering)


def unalign(apps, schema_editor):
    """
    Restore the Phase 43 labels and re-activate the generic committee type. The three
    named committees are left in place - a minute may already reference them.
    """
    MinuteType = apps.get_model("minutes", "MinuteType")
    MinuteType.objects.filter(code="management-committee").update(
        name="Management Meeting", ordering=20)
    MinuteType.objects.filter(code="departmental").update(
        name="Department Meeting", ordering=30)
    MinuteType.objects.filter(code="committee-meeting").update(
        is_active=True, ordering=40)


def backfill_legacy_decisions(apps, schema_editor):
    """
    Nothing to backfill for the lifecycle: `Completed` rows keep their value and every
    counter treats them as settled. This exists to say so explicitly rather than leaving
    the reader to wonder whether a data step was forgotten.
    """



class Migration(migrations.Migration):

    dependencies = [
        ('minutes', '0005_alter_minuteauditlog_action'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='minute',
            name='acknowledgement_due_days',
            field=models.PositiveSmallIntegerField(default=7, help_text='Days participants have to acknowledge once the round opens.'),
        ),
        migrations.AddField(
            model_name='minuteactionitem',
            name='escalated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='minuteactionitem',
            name='escalation_notified',
            field=models.CharField(choices=[('none', 'On track'), ('reminder', 'Reminder'), ('escalation', 'Escalated'), ('management_alert', 'Management alert')], default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='minutedecision',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='minutedecision',
            name='closure_remarks',
            field=models.TextField(blank=True, help_text='How the decision was discharged. Required to close it.'),
        ),
        migrations.AddField(
            model_name='minutedecision',
            name='implemented_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='minutedecision',
            name='is_resolution',
            field=models.BooleanField(db_index=True, default=False, help_text='True once the meeting formally resolved this decision.'),
        ),
        migrations.AddField(
            model_name='minutedecision',
            name='resolution_number',
            field=models.CharField(blank=True, db_index=True, help_text='RES-2026-001. Allocated on promotion and never reissued.', max_length=24),
        ),
        migrations.AddField(
            model_name='minutedecision',
            name='resolution_status',
            field=models.CharField(blank=True, choices=[('approved', 'Approved'), ('rejected', 'Rejected'), ('tabled', 'Tabled'), ('deferred', 'Deferred')], max_length=16),
        ),
        migrations.AddField(
            model_name='minutedecision',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='minutechildsequence',
            name='kind',
            field=models.CharField(choices=[('DEC', 'Decision'), ('ACT', 'Action item'), ('RES', 'Board resolution')], max_length=4),
        ),
        migrations.AlterField(
            model_name='minutedecision',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('implemented', 'Implemented'), ('closed', 'Closed'), ('rejected', 'Rejected'), ('deferred', 'Deferred'), ('completed', 'Completed (legacy)')], db_index=True, default='pending', max_length=16),
        ),
        migrations.AddIndex(
            model_name='minuteactionitem',
            index=models.Index(fields=['escalation_notified', 'deadline'], name='minutes_min_escalat_4d6715_idx'),
        ),
        migrations.AddConstraint(
            model_name='minutedecision',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('is_resolution', True), _negated=True), models.Q(('resolution_number', ''), _negated=True), _connector='OR'), name='minute_resolution_has_a_number'),
        ),
        migrations.RunPython(align_governance_types, unalign),
        migrations.RunPython(backfill_legacy_decisions, migrations.RunPython.noop),
    ]
