# Generated by Django 5.2.16 on 2026-10-04 12:28

import minutes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minutes', '0011_phase_a_organization_required'),
    ]

    operations = [
        migrations.AlterField(
            model_name='minuteattachment',
            name='file',
            field=models.FileField(upload_to=minutes.models.minute_attachment_path),
        ),
    ]
