# Generated by Django 5.2.16 on 2026-10-04 12:33

import minutes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minutes', '0012_phase_s3_tenant_upload_paths'),
    ]

    operations = [
        migrations.AlterField(
            model_name='minuteattachment',
            name='file',
            field=models.FileField(max_length=255, upload_to=minutes.models.minute_attachment_path),
        ),
    ]
