# Generated by Django 5.2.16 on 2026-08-14 08:43

import circulars.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('leaves', '0017_merge_20260806_1728'),
        ('memos', '0014_memo_transfer_kind_labels'),
        ('minutes', '0007_alter_minuteauditlog_action'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CircularNumberSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(unique=True)),
                ('last_value', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Circular',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('circular_number', models.CharField(editable=False, max_length=30, unique=True)),
                ('subject', models.CharField(max_length=500)),
                ('content', models.TextField(help_text='The circular body, as sanitized HTML. Sanitized on write, on read and again when the PDF renders.')),
                ('category', models.CharField(choices=[('policy', 'Policy Communication'), ('administrative', 'Administrative Notice'), ('hr', 'HR Announcement'), ('management', 'Management Communication'), ('governance', 'Governance Update'), ('instruction', 'Official Instruction')], db_index=True, default='administrative', max_length=20)),
                ('classification', models.CharField(choices=[('internal', 'Internal'), ('confidential', 'Confidential'), ('restricted', 'Restricted'), ('public', 'Public')], db_index=True, default='internal', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], default='normal', max_length=10)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('under_review', 'Under Review'), ('ready_for_issue', 'Ready For Issue'), ('issued', 'Issued'), ('ready_for_broadcast', 'Ready For Broadcast'), ('broadcasted', 'Broadcasted'), ('archived', 'Archived'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], db_index=True, default='draft', max_length=24)),
                ('issue_date', models.DateField(blank=True, help_text='The date the circular bears. Distinct from created_at and from the broadcast date.', null=True)),
                ('department_name', models.CharField(blank=True, default='', max_length=150)),
                ('external_reference', models.CharField(blank=True, db_index=True, default='', help_text="A reference outside the system - a board decision, a regulator's directive, an incoming letter.", max_length=100)),
                ('acknowledgement_required', models.BooleanField(default=False, help_text='When set, every recipient is asked to confirm or decline. Independent of read tracking, which happens either way.')),
                ('acknowledgement_due_days', models.PositiveSmallIntegerField(default=7, help_text='Days from broadcast within which an acknowledgement is expected.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('issued_at', models.DateTimeField(blank=True, null=True)),
                ('issued_by_name', models.CharField(blank=True, default='', max_length=150)),
                ('broadcast_at', models.DateTimeField(blank=True, null=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='circulars_created', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='circulars', to='leaves.department')),
                ('issued_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='circulars_issued', to=settings.AUTH_USER_MODEL)),
                ('memo_reference', models.ForeignKey(blank=True, help_text='The memo whose decision this circular announces.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='circulars', to='memos.memo')),
                ('minute_reference', models.ForeignKey(blank=True, help_text='The minute whose resolution this circular announces.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='circulars', to='minutes.minute')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CircularAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to=circulars.models.circular_attachment_path)),
                ('original_name', models.CharField(blank=True, default='', max_length=255)),
                ('size', models.PositiveIntegerField(default=0)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('circular', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='circulars.circular')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='circular_attachments_uploaded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='CircularAuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sequence', models.PositiveIntegerField(default=0)),
                ('action', models.CharField(choices=[('created', 'Created'), ('edited', 'Edited'), ('sent_for_review', 'Sent for Review'), ('reviewed', 'Reviewed'), ('rejected', 'Returned for revision'), ('issued', 'Issued'), ('audience_set', 'Audience defined'), ('broadcast', 'Broadcast'), ('read', 'Opened by a recipient'), ('acknowledged', 'Acknowledged'), ('declined', 'Acknowledgement declined'), ('reminded', 'Acknowledgement reminder sent'), ('archived', 'Archived'), ('cancelled', 'Cancelled'), ('attached', 'Attachment added'), ('attachment_removed', 'Attachment removed'), ('imported', 'Content imported'), ('exported', 'Exported')], db_index=True, max_length=20)),
                ('actor_name', models.CharField(blank=True, default='', max_length=150)),
                ('remarks', models.TextField(blank=True, default='')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='circular_actions', to=settings.AUTH_USER_MODEL)),
                ('circular', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_entries', to='circulars.circular')),
            ],
            options={
                'ordering': ['at', 'sequence'],
            },
        ),
        migrations.CreateModel(
            name='CircularBroadcast',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sequence', models.PositiveIntegerField(default=1, help_text='1 for the original broadcast, 2+ for extensions.')),
                ('audience', models.CharField(choices=[('organisation', 'Entire Organisation'), ('departments', 'Selected Departments'), ('groups', 'Employee Groups'), ('employees', 'Selected Employees')], max_length=14)),
                ('include_child_departments', models.BooleanField(default=True, help_text='Departments only: also reach every department beneath the named ones. leaves.Department is self-nesting, so a unit IS a department row with a parent.')),
                ('audience_label', models.CharField(blank=True, default='', help_text='Human description of the audience, snapshotted - so the record still reads correctly after a department is renamed.', max_length=300)),
                ('recipient_count', models.PositiveIntegerField(default=0)),
                ('already_present_count', models.PositiveIntegerField(default=0)),
                ('broadcast_by_name', models.CharField(blank=True, default='', max_length=150)),
                ('broadcast_at', models.DateTimeField(auto_now_add=True)),
                ('remarks', models.TextField(blank=True, default='')),
                ('broadcast_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='circular_broadcasts_sent', to=settings.AUTH_USER_MODEL)),
                ('circular', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='broadcasts', to='circulars.circular')),
                ('departments', models.ManyToManyField(blank=True, related_name='circular_broadcasts', to='leaves.department')),
                ('employees', models.ManyToManyField(blank=True, related_name='circular_broadcasts_targeted', to=settings.AUTH_USER_MODEL)),
                ('groups', models.ManyToManyField(blank=True, related_name='circular_broadcasts', to='auth.group')),
            ],
            options={
                'ordering': ['-broadcast_at'],
            },
        ),
        migrations.CreateModel(
            name='CircularRecipient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_name', models.CharField(blank=True, default='', max_length=150)),
                ('designation', models.CharField(blank=True, default='', max_length=120)),
                ('department_label', models.CharField(blank=True, default='', max_length=150)),
                ('notified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('broadcast', models.ForeignKey(blank=True, help_text='Which broadcast first reached this person. SET_NULL so deleting a broadcast log never removes somebody from the audience.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recipients', to='circulars.circularbroadcast')),
                ('circular', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to='circulars.circular')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='circular_recipients', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user_name'],
            },
        ),
        migrations.CreateModel(
            name='CircularReadLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('opened_at', models.DateTimeField(help_text='First open. Never updated afterwards.')),
                ('last_viewed_at', models.DateTimeField()),
                ('view_count', models.PositiveIntegerField(default=1)),
                ('recipient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='read_log', to='circulars.circularrecipient')),
            ],
            options={
                'ordering': ['-last_viewed_at'],
            },
        ),
        migrations.CreateModel(
            name='CircularAcknowledgement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('state', models.CharField(choices=[('pending', 'Pending'), ('acknowledged', 'Acknowledged'), ('declined', 'Declined')], db_index=True, default='pending', max_length=14)),
                ('remarks', models.TextField(blank=True, default='')),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('due_date', models.DateField(blank=True, help_text="Snapshotted at broadcast, so a later change to the circular's due-days setting cannot move a deadline somebody was already given.", null=True)),
                ('reminded_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='acknowledgement', to='circulars.circularrecipient')),
            ],
            options={
                'ordering': ['recipient__user_name'],
            },
        ),
        migrations.CreateModel(
            name='CircularWorkflowStep',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sequence', models.PositiveIntegerField(help_text='1-based position. Contiguous and unique per circular.')),
                ('assignee_name', models.CharField(blank=True, default='', max_length=150)),
                ('designation', models.CharField(blank=True, default='', max_length=120)),
                ('department_label', models.CharField(blank=True, default='', max_length=150)),
                ('role_type', models.CharField(choices=[('reviewer', 'Reviewer'), ('issuer', 'Issuer')], max_length=12)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Awaiting Action'), ('completed', 'Completed'), ('rejected', 'Rejected'), ('skipped', 'Skipped')], db_index=True, default='pending', max_length=12)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('acted_at', models.DateTimeField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='circular_workflow_steps', to=settings.AUTH_USER_MODEL)),
                ('circular', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_steps', to='circulars.circular')),
            ],
            options={
                'ordering': ['circular', 'sequence'],
            },
        ),
        migrations.AddIndex(
            model_name='circular',
            index=models.Index(fields=['status', 'created_by'], name='cir_status_author_idx'),
        ),
        migrations.AddIndex(
            model_name='circular',
            index=models.Index(fields=['status', 'department'], name='cir_status_dept_idx'),
        ),
        migrations.AddIndex(
            model_name='circular',
            index=models.Index(fields=['-created_at'], name='cir_created_desc_idx'),
        ),
        migrations.AddIndex(
            model_name='circular',
            index=models.Index(fields=['classification'], name='cir_classification_idx'),
        ),
        migrations.AddIndex(
            model_name='circularauditlog',
            index=models.Index(fields=['circular', 'action'], name='cir_audit_action_idx'),
        ),
        migrations.AddConstraint(
            model_name='circularbroadcast',
            constraint=models.UniqueConstraint(fields=('circular', 'sequence'), name='uniq_cir_broadcast_sequence'),
        ),
        migrations.AddIndex(
            model_name='circularrecipient',
            index=models.Index(fields=['user', 'circular'], name='cir_recipient_user_idx'),
        ),
        migrations.AddConstraint(
            model_name='circularrecipient',
            constraint=models.UniqueConstraint(fields=('circular', 'user'), name='uniq_cir_recipient'),
        ),
        migrations.AddIndex(
            model_name='circularworkflowstep',
            index=models.Index(fields=['assignee', 'status'], name='cir_step_assignee_idx'),
        ),
        migrations.AddConstraint(
            model_name='circularworkflowstep',
            constraint=models.UniqueConstraint(fields=('circular', 'sequence'), name='uniq_cir_step_sequence'),
        ),
        migrations.AddConstraint(
            model_name='circularworkflowstep',
            constraint=models.UniqueConstraint(fields=('circular', 'assignee'), name='uniq_cir_step_assignee'),
        ),
    ]
