# Generated by Django 5.2.16 on 2026-09-15 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circulars', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='circular',
            name='category',
            field=models.CharField(choices=[('policy', 'Policy Communication'), ('administrative', 'Administrative Notice'), ('hr', 'HR Announcement'), ('management', 'Management Communication'), ('governance', 'Governance Update'), ('instruction', 'Official Instruction'), ('executive', 'Executive Circular')], db_index=True, default='administrative', max_length=20),
        ),
        migrations.AlterField(
            model_name='circularbroadcast',
            name='audience',
            field=models.CharField(choices=[('organisation', 'Entire Organisation'), ('departments', 'Selected Departments'), ('groups', 'Employee Groups'), ('employees', 'Selected Employees'), ('board', 'Board of Directors')], max_length=14),
        ),
    ]
