# Generated by Django 5.2.16 on 2026-10-04 12:33

import circulars.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circulars', '0004_phase_a_organization_required'),
    ]

    operations = [
        migrations.AlterField(
            model_name='circularattachment',
            name='file',
            field=models.FileField(max_length=255, upload_to=circulars.models.circular_attachment_path),
        ),
    ]
