# Generated by Django 5.2.12 on 2026-04-29 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('maker', 'Maker'), ('checker', 'Checker'), ('approver', 'Approver'), ('admin', 'Admin')], default='maker', max_length=20),
        ),
    ]
