# Generated by Django 5.2.16 on 2026-07-12 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_backfill_employee_ids'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='employee_type',
            field=models.CharField(choices=[('employee', 'Employee'), ('supervisor', 'Supervisor'), ('manager', 'Manager'), ('department_head', 'Department Head'), ('hr_officer', 'HR Officer'), ('system_admin', 'System Admin')], default='employee', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('maker', 'Employee'), ('checker', 'Department Head'), ('approver', 'HR'), ('admin', 'Admin')], default='maker', max_length=20),
        ),
    ]
