# Generated by Django 5.2.16 on 2026-07-13 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_employee_type_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='category_flag',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='employment_type',
            field=models.CharField(choices=[('permanent', 'Permanent'), ('post_probation', 'Post-Probation'), ('probation', 'Probation'), ('intern', 'Intern'), ('volunteer', 'Volunteer')], default='permanent', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('undisclosed', 'Prefer not to say')], default='undisclosed', max_length=12),
        ),
        migrations.AddField(
            model_name='user',
            name='leave_category',
            field=models.CharField(blank=True, choices=[('A', 'Category A — Permanent (>3 yrs)'), ('B', 'Category B — Permanent (1–3 yrs)'), ('C', 'Category C — Post-Probation / Permanent (<1 yr)'), ('D', 'Category D — Intern / Volunteer'), ('PROBATION', 'Probation (<3 mo)')], max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='maternity_eligible',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='paternity_eligible',
            field=models.BooleanField(default=False),
        ),
    ]
