# Generated by Django 5.2.16 on 2026-08-11 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_user_address_user_bio_user_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='biometric_id',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
