# Generated by Django 5.2.16 on 2026-09-07 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_user_biometric_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='leave_category',
            field=models.CharField(blank=True, choices=[('A', 'Category A — Permanent (>3 yrs)'), ('B', 'Category B — Permanent (1–3 yrs)'), ('C', 'Category C — Post-Probation / Permanent (<1 yr)'), ('D', 'Category D — Intern'), ('E', 'Category E — Volunteer'), ('PROBATION', 'Probation (<3 mo)')], max_length=12, null=True),
        ),
    ]
