# Generated by Django 5.2.16 on 2026-09-15 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_user_leave_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('maker', 'Employee'), ('checker', 'Department Head'), ('approver', 'HR'), ('bod', 'Board of Directors'), ('admin', 'Admin')], default='maker', max_length=20),
        ),
    ]
