# Generated by Django 5.2.16 on 2026-10-04 08:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('leaves', '0021_leave_board_action_date_leave_board_reviewer'),
        ('tenancy', '0001_initial'),
        ('users', '0011_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_platform_staff',
            field=models.BooleanField(default=False, help_text="Platform operator, not a customer's employee. Grants access to the platform console and to NO tenant workspace."),
        ),
        migrations.AddField(
            model_name='user',
            name='organization',
            field=models.ForeignKey(blank=True, help_text='The tenant this user belongs to. NULL for platform staff.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='users', to='tenancy.organization'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(condition=models.Q(('is_platform_staff', True), ('organization__isnull', False), _negated=True), name='user_platform_staff_has_no_org'),
        ),
    ]
