# Generated by Django 5.2.16 on 2026-10-04 12:28

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_phase_a_user_identity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to=users.models.profile_photo_path),
        ),
    ]
