# Generated by Django 5.2.16 on 2026-10-04 12:33

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_phase_s3_tenant_upload_paths'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_photo',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to=users.models.profile_photo_path),
        ),
    ]
