# Generated by Django 5.2.17 on 2026-10-04 14:51

import users.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_phase_s3_media_path_length'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', users.models.TenantUserManager()),
                ('all_tenants', users.models.UnscopedUserManager()),
            ],
        ),
    ]
