# Generated by Django 5.2.17 on 2026-10-06 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_phase_s5_user_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ui_state',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
