# Generated by Django 5.2.16 on 2026-09-15 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0004_alter_auditlog_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('approve', 'Approve'), ('reject', 'Reject'), ('submit', 'Submit'), ('login', 'Login'), ('other', 'Other'), ('reviewed', 'Reviewed'), ('recommended', 'Recommended'), ('supported', 'Supported'), ('archived', 'Archived'), ('ownership_changed', 'Ownership Changed'), ('bod_approved', 'BOD Approved'), ('bod_rejected', 'BOD Rejected')], db_index=True, max_length=20),
        ),
    ]
