# Generated by Django 5.2.16 on 2026-10-04 08:46

import django.core.validators
import django.db.models.deletion
import django.db.models.functions.text
import django.utils.timezone
import tenancy.slugs
import tenancy.uploads
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentInstruction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('method', models.CharField(db_index=True, max_length=20)),
                ('label', models.CharField(max_length=120)),
                ('account_name', models.CharField(blank=True, default='', max_length=160)),
                ('account_number', models.CharField(blank=True, default='', max_length=64)),
                ('bank_name', models.CharField(blank=True, default='', max_length=160)),
                ('branch', models.CharField(blank=True, default='', max_length=160)),
                ('esewa_id', models.CharField(blank=True, default='', max_length=64)),
                ('qr_image', models.ImageField(blank=True, null=True, upload_to='platform/payment-instructions/')),
                ('instructions_html', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['sort_order', 'label'],
            },
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.SlugField(max_length=30, unique=True)),
                ('name', models.CharField(max_length=80)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('interval_months', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('trial_days', models.PositiveSmallIntegerField(default=14)),
                ('grace_days', models.PositiveSmallIntegerField(default=7)),
                ('billing_mode', models.CharField(choices=[('flat', 'Flat per organization'), ('per_seat', 'Per seat')], default='flat', max_length=10)),
                ('included_seats', models.PositiveIntegerField(blank=True, null=True)),
                ('is_public', models.BooleanField(default=True, help_text='Shown in the plan picker.')),
                ('is_active', models.BooleanField(default=True, help_text='New subscriptions permitted.')),
                ('sort_order', models.PositiveSmallIntegerField(default=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['sort_order', 'interval_months'],
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=63, unique=True, validators=[tenancy.slugs.validate_tenant_slug])),
                ('status', models.CharField(choices=[('provisioning', 'Provisioning'), ('trial', 'Trial'), ('active', 'Active'), ('suspended', 'Suspended'), ('cancelled', 'Cancelled')], db_index=True, default='provisioning', max_length=20)),
                ('logo', models.ImageField(blank=True, null=True, upload_to=tenancy.uploads.org_asset_path)),
                ('favicon', models.ImageField(blank=True, null=True, upload_to=tenancy.uploads.org_asset_path)),
                ('industry', models.CharField(blank=True, default='', max_length=80)),
                ('address', models.TextField(blank=True, default='')),
                ('phone', models.CharField(blank=True, default='', max_length=32)),
                ('email', models.EmailField(help_text='Billing and platform-notice address.', max_length=254)),
                ('country', models.CharField(default='NP', help_text='ISO 3166-1 alpha-2.', max_length=2)),
                ('timezone', models.CharField(default='Asia/Kathmandu', max_length=64)),
                ('document_prefix', models.CharField(max_length=12)),
                ('fiscal_calendar', models.CharField(choices=[('BS', 'Bikram Sambat'), ('AD', 'Gregorian')], default='BS', max_length=2)),
                ('site_url', models.URLField(blank=True, default='')),
                ('domain', models.CharField(blank=True, max_length=253, null=True, unique=True)),
                ('database_alias', models.CharField(default='default', max_length=40)),
                ('subscription_status', models.CharField(db_index=True, default='trial', editable=False, max_length=20)),
                ('subscription_start', models.DateField(blank=True, editable=False, null=True)),
                ('subscription_expiry', models.DateField(blank=True, db_index=True, editable=False, null=True)),
                ('seat_count', models.PositiveIntegerField(default=0, editable=False)),
                ('storage_bytes', models.BigIntegerField(default=0, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organizations_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='OrganizationBranding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(blank=True, default='', max_length=200)),
                ('logo_primary', models.ImageField(blank=True, null=True, upload_to=tenancy.uploads.org_asset_path)),
                ('logo_login', models.ImageField(blank=True, null=True, upload_to=tenancy.uploads.org_asset_path)),
                ('logo_email', models.ImageField(blank=True, null=True, upload_to=tenancy.uploads.org_asset_path)),
                ('logo_letterhead', models.ImageField(blank=True, null=True, upload_to=tenancy.uploads.org_asset_path)),
                ('color_primary', models.CharField(blank=True, default='', max_length=7, validators=[django.core.validators.RegexValidator('^#(?:[0-9a-fA-F]{3}|[0-9a-fA-F]{6})$', 'Enter a hex colour such as #1D4ED8.')])),
                ('color_secondary', models.CharField(blank=True, default='', max_length=7, validators=[django.core.validators.RegexValidator('^#(?:[0-9a-fA-F]{3}|[0-9a-fA-F]{6})$', 'Enter a hex colour such as #1D4ED8.')])),
                ('login_tagline', models.CharField(blank=True, default='', max_length=200)),
                ('dashboard_welcome', models.CharField(blank=True, default='', max_length=300)),
                ('report_footer_text', models.CharField(blank=True, default='', max_length=300)),
                ('email_footer_html', models.TextField(blank=True, default='')),
                ('letterhead_header_html', models.TextField(blank=True, default='')),
                ('letterhead_footer_html', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='branding', to='tenancy.organization')),
            ],
        ),
        migrations.CreateModel(
            name='OrganizationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('office_start', models.TimeField(blank=True, null=True)),
                ('full_day_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('half_day_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('absent_cutoff', models.TimeField(blank=True, null=True)),
                ('tracking_start', models.DateField(blank=True, null=True)),
                ('office_name', models.CharField(blank=True, default='', max_length=120)),
                ('office_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('office_lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('office_radius_m', models.PositiveIntegerField(blank=True, null=True)),
                ('max_accuracy_m', models.PositiveIntegerField(blank=True, null=True)),
                ('require_location', models.BooleanField(blank=True, null=True)),
                ('escalation_supervisor_days', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('escalation_hr_days', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('escalation_management_days', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('review_pending_days', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('min_department_sample', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='tenancy.organization')),
            ],
            options={
                'verbose_name_plural': 'organization settings',
            },
        ),
        migrations.CreateModel(
            name='PlanPrice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('currency', models.CharField(default='NPR', max_length=3)),
                ('amount_minor', models.BigIntegerField(help_text='Minor units (paisa for NPR). 12345 = NPR 123.45', validators=[django.core.validators.MinValueValidator(0)])),
                ('per_extra_seat_minor', models.BigIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('effective_from', models.DateField()),
                ('effective_until', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prices', to='tenancy.plan')),
            ],
            options={
                'ordering': ['plan', '-effective_from'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('payment_reference', models.CharField(editable=False, max_length=32)),
                ('amount_minor', models.BigIntegerField(editable=False, validators=[django.core.validators.MinValueValidator(0)])),
                ('currency', models.CharField(default='NPR', editable=False, max_length=3)),
                ('method', models.CharField(blank=True, choices=[('esewa', 'eSewa'), ('bank_transfer', 'Bank Transfer'), ('cheque', 'Cheque'), ('cash', 'Cash')], default='', max_length=20)),
                ('transaction_id', models.CharField(blank=True, default='', max_length=120)),
                ('paid_at', models.DateField(blank=True, help_text='Date the customer says they paid.', null=True)),
                ('payer_note', models.TextField(blank=True, default='')),
                ('proof', models.FileField(blank=True, null=True, upload_to=tenancy.uploads.payment_proof_path)),
                ('status', models.CharField(choices=[('awaiting_proof', 'Awaiting proof'), ('submitted', 'Proof submitted'), ('under_review', 'Under review'), ('verified', 'Verified'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], db_index=True, default='awaiting_proof', max_length=20)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('review_started_at', models.DateTimeField(blank=True, null=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, default='')),
                ('gateway', models.CharField(blank=True, default='', max_length=30)),
                ('gateway_ref', models.CharField(blank=True, default='', max_length=120)),
                ('gateway_payload', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments_created', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='tenancy.organization')),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments_claimed', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments_verified', to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='tenancy.plan')),
                ('plan_price', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='tenancy.planprice')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('trial', 'Trial'), ('active', 'Active'), ('grace', 'Grace period'), ('suspended', 'Suspended'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], db_index=True, default='trial', max_length=20)),
                ('trial_start', models.DateField(blank=True, null=True)),
                ('trial_end', models.DateField(blank=True, null=True)),
                ('current_period_start', models.DateField(blank=True, null=True)),
                ('current_period_end', models.DateField(blank=True, db_index=True, null=True)),
                ('grace_until', models.DateField(blank=True, db_index=True, null=True)),
                ('renewal_date', models.DateField(blank=True, null=True)),
                ('auto_renew', models.BooleanField(default=False)),
                ('seats', models.PositiveIntegerField(default=0)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancel_reason', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='subscription', to='tenancy.organization')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='tenancy.plan')),
                ('plan_price', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='tenancy.planprice')),
            ],
            options={
                'ordering': ['organization__name'],
            },
        ),
        migrations.CreateModel(
            name='SubscriptionEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event', models.CharField(choices=[('created', 'Created'), ('trial_started', 'Trial started'), ('activated', 'Activated'), ('renewed', 'Renewed'), ('extended', 'Extended'), ('plan_changed', 'Plan changed'), ('entered_grace', 'Entered grace period'), ('expired', 'Expired'), ('suspended', 'Suspended'), ('reactivated', 'Reactivated'), ('cancelled', 'Cancelled')], db_index=True, max_length=30)),
                ('from_status', models.CharField(blank=True, default='', max_length=20)),
                ('to_status', models.CharField(blank=True, default='', max_length=20)),
                ('period_start', models.DateField(blank=True, null=True)),
                ('period_end', models.DateField(blank=True, null=True)),
                ('note', models.TextField(blank=True, default='')),
                ('effective_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscription_events', to=settings.AUTH_USER_MODEL)),
                ('from_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='tenancy.plan')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_events', to='tenancy.organization')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='tenancy.payment')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='tenancy.subscription')),
                ('to_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='tenancy.plan')),
            ],
            options={
                'ordering': ['-effective_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='planprice',
            constraint=models.UniqueConstraint(fields=('plan', 'currency', 'effective_from'), name='uniq_plan_price_effective'),
        ),
        migrations.AddConstraint(
            model_name='planprice',
            constraint=models.CheckConstraint(condition=models.Q(('effective_until__isnull', True), ('effective_until__gte', models.F('effective_from')), _connector='OR'), name='plan_price_period_ordered'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['status', 'created_at'], name='payment_queue_idx'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.UniqueConstraint(fields=('organization', 'payment_reference'), name='uniq_payment_ref_per_org'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('transaction_id'), models.F('organization'), condition=models.Q(('transaction_id', ''), _negated=True), name='uniq_payment_txn_per_org'),
        ),
        migrations.AddConstraint(
            model_name='subscriptionevent',
            constraint=models.UniqueConstraint(condition=models.Q(('event__in', ['activated', 'renewed', 'extended'])), fields=('payment',), name='uniq_activation_per_payment'),
        ),
    ]
