# Generated by Django 5.2.16 on 2026-10-04 12:33

import tenancy.uploads
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0004_organization_legacy_number_formats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='favicon',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to=tenancy.uploads.org_asset_path),
        ),
        migrations.AlterField(
            model_name='organization',
            name='logo',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to=tenancy.uploads.org_asset_path),
        ),
        migrations.AlterField(
            model_name='organizationbranding',
            name='logo_email',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to=tenancy.uploads.org_asset_path),
        ),
        migrations.AlterField(
            model_name='organizationbranding',
            name='logo_letterhead',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to=tenancy.uploads.org_asset_path),
        ),
        migrations.AlterField(
            model_name='organizationbranding',
            name='logo_login',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to=tenancy.uploads.org_asset_path),
        ),
        migrations.AlterField(
            model_name='organizationbranding',
            name='logo_primary',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to=tenancy.uploads.org_asset_path),
        ),
        migrations.AlterField(
            model_name='payment',
            name='proof',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to=tenancy.uploads.payment_proof_path),
        ),
        migrations.AlterField(
            model_name='paymentinstruction',
            name='qr_image',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='platform/payment-instructions/'),
        ),
    ]
