# Generated by Django 5.2.17 on 2026-10-04 16:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0006_phase_s5_row_level_security'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationsettings',
            name='notify_digest_default',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organizationsettings',
            name='notify_email_default',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organizationsettings',
            name='notify_in_app_default',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='status',
            field=models.CharField(choices=[('provisioning', 'Provisioning'), ('trial', 'Trial'), ('active', 'Active'), ('grace', 'Grace period'), ('suspended', 'Suspended'), ('cancelled', 'Cancelled')], db_index=True, default='provisioning', max_length=20),
        ),
        migrations.CreateModel(
            name='PlatformAuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('organization_slug', models.CharField(blank=True, default='', max_length=63)),
                ('organization_name', models.CharField(blank=True, default='', max_length=200)),
                ('action', models.CharField(choices=[('tenant_created', 'Tenant created'), ('tenant_updated', 'Tenant updated'), ('tenant_bootstrapped', 'Tenant bootstrapped'), ('tenant_suspended', 'Tenant suspended'), ('tenant_activated', 'Tenant activated'), ('tenant_cancelled', 'Tenant cancelled'), ('subscription_changed', 'Subscription changed'), ('plan_changed', 'Plan changed'), ('subscription_extended', 'Subscription extended'), ('trial_started', 'Trial started'), ('branding_changed', 'Branding changed'), ('settings_changed', 'Settings changed'), ('payment_verified', 'Payment verified'), ('payment_rejected', 'Payment rejected'), ('admin_user_created', 'Tenant admin user created')], db_index=True, max_length=40)),
                ('actor_email', models.CharField(blank=True, default='', max_length=254)),
                ('changes', models.JSONField(blank=True, null=True)),
                ('note', models.TextField(blank=True, default='')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, default='', max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='platform_audit_entries', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='platform_audit_entries', to='tenancy.organization')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['organization', '-created_at'], name='platform_audit_org_idx')],
            },
        ),
    ]
