# Generated by Django 5.2.17 on 2026-10-04 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0007_phase_s6_platform_console'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='status_overridden_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='status_override',
            field=models.BooleanField(default=False, editable=False, help_text='The status was set by a platform operator; the subscription must not derive over it.'),
        ),
        migrations.AddField(
            model_name='organization',
            name='status_override_reason',
            field=models.CharField(blank=True, default='', editable=False, max_length=300),
        ),
    ]
