# Generated by Django 5.2.17 on 2026-10-05 12:36

import django.db.models.deletion
import tenancy.uploads
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0009_phase_s6_platform_policy'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='archived_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='archived_reason',
            field=models.CharField(blank=True, default='', editable=False, max_length=300),
        ),
        migrations.AddField(
            model_name='organization',
            name='status_before_archive',
            field=models.CharField(blank=True, default='', editable=False, max_length=20),
        ),
        migrations.AlterField(
            model_name='organization',
            name='status',
            field=models.CharField(choices=[('provisioning', 'Provisioning'), ('trial', 'Trial'), ('active', 'Active'), ('grace', 'Grace period'), ('suspended', 'Suspended'), ('cancelled', 'Cancelled'), ('archived', 'Archived')], db_index=True, default='provisioning', max_length=20),
        ),
        migrations.AlterField(
            model_name='platformauditlog',
            name='action',
            field=models.CharField(choices=[('tenant_created', 'Tenant created'), ('tenant_updated', 'Tenant updated'), ('tenant_bootstrapped', 'Tenant bootstrapped'), ('tenant_suspended', 'Tenant suspended'), ('tenant_activated', 'Tenant activated'), ('tenant_cancelled', 'Tenant cancelled'), ('subscription_changed', 'Subscription changed'), ('plan_changed', 'Plan changed'), ('subscription_extended', 'Subscription extended'), ('trial_started', 'Trial started'), ('branding_changed', 'Branding changed'), ('settings_changed', 'Settings changed'), ('payment_verified', 'Payment verified'), ('payment_rejected', 'Payment rejected'), ('admin_user_created', 'Tenant admin user created'), ('export_created', 'Export created'), ('export_downloaded', 'Export downloaded'), ('tenant_archived', 'Tenant archived'), ('tenant_restored', 'Tenant restored'), ('retention_action', 'Retention action')], db_index=True, max_length=40),
        ),
        migrations.CreateModel(
            name='TenantExport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('organization_slug', models.CharField(blank=True, default='', max_length=63)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('ready', 'Ready'), ('failed', 'Failed'), ('expired', 'Expired')], db_index=True, default='pending', max_length=20)),
                ('contents', models.CharField(choices=[('json', 'JSON only'), ('csv', 'CSV only'), ('full', 'JSON, CSV and media')], default='full', max_length=10)),
                ('requested_by_email', models.CharField(blank=True, default='', max_length=254)),
                ('file', models.FileField(blank=True, max_length=255, null=True, upload_to=tenancy.uploads.export_bundle_path)),
                ('size_bytes', models.BigIntegerField(default=0)),
                ('sha256', models.CharField(blank=True, default='', max_length=64)),
                ('manifest', models.JSONField(blank=True, null=True)),
                ('row_count', models.PositiveIntegerField(default=0)),
                ('media_count', models.PositiveIntegerField(default=0)),
                ('error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('downloaded_at', models.DateTimeField(blank=True, null=True)),
                ('download_count', models.PositiveIntegerField(default=0)),
                ('last_downloaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tenant_exports_downloaded', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exports', to='tenancy.organization')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tenant_exports_requested', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['organization', '-created_at'], name='tenant_export_org_idx')],
            },
        ),
    ]
