# Generated by Django 5.2.17 on 2026-10-05 13:09

import django.db.models.deletion
import tenancy.slugs
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0010_s6_5_tenant_export_and_archive'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingRegistration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('organization_name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=63, validators=[tenancy.slugs.validate_tenant_slug])),
                ('industry', models.CharField(blank=True, default='', max_length=100)),
                ('country', models.CharField(blank=True, default='', max_length=2)),
                ('organization_email', models.EmailField(max_length=254)),
                ('admin_name', models.CharField(blank=True, default='', max_length=150)),
                ('admin_email', models.EmailField(db_index=True, max_length=254)),
                ('admin_password', models.CharField(editable=False, max_length=256)),
                ('status', models.CharField(choices=[('pending', 'Awaiting email verification'), ('verified', 'Email verified'), ('provisioned', 'Workspace created'), ('expired', 'Expired unverified'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20)),
                ('token_hash', models.CharField(db_index=True, editable=False, max_length=64)),
                ('token_expires_at', models.DateTimeField()),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, default='', max_length=300)),
                ('verification_sends', models.PositiveIntegerField(default=0)),
                ('verification_attempts', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('provisioned_at', models.DateTimeField(blank=True, null=True)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registration', to='tenancy.organization')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='pending_reg_status_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status__in', ['pending', 'verified'])), fields=('slug',), name='uniq_pending_registration_slug'), models.UniqueConstraint(condition=models.Q(('status__in', ['pending', 'verified'])), fields=('admin_email',), name='uniq_pending_registration_admin_email')],
            },
        ),
    ]
