# Generated by Django 5.2.17 on 2026-10-05 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0011_s7_pending_registration'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationsettings',
            name='onboarding_dismissed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organizationsettings',
            name='onboarding_steps',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
