# Generated by Django 5.2.17 on 2026-10-05 14:17

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0012_s7_onboarding_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformMetric',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('day', models.DateField(db_index=True)),
                ('key', models.CharField(choices=[('login_ok', 'Login succeeded'), ('login_failed', 'Login failed'), ('provision_ok', 'Provisioning succeeded'), ('provision_failed', 'Provisioning failed'), ('email_sent', 'Platform email sent'), ('email_failed', 'Platform email failed')], db_index=True, max_length=32)),
                ('count', models.PositiveIntegerField(default=0)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='tenancy.organization')),
            ],
            options={
                'ordering': ['-day', 'key'],
                'indexes': [models.Index(fields=['key', '-day'], name='platform_metric_idx')],
                'constraints': [models.UniqueConstraint(fields=('day', 'key', 'organization'), name='uniq_platform_metric_day_key_org')],
            },
        ),
    ]
