# Generated by Django 5.2.17 on 2026-10-05 15:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0014_s8_customer_payment_actions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantDomain',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('hostname', models.CharField(db_index=True, max_length=253, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Awaiting DNS verification'), ('verified', 'Ownership verified'), ('active', 'Active'), ('failed', 'Verification failed'), ('removed', 'Removed')], db_index=True, default='pending', max_length=20)),
                ('method', models.CharField(choices=[('txt', 'TXT record'), ('cname', 'CNAME record')], default='txt', max_length=10)),
                ('verification_token', models.CharField(editable=False, max_length=64)),
                ('is_primary', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('last_checked_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.CharField(blank=True, default='', max_length=300)),
                ('check_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tenant_domains_created', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domains', to='tenancy.organization')),
            ],
            options={
                'ordering': ['-is_primary', 'hostname'],
                'indexes': [models.Index(fields=['status', 'hostname'], name='tenant_domain_status_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('organization',), name='uniq_primary_domain_per_org')],
            },
        ),
    ]
