# Generated by Django 5.2.17 on 2026-10-05 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0015_s9_tenant_domain'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationbranding',
            name='color_accent',
            field=models.CharField(blank=True, default='', help_text='Hex, e.g. #F59E0B. Used for buttons and highlights.', max_length=7),
        ),
        migrations.AlterField(
            model_name='platformauditlog',
            name='action',
            field=models.CharField(choices=[('tenant_created', 'Tenant created'), ('tenant_updated', 'Tenant updated'), ('tenant_bootstrapped', 'Tenant bootstrapped'), ('tenant_suspended', 'Tenant suspended'), ('tenant_activated', 'Tenant activated'), ('tenant_cancelled', 'Tenant cancelled'), ('subscription_changed', 'Subscription changed'), ('plan_changed', 'Plan changed'), ('subscription_extended', 'Subscription extended'), ('trial_started', 'Trial started'), ('branding_changed', 'Branding changed'), ('settings_changed', 'Settings changed'), ('payment_verified', 'Payment verified'), ('payment_rejected', 'Payment rejected'), ('payment_requested', 'Plan requested by customer'), ('payment_submitted', 'Payment proof submitted'), ('branding_updated', 'Branding updated by customer'), ('domain_claimed', 'Custom domain claimed'), ('domain_verified', 'Custom domain verified'), ('domain_removed', 'Custom domain removed'), ('admin_user_created', 'Tenant admin user created'), ('export_created', 'Export created'), ('export_downloaded', 'Export downloaded'), ('tenant_archived', 'Tenant archived'), ('tenant_restored', 'Tenant restored'), ('retention_action', 'Retention action')], db_index=True, max_length=40),
        ),
    ]
