# Generated by Django 5.2.17 on 2026-10-06 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0016_s9_branding_accent_and_domain_actions'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationsettings',
            name='attendance_mode',
            field=models.CharField(blank=True, choices=[('biometric_only', 'Biometric devices only'), ('app_only', 'App check-in only'), ('both', 'Biometric devices and app check-in')], default='', max_length=20),
        ),
    ]
