# Generated by Django 5.2.17 on 2026-10-06 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0017_organizationsettings_attendance_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platformauditlog',
            name='action',
            field=models.CharField(choices=[('tenant_created', 'Organization created'), ('tenant_updated', 'Organization details changed'), ('tenant_bootstrapped', 'Workspace set up'), ('tenant_suspended', 'Organization suspended'), ('tenant_activated', 'Organization reactivated'), ('tenant_cancelled', 'Organization cancelled'), ('subscription_changed', 'Subscription changed'), ('plan_changed', 'Plan changed'), ('subscription_extended', 'Subscription extended'), ('trial_started', 'Trial started'), ('branding_changed', 'Branding changed'), ('settings_changed', 'Settings changed'), ('payment_verified', 'Payment verified'), ('payment_rejected', 'Payment rejected'), ('payment_requested', 'Plan requested by customer'), ('payment_submitted', 'Payment proof submitted'), ('branding_updated', 'Branding updated by customer'), ('domain_claimed', 'Custom domain claimed'), ('domain_verified', 'Custom domain verified'), ('domain_removed', 'Custom domain removed'), ('admin_user_created', 'First administrator created'), ('export_created', 'Export created'), ('export_downloaded', 'Export downloaded'), ('tenant_archived', 'Organization archived'), ('tenant_restored', 'Organization restored'), ('retention_action', 'Retention action'), ('access_sent', 'Sign-in details emailed'), ('access_reissued', 'Temporary password reissued'), ('admin_first_sign_in', 'Client administrator signed in')], db_index=True, max_length=40),
        ),
    ]
