# Generated by Django 5.2.17 on 2026-10-06 18:43

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0019_payment_operations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platformmetric',
            name='key',
            field=models.CharField(choices=[('login_ok', 'Login succeeded'), ('login_failed', 'Login failed'), ('provision_ok', 'Provisioning succeeded'), ('provision_failed', 'Provisioning failed'), ('email_sent', 'Platform email sent'), ('email_failed', 'Platform email failed'), ('active_user', 'Active user (once per person per day)'), ('attendance_used', 'Attendance recorded'), ('leave_used', 'Leave applied for'), ('task_used', 'Task created'), ('document_used', 'Document created')], db_index=True, max_length=32),
        ),
        migrations.CreateModel(
            name='SupportRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('contact', 'Question'), ('problem', 'Problem report'), ('feature', 'Feature request'), ('feedback', 'Feedback')], db_index=True, max_length=20)),
                ('subject', models.CharField(blank=True, default='', max_length=200)),
                ('message', models.TextField(blank=True, default='')),
                ('rating', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('feature', models.CharField(blank=True, default='', max_length=80)),
                ('page', models.CharField(blank=True, default='', max_length=300)),
                ('user_agent', models.CharField(blank=True, default='', max_length=300)),
                ('submitted_by_email', models.EmailField(blank=True, default='', max_length=254)),
                ('submitted_by_name', models.CharField(blank=True, default='', max_length=150)),
                ('submitted_by_role', models.CharField(blank=True, default='', max_length=30)),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In progress'), ('resolved', 'Resolved')], db_index=True, default='open', max_length=20)),
                ('response', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='support_requests', to='tenancy.organization')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
