# Generated by Django 5.2.17 on 2026-10-07 11:22

import django.db.models.deletion
import django.utils.timezone
import tenancy.uploads
import uuid
from django.conf import settings
from django.db import migrations, models


def adopt_existing_requests(apps, schema_editor):
    """Give requests sent before the Support Center a place in it.

    Numbers in creation order; a category from the old kind; feature requests
    start "Submitted"; an old single reply becomes the first staff message, so
    the conversation view shows what was already said. Nothing that was
    already resolved is marked unread.
    """
    Request = apps.get_model("tenancy", "SupportRequest")
    Message = apps.get_model("tenancy", "SupportMessage")
    category = {"problem": "bug", "contact": "other", "feature": "feature_request"}
    number = 0
    for r in Request.objects.exclude(kind="feedback").order_by("created_at"):
        number += 1
        r.number = number
        r.category = category.get(r.kind, "other")
        if r.kind == "feature":
            r.roadmap_status = "submitted"
            r.priority = "low"
        r.unread_by_staff = r.status == "open"
        if r.status == "resolved":
            r.resolved_at = r.updated_at
        r.save()
        if r.response:
            Message.objects.create(ticket=r, author_kind="staff", author_name="Support team",
                                   body=r.response)
    Request.objects.filter(kind="feedback").update(unread_by_staff=False)


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0020_customer_success'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='supportrequest',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='supportrequest',
            name='attachment',
            field=models.FileField(blank=True, default='', max_length=255, upload_to=tenancy.uploads.support_file_path),
        ),
        migrations.AddField(
            model_name='supportrequest',
            name='category',
            field=models.CharField(blank=True, choices=[('bug', 'Bug'), ('technical', 'Technical issue'), ('attendance', 'Attendance issue'), ('leave', 'Leave issue'), ('task', 'Task issue'), ('billing', 'Billing issue'), ('domain', 'Domain issue'), ('login', 'Login issue'), ('feature_request', 'Feature request'), ('other', 'Other')], db_default='', db_index=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='supportrequest',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supportrequest',
            name='context',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='supportrequest',
            name='escalated',
            field=models.BooleanField(db_default=False, default=False),
        ),
        migrations.AddField(
            model_name='supportrequest',
            name='first_response_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supportrequest',
            name='number',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='supportrequest',
            name='priority',
            field=models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], db_default='medium', db_index=True, default='medium', max_length=10),
        ),
        migrations.AddField(
            model_name='supportrequest',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supportrequest',
            name='roadmap_status',
            field=models.CharField(blank=True, choices=[('submitted', 'Submitted'), ('under_review', 'Under review'), ('planned', 'Planned'), ('in_development', 'In development'), ('completed', 'Completed')], db_default='', default='', max_length=20),
        ),
        migrations.AddField(
            model_name='supportrequest',
            name='satisfaction_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supportrequest',
            name='satisfaction_comment',
            field=models.TextField(blank=True, db_default='', default=''),
        ),
        migrations.AddField(
            model_name='supportrequest',
            name='satisfaction_rating',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supportrequest',
            name='screenshot',
            field=models.FileField(blank=True, default='', max_length=255, upload_to=tenancy.uploads.support_file_path),
        ),
        migrations.AddField(
            model_name='supportrequest',
            name='sla_due_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='supportrequest',
            name='sla_paused_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supportrequest',
            name='unread_by_customer',
            field=models.BooleanField(db_default=False, default=False),
        ),
        migrations.AddField(
            model_name='supportrequest',
            name='unread_by_staff',
            field=models.BooleanField(db_default=True, default=True),
        ),
        migrations.AddField(
            model_name='supportrequest',
            name='url',
            field=models.CharField(blank=True, db_default='', default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='supportrequest',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('in_progress', 'In progress'), ('waiting_customer', 'Waiting for you'), ('resolved', 'Resolved'), ('closed', 'Closed')], db_index=True, default='open', max_length=20),
        ),
        migrations.CreateModel(
            name='ProductUpdate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=160)),
                ('summary', models.CharField(blank=True, default='', max_length=300)),
                ('body', models.TextField(blank=True, default='')),
                ('category', models.CharField(choices=[('new', 'New'), ('improved', 'Improved'), ('fixed', 'Fixed'), ('announcement', 'Announcement')], default='new', max_length=20)),
                ('link', models.CharField(blank=True, default='', max_length=200)),
                ('published_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-published_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StatusNotice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('component', models.CharField(choices=[('platform', 'Platform'), ('email', 'Email delivery'), ('storage', 'File storage'), ('payments', 'Payments'), ('domains', 'Domain verification'), ('attendance', 'Attendance services')], max_length=20)),
                ('level', models.CharField(choices=[('maintenance', 'Maintenance'), ('degraded', 'Degraded'), ('outage', 'Outage')], default='degraded', max_length=20)),
                ('message', models.CharField(max_length=500)),
                ('starts_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-starts_at'],
            },
        ),
        migrations.CreateModel(
            name='SupportMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('author_name', models.CharField(blank=True, default='', max_length=150)),
                ('author_kind', models.CharField(choices=[('customer', 'Customer'), ('staff', 'Support team'), ('system', 'System')], max_length=10)),
                ('body', models.TextField(blank=True, default='')),
                ('is_internal', models.BooleanField(default=False)),
                ('attachment', models.FileField(blank=True, default='', max_length=255, upload_to=tenancy.uploads.support_file_path)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='tenancy.supportrequest')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
            migrations.RunPython(adopt_existing_requests, migrations.RunPython.noop),
    ]
