# Generated by Django 5.2.17 on 2026-10-07 12:20

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0021_customer_success_center'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='supportrequest',
            name='sla_alerts',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='platformmetric',
            name='key',
            field=models.CharField(choices=[('login_ok', 'Login succeeded'), ('login_failed', 'Login failed'), ('provision_ok', 'Provisioning succeeded'), ('provision_failed', 'Provisioning failed'), ('email_sent', 'Platform email sent'), ('email_failed', 'Platform email failed'), ('active_user', 'Active user (once per person per day)'), ('attendance_used', 'Attendance recorded'), ('leave_used', 'Leave applied for'), ('task_used', 'Task created'), ('document_used', 'Document created'), ('employee_added', 'Employee added'), ('ticket_deflected', 'Ticket answered by the assistant')], db_index=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='productupdate',
            name='category',
            field=models.CharField(choices=[('new', 'New'), ('improved', 'Improved'), ('fixed', 'Fixed'), ('release', 'Release notes'), ('announcement', 'Announcement'), ('maintenance', 'Maintenance')], default='new', max_length=20),
        ),
        migrations.CreateModel(
            name='SuccessTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('follow_up', 'Follow up'), ('call', 'Call customer'), ('meeting', 'Schedule meeting'), ('training', 'Product training'), ('onboarding_review', 'Onboarding review')], default='follow_up', max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('notes', models.TextField(blank=True, default='')),
                ('due_date', models.DateField(blank=True, db_index=True, null=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('done', 'Done'), ('cancelled', 'Cancelled')], db_index=True, default='open', max_length=10)),
                ('auto_reason', models.CharField(blank=True, db_index=True, default='', max_length=40)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='success_tasks', to='tenancy.organization')),
            ],
            options={
                'ordering': ['status', 'due_date', '-created_at'],
            },
        ),
    ]
