# Generated by Django 5.2.17 on 2026-10-07 15:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


# The four teams the desk starts with, and which ticket categories each owns.
# Platform staff are added to them from the console; until then a ticket is
# still owned -- by its team -- and shows in that team's queue.
TEAMS = [
    ("technical", "Technical Team", "Bugs and anything not working as it should.",
     ["bug", "technical", "attendance", "leave", "task"], False),
    ("billing", "Billing Team", "Payments, invoices, renewals and plan changes.",
     ["billing"], False),
    ("customer-success", "Customer Success Team",
     "Questions, onboarding, training and feature requests.",
     ["other", "feature_request"], True),
    ("platform", "Platform Team", "Sign-in, custom domains and the platform itself.",
     ["login", "domain"], False),
]


def seed_teams(apps, schema_editor):
    Team = apps.get_model("tenancy", "SupportTeam")
    Request = apps.get_model("tenancy", "SupportRequest")
    route = {}
    default = None
    for key, name, description, categories, is_default in TEAMS:
        team, _ = Team.objects.get_or_create(key=key, defaults={
            "name": name, "description": description, "categories": categories,
            "is_default": is_default})
        for c in categories:
            route[c] = team
        if is_default:
            default = team
    # Every existing ticket gets an owner too, not only the new ones.
    for r in Request.objects.exclude(kind="feedback").filter(team__isnull=True):
        r.team = route.get(r.category) or default
        r.save(update_fields=["team"])


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0022_customer_success_2'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportTeam',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.SlugField(max_length=40, unique=True)),
                ('name', models.CharField(max_length=80)),
                ('description', models.CharField(blank=True, default='', max_length=300)),
                ('categories', models.JSONField(blank=True, default=list)),
                ('is_default', models.BooleanField(default=False)),
                ('auto_assign', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='successtask',
            name='ticket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='tenancy.supportrequest'),
        ),
        migrations.AddField(
            model_name='supportrequest',
            name='escalated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supportrequest',
            name='escalation_level',
            field=models.PositiveSmallIntegerField(db_default=0, default=0),
        ),
        migrations.AlterField(
            model_name='platformmetric',
            name='key',
            field=models.CharField(choices=[('login_ok', 'Login succeeded'), ('login_failed', 'Login failed'), ('provision_ok', 'Provisioning succeeded'), ('provision_failed', 'Provisioning failed'), ('email_sent', 'Platform email sent'), ('email_failed', 'Platform email failed'), ('active_user', 'Active user (once per person per day)'), ('attendance_used', 'Attendance recorded'), ('leave_used', 'Leave applied for'), ('task_used', 'Task created'), ('document_used', 'Document created'), ('employee_added', 'Employee added'), ('ticket_deflected', 'Ticket answered by the assistant'), ('assist_shown', 'Assistant suggestions shown')], db_index=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='successtask',
            name='kind',
            field=models.CharField(choices=[('follow_up', 'Follow up'), ('call', 'Call customer'), ('meeting', 'Schedule meeting'), ('training', 'Product training'), ('onboarding_review', 'Onboarding review'), ('domain_setup', 'Domain setup'), ('payment_verification', 'Payment verification'), ('outreach', 'Customer outreach')], default='follow_up', max_length=20),
        ),
        migrations.CreateModel(
            name='KnownIssue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('symptoms', models.TextField(blank=True, default='')),
                ('workaround', models.TextField(blank=True, default='')),
                ('category', models.CharField(blank=True, default='', max_length=20)),
                ('state', models.CharField(choices=[('investigating', 'Investigating'), ('workaround', 'Workaround available'), ('fixed', 'Fixed')], db_index=True, default='investigating', max_length=20)),
                ('is_public', models.BooleanField(default=True)),
                ('deflected_count', models.PositiveIntegerField(default=0)),
                ('fixed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['state', '-updated_at'],
            },
        ),
        migrations.AddField(
            model_name='supportrequest',
            name='known_issue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='tenancy.knownissue'),
        ),
        migrations.CreateModel(
            name='SuccessCampaign',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=160)),
                ('segment', models.CharField(choices=[('inactive', 'Inactive customers'), ('low_health', 'Low health customers'), ('trial', 'Trial customers'), ('near_renewal', 'Near renewal')], max_length=20)),
                ('task_kind', models.CharField(choices=[('follow_up', 'Follow up'), ('call', 'Call customer'), ('meeting', 'Schedule meeting'), ('training', 'Product training'), ('onboarding_review', 'Onboarding review'), ('domain_setup', 'Domain setup'), ('payment_verification', 'Payment verification'), ('outreach', 'Customer outreach')], default='outreach', max_length=20)),
                ('task_title', models.CharField(max_length=200)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='successtask',
            name='campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='tenancy.successcampaign'),
        ),
        migrations.AddField(
            model_name='supportrequest',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='tenancy.supportteam'),
        ),
        migrations.CreateModel(
            name='SupportMention',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentions', to='tenancy.supportmessage')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenancy.supportrequest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('message', 'user'), name='uniq_support_mention')],
            },
        ),
        migrations.CreateModel(
            name='SupportTeamMember',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('lead', 'Team lead'), ('agent', 'Agent')], default='agent', max_length=10)),
                ('is_available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='tenancy.supportteam')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_teams', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['team', 'role', 'created_at'],
                'constraints': [models.UniqueConstraint(fields=('team', 'user'), name='uniq_support_team_member')],
            },
        ),
        migrations.CreateModel(
            name='SupportTicketLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('from_ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenancy.supportrequest')),
                ('to_ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenancy.supportrequest')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('from_ticket', 'to_ticket'), name='uniq_support_ticket_link')],
            },
        ),
        migrations.RunPython(seed_teams, migrations.RunPython.noop),
    ]
